ENH: pydanticをv2へ
VOICEVOX/voicevox_engine pull request #1184
Opened 2024-04-17 09:35 UTC by sabonerune

## 内容

`Pydantic`を2.7へ更新します。

ref: [Migration Guide - Pydantic](https://docs.pydantic.dev/latest/migration/)

現状`FastAPI`のバグが原因と思われる問題があるためドラフトにしています。

## 関連 Issue

- ref: #995

## その他

### 現状の問題

特に問題になりそうなのは以下の二つです。

#### OpenAPIスキーマーがおかしい

オプションのクエリやフォームで`null`が使用可能と記述されています。
これは多分誤りです。

#### Swagger UIの表示が壊れている

上記が原因でドキュメントのUIが壊れています。
例
<img width="500" alt="比較" src="https://github.com/VOICEVOX/voicevox_engine/assets/102559104/75071600-0e6f-4bb3-97c4-c3418a6e54b7">

その他気になる挙動
- `test_post_user_dict_word_422.json`でPydanticの情報まで出てきている?
これは意図的?
- `separate_input_output_schemas=True`にしたときドキュメントの記載と動作が異なる?
`False`に指定したため影響はない
ref: [Separate OpenAPI Schemas for Input and Output or Not - FastAPI](https://fastapi.tiangolo.com/how-to/separate-openapi-schemas/)

2024-04-30 11:51 UTC, Hiroshiba commented
バグが直るの楽しみです…！！

2024-06-06 15:22 UTC, sabonerune commented
OpenAPIスキーマーの問題は恐らく仕様らしいのでドラフトを解除します。

2024-06-06 16:07 UTC, sabonerune commented
Swagger UIが壊れる問題に対処するため`SkipJsonSchema[None]`を使用しています。
ref: https://github.com/tiangolo/fastapi/discussions/10654

2024-06-06 17:14 UTC, tarepan requested changes
- 👍️ 移行ガイドに沿い、適切に関数・クラスを変更しています。good work!
- 👍️ 移行以外の変更を極力控え、レビューしやすい変更です。great!
- [ ] 変数名をより明確にし、更に可読性を向上できます
- [ ] 機能追加・変更か否か、確認が必要な箇所があります

----------------------------------------------------------
レビュー用情報  

- リネーム
  - `.dict()` → `.model_dump()` ([migration docs](https://docs.pydantic.dev/latest/migration/#changes-to-pydanticbasemodel))
  - `.validate()` → `.model_validate()` ([docs](https://docs.pydantic.dev/latest/api/base_model/#pydantic.BaseModel))
  - `.copy()` → `.model_copy()` ([migration docs](https://docs.pydantic.dev/latest/migration/#changes-to-pydanticbasemodel))
- 置き換え
  - `parse_obj_as()` → `TypeAdapter` ([migration docs](https://docs.pydantic.dev/latest/migration/#introduction-of-typeadapter))
  - `| None` → `| SkipJsonSchema[None]`

2024-06-06 17:14 UTC, tarepan commented on voicevox_engine/model.py
> +        default=None,
同上（仕様変更）

2024-06-06 17:14 UTC, tarepan commented on voicevox_engine/preset/preset_manager.py
> +            adapter = TypeAdapter(list[Preset])
同上（変数名）

2024-06-06 17:14 UTC, tarepan commented on voicevox_engine/setting/setting_manager.py
> +    allow_origin: str | None = Field(default=None, title="許可するオリジン")
同上（仕様変更）

2024-06-06 17:14 UTC, tarepan commented on voicevox_engine/tts_pipeline/model.py
> +    consonant: str | None = Field(default=None, title="子音の音素")
同上（仕様変更）

2024-06-06 17:14 UTC, tarepan commented on voicevox_engine/user_dict/model.py
> +    mora_count: int | None = Field(default=None, title="モーラ数")
同上（仕様変更）

2024-06-06 17:14 UTC, tarepan commented on test/e2e/__snapshots__/test_openapi/test_OpenAPIの形が変わっていないことを確認.json
> +                "type": "null"
`"required": false` でなく "anyOf null" になっているように見えます。  
意図的な変更でしょうか？

2024-06-06 22:03 UTC, sabonerune commented on voicevox_engine/library/library_manager.py
> +                library_info = downloadable_library.model_dump_json()
`indent=4`は必要ですね。
抜け落ちてしまいました。

2024-06-06 22:49 UTC, sabonerune commented on voicevox_engine/engine_manifest.py
> +    contributors: list[str] | None = Field(default=None, title="貢献者名")
Pydantic V1ではデフォルトが設定されていない場合、属性がなくてもインスタンス化が可能なはずです。
また、スキーマーにも反映されているがはずです。
`default=None`を外してしまうとOpenAPIに破壊的変更が起こってしまう可能性があります。

2024-06-06 23:03 UTC, sabonerune commented on test/e2e/__snapshots__/test_openapi/test_OpenAPIの形が変わっていないことを確認.json
> +                "type": "null"
Pydantic V2の仕様変更で出力されるスキーマーが正確になったという感じです。

2024-06-07 07:27 UTC, tarepan commented on voicevox_engine/engine_manifest.py
> +    contributors: list[str] | None = Field(default=None, title="貢献者名")
> Pydantic V1ではデフォルトが設定されていない場合、属性がなくてもインスタンス化が可能  

👍️  
こちらが正しい理解です（[v1 docs](https://docs.pydantic.dev/1.10/usage/models/#required-optional-fields)）。v1 で動作確認したところ `None` の自動挿入を確認しました。  
移行ガイドでもデフォルト引数に関する挙動変更が書かれていました（[migration guide](https://docs.pydantic.dev/latest/migration/#required-optional-and-nullable-fields)）。  
上記は妥当でない指摘でした、撤回します。丁寧な解説ありがとうございました🙇

2024-06-07 07:56 UTC, tarepan commented on test/e2e/__snapshots__/test_openapi/test_OpenAPIの形が変わっていないことを確認.json
> +                "type": "null"
スキーマが正確になったのではなく、マイグレーション不足で意図しないスキーマ変更が起きていると考えます（以下、検証と考察）。  

スキーマに diff が入っている `UpdateInfo.contributors` 属性について、`list[str] | None` を `list[str] | SkipJsonSchema[None]` とすると diff が無くなりました。  
これは PR 冒頭にあるとおり、`: X | None` を Nullable と解釈する仕様変更に伴うものです。  

このマイグレーションをしない場合、新スキーマは `required: false` かつ `Nullable` になり、今までの「field に値を入れる or field ごと無い」から「field に値を入れる or field に Null を入れる or field ごと無い」へ仕様変更が起きます。  

ゆえに `SkipJsonSchema` を用いてマイグレーションすべき箇所と考えます。

2024-06-07 08:53 UTC, Hiroshiba commented on test/e2e/__snapshots__/test_openapi/test_OpenAPIの形が変わっていないことを確認.json
> +                "type": "null"
何を正しいとするかだと思います。
V1→V2の変更で、今のPython実装に合うようになります。

例えばpause_moraは`required=false`ですが、
https://github.com/VOICEVOX/voicevox_engine/blob/3cd83de8cf3de4d935cfa88c4edc20e8a3268c60/voicevox_engine/tts_pipeline/model.py#L44
実態としてnoneが返ってきてました。
https://github.com/VOICEVOX/voicevox_engine/blob/3cd83de8cf3de4d935cfa88c4edc20e8a3268c60/test/e2e/single_api/tts_pipeline/__snapshots__/test_audio_query/test_post_audio_query_200.json#L48

2024-06-07 09:30 UTC, tarepan commented on test/e2e/__snapshots__/test_openapi/test_OpenAPIの形が変わっていないことを確認.json
> +                "type": "null"
@Hiroshiba  
スキーマを実態に合わせて変更することは仕様変更（update or fix）です。  
リファクタリングの一種である bump PR で仕様変更をするのはバットプラクティスです（悪影響例: `update_infos.json` 作るときに `開発環境の向上` と誤認して記載を忘れる）。  
仕様変更は後続 PR でおこなうのが適切と考えます。

2024-06-07 09:33 UTC, sabonerune commented on test/e2e/__snapshots__/test_openapi/test_OpenAPIの形が変わっていないことを確認.json
> +                "type": "null"
自分は今までのスキーマーが間違っていたという認識です。

Pydantic V1のVOICEVOX Engineで`contributors`のキーがない`update_infos.json`を読み込ませて`/manifest`を叩くと`contributors`に`null`が入ったjsonが返されます。
これは`pydantic`のインスタンスにはフィールドがないという状態がないということと`None`が入ったフィールドは`null`にシリアライズされるからです。
`SkipJsonSchema`はあくまでスキーマーの出力を変えるだけです。
これを直す場合Pydanticのシリアライズの処理周りも同時に変えないといけないと思います。

UpdateInfoはEngineManifestの出力にしか使用していないためこのAPI変更による影響はほぼないと考えています。

2024-06-07 09:45 UTC, sabonerune commented on voicevox_engine/app/routers/user_dict.py
> +                json_schema_extra={"maximum": MAX_PRIORITY, "minimum": MIN_PRIORITY},
これは`SkipJsonSchema[None]`の副作用(?)でJsonSchemaから`ge=MIN_PRIORITY`と`le=MAX_PRIORITY`の情報が何故か抜け落ちてしまっていたので対処したものです。

自分でもすっかり忘れていました。
コメントを付けておきます。

2024-06-08 06:31 UTC, Hiroshiba commented on test/e2e/__snapshots__/test_openapi/test_OpenAPIの形が変わっていないことを確認.json
> +                "type": "null"
スキーマと実装が乖離してるという認識は３人とも揃ってるはずです。
そのうえでスキーマの変更をどれくらい強い仕様変更だと想定するか、という話だと思います。

@sabonerune UpdateInfoだけなら大丈夫かもですが、pause_moraが一番でかいのでこれ基準で考えるのが良い気がしました。
他もpause_moraと扱い合わせるのが手っ取り早いかなと。（５種類くらいあるので１つずつ判断が大変）

---

個人的には、FastAPIの現仕様はFastAPIにとっても想定外なのではと感じています。
将来、pydantic v1と同じ挙動に戻る気がする。なのでまあ、２択だと思います

1. APIを理想形に近づくようにワークアラウンド（結果としてAPIが変わらない形になる）
2. さほど影響がないと判断して変えちゃう、変更は更新履歴で案内する

個人的には、よほどしんどくなければワークアラウンドが良いのかな〜と思い直しました。
`int | SkipJsonSchema[None]`とするのは若干面倒ですが、例えば
`NonRequired[T] = T | SkipJsonSchema[None]`みたいな型を定義して使い回せばあまりしんどくないかもです。
（あと、APIドキュメントの案内が多少変わるくらいなら、まあ見逃しても別に良い気もしてます。困る人は０人だと思う。）

（↑の方針で行くなら関係ないですが）あとAPIの変更はこのPRでやる形が丸いと思います。
v2へのアプデとデータ構造変更が完全に対応している（片方だけrevertしたいことがない）ためです。
ただタイトル内容と乖離するので、もしやるならタイトルを変えるべきだと思います。

2024-06-08 07:34 UTC, tarepan commented on test/e2e/__snapshots__/test_openapi/test_OpenAPIの形が変わっていないことを確認.json
> +                "type": "null"
（意思決定のための情報共有です）  

FastAPI は path operation 引数として `response_model_exclude_none` をもち、これにより値が `None` な field を除去できます。  
ゆえに、現在のスキーマが理想形とするのであれば、乖離は `response_model_exclude_none` オプションを正しく設定していないサーバー実装に起因すると言えます。逆に現在の実装挙動を理想形とするなら、`response_model_exclude_none` オプションは不要で、乖離は API 定義に起因すると言えます。  
これは pydantic の bump で顕在化した潜在バグであり、 pydantic の問題ではなく API 設計・実装の問題だと言えそうです（v1 維持であっても修正の必要がある）。

2024-06-08 08:01 UTC, Hiroshiba commented on test/e2e/__snapshots__/test_openapi/test_OpenAPIの形が変わっていないことを確認.json
> +                "type": "null"
@tarepan 
確かにどっちにしても修正は必要ですね！

お答えするために色々考えてたのですが、さっきお答えした２択はスキーマのことしか考えてなかったことに気づきました。。
むしろ多分ユーザーにとって大事なのは実装側（どんなものが帰ってくるか）で、こっちを変更するかしないかが大事な気がしてきました。

となるとさっきの二択はかなり変わって、最終的に目指す形は以下の2つになりそうです。

1. v1のAPIを真だとする。返すデータ構造を変える。サードパーティーアプリにとって大きな変更になるので、ツイートも含めてしっかり案内する。v2にするならワークアラウンドも実装する。
2. v1の実装を真だとする。V2に沿ってスキーマ側を変えればOK。変更は軽く案内すれば良さそう。

個人的には2が良い気がしてます。
1の理想形に近づけるのがきれいなAPIになるかもしれませんが、個人的にはそんなに恩恵ないだろうなとも感じます。
さっき1推しだったのは、どちらかというと手数が少なかったからそれでいいかなと思っていました。

もし1で行く場合、@tarepan さんのおっしゃる通り実装側をスキーマに寄せたり、あと案内もしなくちゃだったりで大変そうだなと。
であればとりあえず v2に寄せちゃって、FastAPIが色々変えたらこちらも乗っかるかどうか再考するのがいいんじゃないかなと･･･！

2024-06-08 16:14 UTC, tarepan commented on test/e2e/__snapshots__/test_openapi/test_OpenAPIの形が変わっていないことを確認.json
> +                "type": "null"
@Hiroshiba @sabonerune  
スキーマ修正案（上記 *2*）を採用する場合、ENGINE 外への影響はどの程度になるのでしょうか？  

VOICEVOX editor はパッと見た感じスキーマファイル `openapi.json` からコード自動生成をしているようでした。もしそうなら editor 側にそれなりの修正が入る気がします（union が "not_required | value" から "not_required | value | null" に変わるため）。  
また API docs でスキーマファイルを配布している以上、ENGINE ユーザーがスキーマからコード自動生成していることは想定すべき事項かと思います。その意味で ENGINE を組み込んでいるユーザーにも影響すると考えます。  

![image](https://github.com/VOICEVOX/voicevox_engine/assets/19833110/b2db06d7-0846-48cc-892f-2823e271354d)

（私は VOICEVOX 全体の動向に疎いので）お二人の見立てをお聞きできると嬉しいです。  

-----------------------------------------------------------------------------------

私が挙げた影響範囲に限っても、*1* 案であれ *2* 案であれ、それなりに慎重に検討・実装・周知すべき事項のように見えます。  
本 PR が様々なファイルに変更を入れておりコンフリクトしがちであること、慎重な進行は時間が必要でその間にコンフリクトが増えていくこと、ベストプラクティスは bump と fix を分離すること。  
これらを考慮すると、本 PR は `SkipJsonSchema` を使ってサクッと merge し後続 PR で上記課題に取り組むのが進行上スムーズである、というのが私の見解です。   
もちろんコンフリクトしてでも本 PR で一括解決するという進行もアリだと思いますので、どちらの進行でいくかは PR author と maintainer の意見を尊重する所存です。

2024-06-09 01:05 UTC, Hiroshiba commented on test/e2e/__snapshots__/test_openapi/test_OpenAPIの形が変わっていないことを確認.json
> +                "type": "null"
@tarepan 考慮ありがとうございます。

スキーマを実装に合わせるのは、問題になる例が思いてない感じです。更に考えても思いつかないので、無い気がしてます。
なぜかというと単純に、間違ってるスキーマを信用してコードを書いても正しく動かないので、みんな必ず実装に合わせたコードを書くんですよね。
なので破壊的変更になっておらず、影響範囲は小さいという認識です。

ちなみにエディタ（TypeScript）は"not_required | value"も"not_required | value | null"もどっちも`?`（Optional Property）だと思います。

まあでもそれはさておき、とりあえず変更がない形にして先にマージを目指すというのはありだと思います。
`SkipJsonSchema`をつけまくる形で進めていただければ･･･！！

2024-06-09 09:16 UTC, sabonerune commented on test/e2e/__snapshots__/test_openapi/test_OpenAPIの形が変わっていないことを確認.json
> +                "type": "null"
実装をスキーマーに合わせる場合`pause_mora`など入力と出力の両方に利用する部分では問題が起こる可能性があると思います。
1. v1API環境でクエリを作成して保存する(`pause_mora`は`null`になる)
2. 保存したクエリを厳密にv1APIでバリテーションすると`pause_mora`に`null`は許可されていないためエラーになる。

といった感じです。

2024-06-09 09:19 UTC, Hiroshiba commented on test/e2e/__snapshots__/test_openapi/test_OpenAPIの形が変わっていないことを確認.json
> +                "type": "null"
なるほどです。更に考慮事項が増えてしまう、ということですよね･･･。

Skipをつけてその問題が起きないのであれば、とりあえずSkipする形が良さそうに思いました！！

2024-06-09 11:09 UTC, tarepan approved these changes
LGTM👍️

2024-06-09 15:49 UTC, sabonerune commented on test/e2e/__snapshots__/test_openapi/test_OpenAPIの形が変わっていないことを確認.json
> +                "type": "null"
ふと思い出したのですがFastAPIがpydantic V2のModelと同じ挙動になるのはないとおもいます。
というのも[`separate_input_output_schemas`](https://fastapi.tiangolo.com/how-to/separate-openapi-schemas/)という形でPydanticの入力と出力の対応が異なるという問題に対処しているからです。

今回のPRではこれをTrueにしてしまうとスキーマーが大きく変わってしまうためFalseにしてあります。

2024-06-10 19:25 UTC, Hiroshiba commented on test/e2e/__snapshots__/test_openapi/test_OpenAPIの形が変わっていないことを確認.json
> +                "type": "null"
ちゃんとわかってないかもなのですが、`separate_input_output_schemas=true`なら同じ挙動になる気がします。

PydanticはV2であれV1であれ「キーがない」という型を表現できないんですよね。
APIの入力側はこの仕様でも問題ないはず。
`value=null`がAPIに投げられてもOK、投げなくてもOKにすれば良いだけなので。

問題は出力側で、pydanticは必ず全キーがあるモデルしか定義できない。
その折衷案がFastAPIの`separate_input_output_schemas=true`で、実装をpydanticに合わせた形だと思います。
逆にV2&`separate_input_output_schemas=false`やV1のときはスキーマと実装がずれる。

よくよく考えると、別にこの辺りでpydanticがV1からV2になって変わったことはないはずで、V2に対応するときにFastAPI側がバグっぽい挙動を直したって感じな気がします。

2024-06-10 20:02 UTC, Hiroshiba approved these changes
LGTM！！！

なんかいろいろ考えたのですが、めちゃくちゃややこしいですね！！！
スキーマの互換性まで考えると、もう「キーがない」＝＝「デフォルト値がNone」くらいに制限強めないとダメな気がしてきました。。

１箇所コメント追加だけこちらでさせていただきます！

2024-06-10 20:05 UTC, merged

2024-06-12 06:26 UTC, tarepan commented on test/e2e/__snapshots__/test_openapi/test_OpenAPIの形が変わっていないことを確認.json
> +                "type": "null"
> pydanticは必ず全キーがあるモデルしか定義できないから、出力は必ず`value=null`になる。  

pydantic にはこれに対応するための仕組みがあります。  

```python
from pydantic import BaseModel, Field
from pydantic.json_schema import SkipJsonSchema


class APIModel(BaseModel):
  required: int
  not_required: int | SkipJsonSchema[None] = None


api_model = APIModel(required=10)
print(api_model)
# required=10 not_required=None

api_model_dict = api_model.model_dump()
print(api_model_dict)
# {'required': 10, 'not_required': None}

api_model_dict = api_model.model_dump(exclude_none=True)
print(api_model_dict)
# {'required': 10}
```

2024-06-18 14:01 UTC, Hiroshiba commented on test/e2e/__snapshots__/test_openapi/test_OpenAPIの形が変わっていないことを確認.json
> +                "type": "null"
それは･･･noneをexcludeしているのであって、requiredを表現できてるわけではない気がします！

* RequiredでNoneが入りうる型
* NonRequiredでNoneが入らない型

の２つが同時に満たせないとですかね

2024-06-25 13:49 UTC, sabonerune commented on test/e2e/__snapshots__/test_openapi/test_OpenAPIの形が変わっていないことを確認.json
> +                "type": "null"
> - RequiredでNoneが入りうる型
> - NonRequiredでNoneが入らない型
>
> の２つが同時に満たせないかなと

一応できた？

```python
from typing import Annotated, Any

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    ValidationInfo,
    ValidatorFunctionWrapHandler,
    WrapValidator,
)
from pydantic.json_schema import SkipJsonSchema
from pydantic_core import PydanticCustomError


def non_null_validator(
    v: Any, handler: ValidatorFunctionWrapHandler, info: ValidationInfo
) -> Any:
    result = handler(v)
    if result is None:
        raise PydanticCustomError(
            "null_error",
            '"{field_name}" is optional but cannot be null.',
            {"field_name": info.field_name},
        )
    return result


class Model(BaseModel):
    model_config = ConfigDict(validate_assignment=True)
    required: int
    optional: Annotated[
        int | SkipJsonSchema[None],
        WrapValidator(non_null_validator),
    ] = Field(default=None)
    required_nullable: int | None
    optional_nullable: int | None = Field(default=None)


try:
    Model(required=10, optional=None)
except ValueError as e:
    print(e)
    # 2 validation errors for Model
    # optional
    #   "optional" is optional but cannot be null. [type=null_error, input_value=None, input_type=NoneType]
    # required_nullable
    #   Field required [type=missing, input_value={'required': 10, 'optional': None}, input_type=dict]
    #     For further information visit https://errors.pydantic.dev/2.7/v/missing
m = Model(required=10, required_nullable=None, optional_nullable=None)
print(m)
# required=10 optional=None required_nullable=None optional_nullable=None
m.optional = 5
try:
    m.optional = None
except ValueError as e:
    print(e)
    # optional
    #   "optional" is optional but cannot be null. [type=null_error, input_value=None, input_type=NoneType]
del m.optional
print(m)
# required=10 required_nullable=None optional_nullable=None
print(m.model_dump_json(exclude_unset=True))
# {"required":10,"required_nullable":null,"optional_nullable":null}
```

`del m.optional`が怪しいですが…

あと`exclude_none=True`や`exclude_unset=True`両方に言えるのですがこの設定はFastAPIのエンドポイントやpydanticのdump時に指定するものでモデルそのものに設定できないといのも問題だと思います。
(カスタムシリアライザを使えば表現可能な気がしますが管理が面倒だと思います。)

また、既存のモデルにこの`non_null_validator`を入れると保存しておいた以前のエンジンで生成したクエリをそのまま新しいエンジンに投げるとエラーになるという実質的な破壊的変更が起こります。