FIX: `Jinja2Templates`の`DeprecationWarning`を解消
VOICEVOX/voicevox_engine pull request #1398
Opened 2024-06-12 22:09 UTC by sabonerune

## 内容

`Jinja2Templates`周りの`DeprecationWarning`を解消します。

- ref: https://fastapi.tiangolo.com/advanced/templates/#using-jinja2templates
>Before FastAPI 0.108.0, Starlette 0.29.0, the name was the first parameter.
>
>Also, before that, in previous versions, the request object was passed as part of the key-value pairs in the context for Jinja2.
- ref: https://www.starlette.io/templates/

2024-06-12 23:03 UTC, tarepan approved these changes
LGTM👍️  

- `TemplateResponse` の引数変更により `DeprecationWarning: The name is not the first parameter anymore.` が消失することを確認しました。nice!
- `Jinja2Templates` の引数変更により `DeprecationWarning: Extra environment options are deprecated.` が消失することを確認しました。good work!
  - FastAPI 側であまり丁寧に説明されていない `directory` 周りの移行が正しくおこなわれています。great!

2024-06-12 23:08 UTC, tarepan requested changes
（レビュー抜けがありました🙇）  

- [x] `jinja2` の直接インポートにより `pyproject.toml` の `jinja2` に対する `# NOTE: required by fastapi` が古い記述になったため、これを消す必要があります

2024-06-13 09:45 UTC, sabonerune commented
@tarepan 修正しました。

2024-06-13 12:34 UTC, tarepan approved these changes
LGTM👍️

2024-06-16 03:35 UTC, tarepan commented
@sabonerune  
レビューで指摘し修正して頂いた `# NOTE: required by fastapi` に関してです。  
削除は私の考慮が足りておらず、維持が望ましいということが判明しました（ref. #1400）。  
修正のリバートをお願いします、お手数おかけします🙇

2024-06-16 14:25 UTC, Hiroshiba approved these changes
LGTM！！

なんか危ない記法だよなぁと思ってたのでこの変更はありがたいですね！！

pyproject.toml内のコメント、こちらでrevertさせていただきます！

2024-06-16 14:26 UTC, Hiroshiba commented on pyproject.toml
> +jinja2 = "^3.1.3"
```suggestion
jinja2 = "^3.1.3" # NOTE: required by fastapi
```

2024-06-16 14:58 UTC, merged