feat: 自動調整によって擬似的に疑問文に対応する
VOICEVOX/voicevox_engine pull request #229
Opened 2021-12-10 16:00 UTC by qwerty2501

## 内容

疑問文を疑問文ぽく聞こえるように音素を調整する

## 関連 Issue

refs #222

2021-12-10 16:01 UTC, qwerty2501 commented on voicevox_engine/full_context_label.py
> +        is_interrogative: bool
とりあえず他の関数にならってコメント書いたんですが、コメントで戻り値の型を明示しないといけないんですかね？

2021-12-10 16:19 UTC, qwerty2501 commented on voicevox_engine/full_context_label.py
> +    def is_interrogative(self):
音素が質問かどうか判定する必要を感じたのでとりあえず追加

2021-12-10 17:15 UTC, aoirint commented on voicevox_engine/full_context_label.py
> +        is_interrogative: bool
この形式のコメント（docstring）はこのリポジトリとして必須ではなかったと思いますが、 #59 で整備していきたいということにはなっています。
戻り値の型なども負担にならない範囲で書いておくと、コードが読みやすくなると思います！

Pythonのdocstringにはいくつかの記法があるようなのですが、このリポジトリではNumPyスタイルという記法を採用しています。

- <https://numpydoc.readthedocs.io/en/v1.1.0/format.html>
- <https://qiita.com/flcn-x/items/393c6f1f1e1e5abec906#numpy%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB>


型ヒントの方針はわかりませんが、個人的にはdocstringと同様に書いてあった方が読みやすいと感じています。

- <https://docs.python.org/ja/3.8/library/typing.html>

2021-12-10 17:40 UTC, qwerty2501 commented on voicevox_engine/full_context_label.py
> +        is_interrogative: bool
> 戻り値の型なども負担にならない範囲で書いておくと、コードが読みやすくなると思います！

見た感じ関数の戻り値の型として明示的に書いてもそれを自動的にdocstringに反映してくれなさそうですね・・・
とりあえずはこのままにしておこうと思います

2021-12-11 04:15 UTC, qwerty2501 commented
ラベルのメンテで説明がないと100%積むのでソースコード中のコメントで https://github.com/VOICEVOX/voicevox_engine/issues/222#issuecomment-991066787 のリンクがあると良いと思いました

2021-12-11 09:34 UTC, qwerty2501 reviewed
単体テストコードはどこに書けばよいですか？

2021-12-11 09:34 UTC, qwerty2501 commented on voicevox_engine/model.py
> +    is_interrogative: bool = Field(title="疑問の発音を表現するモーラかの判定")
エンジンでMoraを変換後に疑問系かどうか判定する必要があったのでやむなくここに追加
名称が `is_interrogative` だと `full_context_label.Phoneme` の `is_interrogative` とずれているので名前を変えるべきか？

2021-12-11 09:34 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +                    moras=full_context_label_moras_to_moras(
疑問系発音のMoraを追加した状態のmorasで束縛したかったため、処理を関数作って移動させた。
そもそもこのreturnのところで使っているでかいList内包表記は複雑すぎるのでやめたほうが良いような気がしたがとりあえずそのままにした

2021-12-11 09:34 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +    ) -> List[AccentPhrase]:
とりあえずBaseに実装したが、この関数は abstractmethodにして実装は `SynthesisEngine`に実装したほうが良いかもしれない？

2021-12-11 09:34 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +def add_interrogative_mora_if_last_phoneme_is_interrogative(
関数名が長過ぎるので短くしたい

2021-12-11 09:34 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +    moras = moras.copy()
immutableぽくしたほうがいいか？と思ったのでなんとなくcopyしているが不要かも

2021-12-11 09:34 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +    mora = copy.copy(mora)
ここのcopyも不要かも

2021-12-11 09:34 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +    mora.pitch = min(before_mora.pitch + adjust_pitch, max_pitch)
vowel_length=長さ、pitch=イントネーションだと思って設定してますがあってますか？
また各調整値は適当に設定しているので調整する必要あり。

2021-12-11 09:34 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +        full_context_moras + [full_context_label.Mora(None, last_mora.vowel)]
伸ばし棒用の音素を付け足すということだったが、配布版を確認した感じだと伸ばし棒は直前の母音が追加される？ようなので同じ感じにしてみました

2021-12-11 09:39 UTC, qwerty2501 commented
CIでエラー出てるようなので修正します

2021-12-11 10:15 UTC, Hiroshiba commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +    mora.pitch = min(before_mora.pitch + adjust_pitch, max_pitch)
合ってます！

2021-12-11 10:58 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +    mora.pitch = min(before_mora.pitch + adjust_pitch, max_pitch)
設定値の調査とかってどうします？

2021-12-11 12:10 UTC, Hiroshiba commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +    mora.pitch = min(before_mora.pitch + adjust_pitch, max_pitch)
そうですね･･･　よく使われそうな疑問文を3~5用意して、いろんなパラメータで疑問文っぽくしてみて、良さそうなものを採用するというのはどうでしょう。
雑ですが、動画用途でよく使われそうな疑問文を考えてみました。

```
これはありますか？
どういう意味？
どういう意味かなー？
なにしてるの？
なにしてるのだ？
```

2021-12-11 12:13 UTC, Hiroshiba commented
> 単体テストコードはどこに書けばよいですか？

`test/test_synthesis_engine.py`辺りに書いて頂ければ！

ジャストアイデアですが、「ん」で終わる疑問文、「っ」で終わる疑問文でテストが通るか試しておくと良いかもと感じました。

2021-12-11 14:30 UTC, qwerty2501 commented
とりあえず1ケースだけ思いのままに書いて追加してみましたがこんな感じでいいですかね？
`ん？` や `っ？` あと `す？` も追加する予定です

2021-12-11 16:34 UTC, qwerty2501 commented on voicevox_engine/model.py
> +    is_interrogative: bool = Field(title="疑問の発音を表現するモーラかの判定")
フロントと組み合わせて動かしてみたところ、synthesis時にdefault値がないためエラーになる模様。とりあえずdefaultをFalseに設定すれば動いたので設定したほうが良さそう

2021-12-11 16:37 UTC, qwerty2501 commented
ローカルにて `ん？` と `っ？` と `す？` それと `ふぇ？` を実際に発音させてみましたが、
`ん?` と `す？` と `ふぇ?` についてはぎこちなさは感じるもののまあ疑問系に聞こえなくもない感じでした
 `っ？` については直前がっのため疑問形には聞こえませんでした

2021-12-12 07:21 UTC, qwerty2501 reviewed
Draft外しました。気になるところにはすでに自分でコメント打ってますが、問題なさそうならResolveしちゃってください

2021-12-12 07:21 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +    mora.pitch = min(before_mora.pitch + adjust_pitch, max_pitch)
実際に出力してみましたが、ぎこちなさはあるものの疑問文に聞こえなくはないかなといった感じでした
何パターンか文章用意してパラメータをいじったりしてみたのですがどうも最初に設定した値が最適に感じる病気になってるような気がしてなりません。

2021-12-12 10:36 UTC, Hiroshiba commented
> 実際に出力してみましたが、ぎこちなさはあるものの疑問文に聞こえなくはないかなといった感じでした
何パターンか文章用意してパラメータをいじったりしてみたのですがどうも最初に設定した値が最適に感じる病気になってるような気がしてなりません。

色んなパターンを作ってみんなで聴き比べられると、納得の行く答えにたどり着けるかも・・・？

2021-12-12 11:28 UTC, aoirint commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +    moras = moras.copy()
その用途だと、copy.deepcopyの方がいいのかなと思いました

2021-12-12 12:38 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +    moras = moras.copy()
deepcopyのがimmutabilityを主張するのによりふさわしそうだったので直しました

2021-12-12 14:19 UTC, qwerty2501 commented
とりあえず3パターン分作ってみました
https://drive.google.com/drive/folders/1H77oxsevONEWZ81hqRFsWTFWHbpAfHpT?usp=sharing

2021-12-12 16:33 UTC, Hiroshiba commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +    mora.pitch = min(before_mora.pitch + adjust_pitch, max_pitch)
実際に聞いてみました、たしかに疑問文になっていると思います！！

結構疑問文ぽくならないこともありますね･･･

春日部つむぎ辺りは、むしろ語尾は伸ばしめにしても良いのかなと感じました。
min_vowel_length=0.15、adjust_vowel_length=0.0（調整しない）とかはどうでしょう。
やりだすとキリがなさそうなので、一旦それで比較して良さそうなのを選択が良いかなと感じました！

2021-12-12 16:49 UTC, Hiroshiba commented
機能実装に関してコードを眺めていて、課題が２つ思いついたので共有します。
こちらのプルリクで対応できそうであればして頂けると嬉しいですが、難しそうならissue化したいと思います。

- [ ] 疑問文で擬似的に自動調整する機能をON/OFFできるようにする
  - UI側から操作できると良さそう、APIの引数にON/OFFフラグをデフォルトONで持たせる？
- [ ] aquestalk記法（parse_kana関数）の疑問文対応
  - `?`を付けられるようにしたりする

2021-12-12 16:59 UTC, qwerty2501 commented
> 疑問文で擬似的に自動調整する機能をON/OFFできるようにする

これはこのPRでやったほうがよさそうですね

> aquestalk記法（parse_kana関数）の疑問文対応

全く新しいところの修正なのでissue分けたほうが良いと思います

2021-12-13 10:41 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +    mora.pitch = min(before_mora.pitch + adjust_pitch, max_pitch)
0.15に常に固定化するということですね。修正してみました。
正直私の耳だとどっちも同じに聞こえてしまいます。

いちおう0.15にしたもので出力したものが以下になります。
https://drive.google.com/drive/folders/1g0NQ5pjgEJg3uF143nRPbkBy0GVs_ziz?usp=sharing

2021-12-13 11:32 UTC, qwerty2501 commented
# Fixed
- audio_queryのパラメタに疑問系を有効化するものを追加
- vowel_length,pitch調整が疑問系以外にも有効になっていたので修正

2021-12-13 15:57 UTC, Hiroshiba commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +    mora.pitch = min(before_mora.pitch + adjust_pitch, max_pitch)
たしかにあまり変わってないかもです。
固定0.15で良いと感じました！！

2021-12-13 16:00 UTC, Hiroshiba commented on run.py
> +        )
API、良いと思います！
run.py内に`create_accent_phrases`がいくつかあって、それらのAPIにも`enable_interrogative: bool = True`をつけると一貫性があるかなと思います！

2021-12-13 16:01 UTC, Hiroshiba commented
> > aquestalk記法（parse_kana関数）の疑問文対応
> 全く新しいところの修正なのでissue分けたほうが良いと思います

良いと思います！！
issue化お願いできると助かります･･･！

2021-12-13 16:11 UTC, qwerty2501 commented on run.py
> +        )
とりあえずrun.pyにあるもので `create_accent_phrases` を呼び出してると思われるところにつけました

2021-12-13 16:16 UTC, qwerty2501 commented
#235 に作りました

2021-12-14 16:05 UTC, aoirint reviewed
実装は良さそうでした！
気になったところにコメントしてみました！

2021-12-14 17:34 UTC, Hiroshiba commented on voicevox_engine/model.py
> +    )  # frontが動作しなくなるためdefault値を設定するようにしている  # noqa
デフォルト値ありで良いと思います！
というのも今回の`is_interrogative`は、エディタ側からは設定画面やPOST処理だけに使用するので、オプショナルでもそこまで大変じゃなさそうなためです。

2021-12-14 17:42 UTC, Hiroshiba commented on run.py
> +    def audio_query(text: str, speaker: int, enable_interrogative: bool = True):
難しいところですが、今回はデフォルト値を変更する方（True）でいこうと考えています。
意味のない変更ではなく品質が上がる（はずな）変更なためです。
その代わりしっかりアナウンスはしないとですね。リリース手順書にメモしておこうと思います。

2021-12-14 18:31 UTC, takana-v reviewed
コードを読んだ限り、既にある指摘以外に問題点は無いと思います。
（個人的には、場合によってはAudioQuery内部の互換性は切っても構わないと思っています）

2021-12-15 00:31 UTC, qwerty2501 commented on test/test_synthesis_engine.py
> +    def create_accent_phrases_test_base(
そうですね。SynthesisEngineBaseに分けます。

2021-12-15 00:45 UTC, qwerty2501 commented on test/test_synthesis_engine.py
> +    def test_create_accent_phrases_これはありますか(self):
これは迷ったんですが、関数名がテストケース名になるようなのでわかりやすさを重視した感じですね
私個人はどちらでもよかったんですが、テスト観点のデータが日本語でコメント等も日本語で運用されており、ほぼ完全に日本語コミュニティなのでまあケース名も日本語にしておくかぐらいの気持ちでした。
このままにするにしてもコメントで上記理由ぐらいは書いておこうと思います

2021-12-15 00:52 UTC, qwerty2501 commented on voicevox_engine/model.py
> +    )  # frontが動作しなくなるためdefault値を設定するようにしている  # noqa
@aoirint 
> 影響するのは、フロントエンド側でis_interrogativeなモーラであることをUIに反映する場合でしょうか。

現状使用する予定はないので、使用する時に対応すればよいと思います。
default値を設定した理由としてはフロント側の負荷軽減が目的です。これを設定することにより、フロント側ではなにも修正しなくてよいはずです。
将来的には `is_interrogative` が trueだったら エディタ画面のMora表示のところに `?` を出すといったことはしても良いかもしれませんね。

2021-12-15 01:22 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +) -> List[Mora]:
その型はOpenJTalkに依存していたはずなので HTSMoraないしはOpenJTalkMoraあたりも候補になるかもしれません。
そもそも module名が `full_context_label` でいいのかとかそもそも `full_context_label.Mora` は必要なのか？とかもありますが、その時がきたら議論でいいと思います。

2021-12-15 01:26 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +def add_interrogative_mora_if_last_phoneme_is_interrogative(
> 個人的に、SynthesisEngineやSynthesisEngineBaseのモジュール直下に定義する関数は、1ファイルにいろんな目的の実装が混在してしまって読みにくくなると思うので、減らしたいと思っています。

これは同意ですが、場当たり的に分けても良い結果は生まないのと他にも切り出したいものがあるようなので専用のPRを作り全体を俯瞰して見て変更を行った方が良いと思います。なのでこのPRとしてはこのままかなと

2021-12-15 02:11 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +def adjust_interrogative_mora(mora: Mora, before_mora: Mora) -> Mora:
> メモ: Moraクラスに処理を置いてもいい気がしましたが、それも実装が集中しそう・他の実装と合わなくなってしまうので、変形する関数を定義する形（現状）でいいかなと感じました。

そうですね。疑問形にするのはSynthesisEngineの役割かなという気がしますし、直前のMoraに依存するのでこの関数をMoraに生やすのはちょっと違うかなという感じはしますね。

2021-12-15 02:13 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +        max_pitch = 6.5
↑コメントで残しておきますか？

2021-12-15 02:16 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +                    moras=full_context_label_moras_to_moras(
ここもそうですが、実際に機能実装してみて感じたことがあるのでどっかに書いておいた方がいいですかね。 #119?

2021-12-15 02:19 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +    ) -> List[AccentPhrase]:
OKです。グローバル関数に直します

2021-12-15 02:27 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +            else False,
```python
enable_interrogative
            if mora is full_context_moras[-1]
            else False
```
この部分ですね。囲っておきます

2021-12-15 02:45 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +    ) -> List[AccentPhrase]:
> 将来的に、 VOICEVOX/voicevox_project#5 の機械学習的アプローチが組み込まれた場合を想定しているのかなと思ったのですが

これ機械学習でやるべきことじゃね？とは感じてたんですが、一応目標としてはあるんですね。
ちょっと思ったんですが、仮に機械学習でできるようになったとしてパラメタによる有効無効の切り替えってできるんですかね

2021-12-15 03:27 UTC, Hiroshiba commented on voicevox_engine/model.py
> +    )  # frontが動作しなくなるためdefault値を設定するようにしている  # noqa
あ、ほんとだ、たしかに現状使用予定が無いですね…
そして将来的に使うかも微妙かもです。
APIは消去より追加のがだいぶ簡単なので、いったん無しにした方が良いかなと感じました！

2021-12-15 03:30 UTC, Hiroshiba commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +    ) -> List[AccentPhrase]:
手間はかかるかもですが、疑問文有無のパラメタで切り替えできるようになると思います。
まあ仮にできなくてもAPIどうするかはその時考えるで良いかなと思います！

2021-12-15 04:24 UTC, qwerty2501 commented on voicevox_engine/model.py
> +    )  # frontが動作しなくなるためdefault値を設定するようにしている  # noqa
> APIは消去より追加のがだいぶ簡単なので、いったん無しにした方が良いかなと感じました！

ちょっと気になったのですが、ここのフィールド宣言を消してしまうと内部処理で使えなくなるのではないですか？
Pythonは動的型付け言語だからいけるんですかね。

2021-12-15 05:56 UTC, Hiroshiba requested changes

2021-12-15 05:56 UTC, Hiroshiba commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +        max_pitch = 6.5
まあ、変更したくなったときに変更で良いかなと感じました。（今の所変更したい人でおらず、かつここでしか使わない値なので）

2021-12-15 05:56 UTC, Hiroshiba commented on voicevox_engine/model.py
> +    )  # frontが動作しなくなるためdefault値を設定するようにしている  # noqa
無しにしたほうが良いというのは、宣言を消し、代入もしないという意図でした。

> ここのフィールド宣言を消してしまうと内部処理で使えなくなるのではないですか？

今`adjust_interrogative_mora`は全てのmoras（accent phrase？）で呼ばれていて、内部でis_interrogativeを見ている関係で、内部処理に使われているんだと思います。
これを疑問文のところにだけ`adjust_interrogative_mora`を呼ぶようにするというのはどうでしょう。

2021-12-15 05:56 UTC, Hiroshiba commented on test/test_synthesis_engine.py
> +    def test_create_accent_phrases_これはありますか(self):
テストはそのコードが意図通りに上手く行っているかを検査するのが目的だと思うので、そのコードの意図を正確に伝えられるのであれば日本語を使うのもありかなと感じました。
ただこの場合は、テストの意図（「create_accent_phrasesをテストしたい」という意図）の情報量が増えないので、そもそも例文（「これはありますか」）を含めなくても良い気がしました。

2021-12-15 05:56 UTC, Hiroshiba commented on voicevox_engine/full_context_label.py
> +
議論していて気づいたのですが、OpenJTalkは疑問文かどうかをphoneme単位ではなくaccent phrase単位で処理しているようなので、PhonemeクラスではなくAccentPhraseクラスに情報を持たせるのが良いのかなと感じました。
（情報の範囲がわかりやすくなって、処理がきれいになりそうだなと感じています）

2021-12-15 07:12 UTC, qwerty2501 commented on voicevox_engine/model.py
> +    )  # frontが動作しなくなるためdefault値を設定するようにしている  # noqa
話がかみ合ってない感じがするのでどんな感じの実装イメージかわかるコード片もらえますか？雑なものでよいので

2021-12-15 08:01 UTC, Hiroshiba commented on voicevox_engine/model.py
> +    )  # frontが動作しなくなるためdefault値を設定するようにしている  # noqa
こんな感じです。
```python
new_accent_phrases = []
for accent_phrase in accent_phrases:
  if accent_phrase.is_interrogative:
    accent_phrase = adjust_interrogative(accent_phrase)
  new_accent_phrases.append(accent_phrase)
```

2021-12-15 08:39 UTC, qwerty2501 commented on voicevox_engine/full_context_label.py
> +
そうですね。実装してて AccentPhrase単位でつけられてそうな節はあったのですが、どうも確証がもてなかったのでphonemeそのままで判定してる感じですね。

決め打ちでAccentPhraseに持たせて良いかもしれませんが、 https://github.com/VOICEVOX/voicevox_engine/pull/229#discussion_r769313322 をさきに終わらせてからのほうが良さそうです。

2021-12-15 08:40 UTC, aoirint commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +def add_interrogative_mora_if_last_phoneme_is_interrogative(
いいと思います！

2021-12-15 09:03 UTC, qwerty2501 commented on voicevox_engine/model.py
> +    )  # frontが動作しなくなるためdefault値を設定するようにしている  # noqa
そのコードだと、`accent_phrase` に `is_interrogative` を持っていることを期待しているようですが、 `adjust_interrogative` は SynthesizeEngineによるmora data適用後の情報である必要があるためここの `accent_phrase`  は `model.py` にある `AccentPhrase` である必要があると思います。　

つまり、この実装を行ってもAPI定義の変更が必要になるかと。

以下のコメントから余計なAPI定義の変更は行わないという文脈だと思ってたので、この実装を行っても根本的な問題解決にはならないのではないかと考えていたんですが違ってましたか？

> あ、ほんとだ、たしかに現状使用予定が無いですね…
そして将来的に使うかも微妙かもです。
APIは消去より追加のがだいぶ簡単なので、いったん無しにした方が良いかなと感じました！

2021-12-15 09:50 UTC, qwerty2501 commented on test/test_synthesis_engine.py
> +    def test_create_accent_phrases_これはありますか(self):
IMO: それは一つのテスト関数で複数のデータケースを確認してしまうという意味だと思いますが、pytestだと関数名=ケース名となってるようなので、テストでエラーになったときにどのケースでエラーが起きたかわかるようにする必要があると思いました。また、実行確認の際にもpytestだと個別で実行するには関数単位でしか分けられない？ようなのでこのテストケースだけ確認したいというときにちょっと困ったことになりそうです。もし上手くやれる方法があるなら教えていただけますでしょうか？

以上を踏まえて、 `test_create_accent_phrases`　にテスト関数名を変更しますか？

2021-12-15 10:51 UTC, Hiroshiba commented on voicevox_engine/model.py
> +    )  # frontが動作しなくなるためdefault値を設定するようにしている  # noqa
すみません、ちょっと意図をコードに落とし込めていませんでした･･･
`is_interrogative`を`AccentPhrase`modelに持たせるのではなく、何らかの方法で別でis_interrogativeを持っておくという感じです。
こんな感じになりそうです。

```bash
new_accent_phrases = []
for accent_phrase, is_interrogative in zip(accent_phrases, is_interrogative_list):
  if is_interrogative:
    accent_phrase = adjust_interrogative(accent_phrase)
  new_accent_phrases.append(accent_phrase)
```

2021-12-15 11:02 UTC, Hiroshiba commented on test/test_synthesis_engine.py
> +    def test_create_accent_phrases_これはありますか(self):
たしかにログに出ないとわかりにくいかもです。
pytestのfixtureとparametrizeを使うと、入力データをログに出すことができるので、これを用いるのが最高かもです。
https://dev.classmethod.jp/articles/pytest-parametrize-fixture/
（pytestのparametrizeは結構癖があるので、正直なかなかしんどいと思います･･･）

実行が重いテストは個別に実行したくなりそうですが、このテストは軽いのでまとめて実行しても良いかなと感じました。

> 以上を踏まえて、 test_create_accent_phrases　にテスト関数名を変更しますか？

誰も強い意見を持っていない状態だと思うので、一旦どちらでも良いかなと感じました。
確認したところ、他のテストはデータ例をテスト名に含めていなそうので、とりあえず合わせるために消す、というのはどうでしょう。

2021-12-15 11:10 UTC, qwerty2501 commented on voicevox_engine/model.py
> +    )  # frontが動作しなくなるためdefault値を設定するようにしている  # noqa
それだとSynthesisEngineBaseのコードが複雑化しそうですが、そのへんは許容していただけるということでいいですかね

2021-12-15 11:27 UTC, y-chan commented on test/test_synthesis_engine.py
> +    def test_create_accent_phrases_これはありますか(self):
私はテストを汎用的にする(特定の関数などに対するテストを全てひとつのテスト関数に集約する)ことを念頭に今までテストの実装をしていたので、どちらかと言うと関数名に`これはありますか`を入れるのは消極的です。

合わせるという意味もありますが、テストをより汎用的にするという意味でも`test_create_accent_phrases`でとどめておくと、後々のためにも良いのかなと思いました。

どちらにせよ、テストが落ちた時にはどこで落ちたか(どの行を実行中に失敗したか)を見るので、個人的には具体的なテストケース名を入れなくて良いかなと思っているのもひとつあります。

2021-12-15 14:19 UTC, qwerty2501 commented on test/test_synthesis_engine.py
> +    def test_create_accent_phrases_これはありますか(self):
@Hiroshiba @y-chan はい。一旦合わせる感じでまとめちゃいますね。

2021-12-15 16:20 UTC, qwerty2501 commented on voicevox_engine/full_context_label.py
> +
AccentPhraseに `is_interrogative` をもたせました

2021-12-15 16:20 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +    ) -> List[AccentPhrase]:
@aoirint グローバル関数に変更しました

2021-12-15 16:21 UTC, qwerty2501 commented on test/test_synthesis_engine.py
> +    def create_accent_phrases_test_base(
test_synthesis_engine_base.pyを作ってそこに移動させました

2021-12-15 16:27 UTC, qwerty2501 commented on test/test_synthesis_engine.py
> +    def test_create_accent_phrases_これはありますか(self):
既存と同じ感じにしてみました。assertEqualでメッセージ出せるようだったのでそこに申し訳程度にどのケースだったかわかるようにメッセージを出すようにしてます。
@Hiroshiba  parametrizeを使うことも検討しましたが、expectedであるAccentPhraseの出力がカオスになりそうな気がしたので一旦見送りました。まあこの手のケース取り扱うライブラリはないかしら癖があるので挙動確認してみて使い物になりそうだったら導入を検討してみてもいいかもしれませんね。

2021-12-15 16:31 UTC, qwerty2501 commented on voicevox_engine/model.py
> +    )  # frontが動作しなくなるためdefault値を設定するようにしている  # noqa
@Hiroshiba サンプルとは違いbool値のlistではなくfull_context_labelのAccentPhraseのListで実装してみました。特段boolのみする必要がなくこっちのほうが楽だったため

2021-12-15 16:32 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +            else False,
最終的にMoraにたいしてis_interrogativeを持たせないことになったのでここの実装は削除になりました

2021-12-15 16:40 UTC, qwerty2501 commented on voicevox_engine/full_context_label.py
> +            is_interrogative=accent_phrase.is_interrogative,
@Hiroshiba AccentPhraseにis_interrogativeをもたせるとmergeの際にどっちのis_interrogativeを優先させるかで問題になりました。とりあえず後ろにくるaccent_phraseのis_interrogativeを反映させるようにしてるのですが、問題があったら指摘お願いします

2021-12-15 16:40 UTC, qwerty2501 commented
@Hiroshiba @y-chan @aoirint 指摘もらった部分についてですが修正し終えたと思います。
量が多かったので見落としがあるかもしれないのでその際は再度指摘お願いします。

2021-12-15 16:48 UTC, y-chan commented
今更ながらの指摘で申し訳ないのですが、テストに用いる変数定義が大きくなってしまうことに関して、以下のように最初に1つベースを作り、それを随時書き換えてテスト用関数に投げるといった方式によって、一回一回の定義量が少なくできると思います。
https://github.com/VOICEVOX/voicevox_engine/blob/a451258c937113e4d244a643cbaea9d86b1fdcc1/test/test_synthesis_engine.py#L590-L640

こちらを少し試してみてもらえないでしょうか...?

2021-12-15 17:30 UTC, qwerty2501 commented
@y-chan 書き直すこと自体は問題はないのですが、その書き方だと以下の問題点があるのでやめたほうが良いと感じました。

- テストデータが前のケースのデータに依存してしまうので間にケースを新しく追加してしまうと後続のテストケースに影響がでる
    - メンテナーが変わるとこのことに気づきにくい

- テストデータに問題があって修正したときに後続のテストケースに影響を与えてしまう
    - これもメンテナーが変わると気づきにくい 

- テストエラーが出て該当のケースを見に行ったときにそのケースで何のテストデータが設定されているかひと目でわかりにくい
    - やはりこれもメンテナーが変わると戸惑ってしまう

そちらの方針ということであれば直しますがIMOとしてはこんな感じですね

2021-12-16 03:59 UTC, Hiroshiba commented on voicevox_engine/full_context_label.py
> +
音素に`is_interrogative`（疑問文である）フラグがあるのは混乱に繋がりそうなので消しちゃっても良いかもです。
AccentPhraseで`is_interrogative = moras[-1].vowel.is_interrogative()`としているところで直接`moras[-1].vowel.contexts["f3"] == "1"`しちゃうとか。

2021-12-16 04:01 UTC, Hiroshiba commented on voicevox_engine/full_context_label.py
> +            is_interrogative=accent_phrase.is_interrogative,
おお、たしかに！！　そちらの処理が良いかなと感じました！

2021-12-16 04:14 UTC, Hiroshiba commented
@y-chan さんと @qwerty2501 さんのテストケースですが、ベースを作って変更箇所を代入する方法だと、疑問文にする前と後でどこが差分になっているか（テストの意図）がわかりやすいという利点もある気がしました。

> テストデータが前のケースのデータに依存してしまうので間にケースを新しく追加してしまうと後続のテストケースに影響がでる
> テストデータに問題があって修正したときに後続のテストケースに影響を与えてしまう

テストケースが変わるのは厄介なのはそのとおりなので、deepcopyしたほうが安心だと思います。

> テストエラーが出て該当のケースを見に行ったときにそのケースで何のテストデータが設定されているかひと目でわかりにくい

`diffがわかる vs 定義がわかる`の構造なので一長一短かなぁと思いました。定義とdiffを近くに書けると最高かもです。

総合的に見ると、文量が減るので @y-chan さんの案が良いのかなと思いました。

2021-12-16 04:39 UTC, qwerty2501 commented
> テストケースが変わるのは厄介なのはそのとおりなので、deepcopyしたほうが安心だと思います。

deepcopyだとテストケース作る人間が忘れずに明示的にする必要があるので、local関数でベースとなるデータを生成するようにしたほうがいいかもしれません
こんな感じです

```python
def test_create_accent_phrases(self)
    def koreha_arimasuka_base_expected():
         return  [AccentPhrase(...),...]

    expected=koreha_arimasuka_base_expected()
    expected.  # ここで各ケースごとの変更を行う
    self.create_accent_phrases_test_base(
         text="これはありますか？".
         expected=expected,
         enable_interrogative=True,
    )
```

2021-12-16 10:36 UTC, qwerty2501 commented on voicevox_engine/full_context_label.py
> +
Moraから削除しました

2021-12-16 10:37 UTC, qwerty2501 commented
@Hiroshiba @y-chan test_create_accent_phrasesをコメントで書いた感じに書き直してみました

2021-12-16 16:51 UTC, Hiroshiba commented
個人的に気になったところと、API・modelの構成は問題なさそうに感じました！
そこに変更が加わりそうだったらまた聞いて頂けると･･･！

2021-12-18 05:29 UTC, aoirint requested changes
消し忘れていそうなところがあったので、確認のためのRequest changesですが、良さそうでした！

修正ありがとうございます！

2021-12-18 05:29 UTC, aoirint commented on test/test_synthesis_engine_base.py
> +        )
`voicevox_engine.dev.synthesis_engine.MockSynthesisEngine`を使うと、`*_mock`関数の定義をしなくて済むように思いましたが、意図して`SynthesisEngine`を使っている感じですか？ 👀（`SynthesisEngine`の実装に明るくないので、違いがよくわかっていないです）

2021-12-18 05:58 UTC, qwerty2501 commented on test/test_synthesis_engine_base.py
> +        )
そこにMockがあったんですね。
それなら使う感じにしちゃいますか

2021-12-18 06:23 UTC, qwerty2501 commented on test/test_synthesis_engine_base.py
> +        )
MockSynthesisEngineを使用するように変更しました。
MockSynthesisEngineだとreplace系がそのまま返される実装なのでちょっとどうなのだろうなと思いました。
test_create_accent_phrasesでは観点となっているところは見れてますが、いずれはちゃんとしたMockライブラリを使用して、Returnする内容を変えられるようにしたほうが良いと思いました。

2021-12-18 08:43 UTC, aoirint commented on test/test_synthesis_engine_base.py
> +        )
ありがとうございます！

MockSynthesisEngineの実装は、#78 で製品版コアライブラリが未公開で、情報も少なかった時期にENGINEの開発ができるようにするための、仮の実装をしたものがそのまま残っている形だったと思います。

> MockSynthesisEngineだとreplace系がそのまま返される実装

知識がなかったので、音声合成周りについて調べながら、ちょっと実装を見てみました。

MockSynthesisEngineには、`synthesis`時に元のテキスト情報しか使っていないという課題もありそうです。
実装が膨らむかもですが、`List[AccentPhrase]`をフルコンテキストラベルに書き戻してからHTSEngine（`pyopenjtalk.synthesize`）に入れるようにしてもいいのかもしれません。

それから、OpenJTalkの解析結果（フルコンテキストラベル）には音素の高さと長さの情報（音素アライメント情報？）がなさそうなので、replace系の実装は難しそうでした。

また`synthesis`時に`pyopenjtalk.synthesize`を使うようにしても、音素の高さと長さの情報はMockの音声合成に使えなさそうに思いました。

このあたりは、今後のリファクタリングの参考になりそうでした（SynthesisEngineの構成を見直してもいいかもと感じました）。

> Returnする内容を変えられるように

同意です。

`SynthesisEngine`のように、`SynthesisEngineBase`の未実装部分をコンストラクタなどで注入できるようにしてもいいのかなと思いました（新しいクラスとして作るか、いまのBaseを置き換えるか）。

一応、テストコード側で継承したクラスを定義する形もとれそうだということに気づきましたが、個人的には、いったんMockSynthesisEngineでいいかなと思いました。

2021-12-18 08:49 UTC, aoirint approved these changes
LGTM！

2021-12-18 14:03 UTC, qwerty2501 commented
Moraからis_interrogative削除した影響で、使っていない引数が発生したので消しました

https://github.com/VOICEVOX/voicevox_engine/pull/229/commits/eb1803d3fb5a69361ce2de01afe29c869096178f

2021-12-19 03:40 UTC, Hiroshiba requested changes
良さそうです！！

良い実装だと思うのですが、さすがに少し案内がないと目的や何が起こるかがわからないかもと感じました。
最後にドキュメントを少しだけ書いて頂けると助かります！！

2021-12-19 03:40 UTC, Hiroshiba commented on run.py
> +    def audio_query(text: str, speaker: int, enable_interrogative: bool = True):
FastAPIで、もし引数の説明ドキュメントを書く方法があれば、どういうことをするものなのか一言説明があるとみんな安心して活用できそうだと感じました。

2021-12-19 03:40 UTC, Hiroshiba commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +def adjust_interrogative_accent_phrases(
「最後に伸ばし棒音素を足して、足した音の高さを高くすることで疑問文っぽくする」という意図をコードから読み取るのはなかなか難解かもしれません。
この辺りの関数に、目的や何をしているかの一言二言ドキュメントがあると嬉しいかもと感じました。

2021-12-19 05:28 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +def adjust_interrogative_accent_phrases(
たしかにそうですね。こことadd_interrogative_mora_if_last_phoneme_is_interrogativeにも追加しておきました

2021-12-19 05:29 UTC, qwerty2501 commented on run.py
> +    def audio_query(text: str, speaker: int, enable_interrogative: bool = True):
Queryクラスにdescription追加すればできるようなので追加しました

2021-12-19 09:29 UTC, takana-v approved these changes
LGTM！
変更が完了したら、コメントかレビューの再リクエストを頂けると助かります。
（右サイドバーのReviewersのところからできます）

2021-12-19 09:50 UTC, Hiroshiba approved these changes
LGTM！！！！
長く熱い議論本当にありがとうございました！！

エディタ側にこちらのプルリクに対応するissueを作ってみました。

- https://github.com/VOICEVOX/voicevox/issues/608

もしよかったらこちらの機能の実装にチャレンジするというのはどうでしょう👀

またのプルリクエスト、ぜひお待ちしています！！

2021-12-19 09:50 UTC, merged

2021-12-19 10:35 UTC, qwerty2501 commented
お疲れ様でした。
Conversation100超えたときはなかなか感慨深かったです(笑)
フロントはかなり苦手なのですがやるだけやってみます