ユーザ辞書を有効化
VOICEVOX/voicevox_engine pull request #234
Opened 2021-12-13 13:09 UTC by takana-v

## 内容
pyopenjtalk (mecab)のユーザー辞書機能を有効化します。
pyopenjtalk側のPRを先に通す必要があるためdraftです。

## 関連 Issue
- https://github.com/VOICEVOX/voicevox/issues/175
- ~~https://github.com/Hiroshiba/pyopenjtalk/pull/1~~
- https://github.com/VOICEVOX/pyopenjtalk/pull/3

https://github.com/VOICEVOX/voicevox/issues/175#issuecomment-926765847 のPh.1にあたるPRです。

## その他
~~依存関係の更新はpyopenjtalk側のPRが通り次第行います。~~ 反映しました
辞書は、ユーザーが使いそうで誤読するものを入れておきました。
コストを自動推定にすると上手く読まれない場合があったので、一部では値を0にしています。

2021-12-13 13:10 UTC, takana-v commented on .github/workflows/build.yml
>              --include-data-file="licenses.json=./"
PRの本題とは関係ないですが、`presets.yaml`がここだけ無いのが気になりました。

2021-12-16 18:34 UTC, Hiroshiba commented on user-dic.csv
> +ｖｏｉｃｅｖｏｘ,1288,1288,0,名詞,固有名詞,一般,*,*,*,*,ボイスボックス,ボイスボックス,4/7,C1
すごく良いですね！！！

VOICEVOXのキャラクター名も増やせると楽しそうだなと感じました。
どのイントネーションが正しいかは聞いてみようと思います。

2021-12-17 06:41 UTC, amamama commented on user-dic.csv
> +ｖｏｉｃｅｖｏｘ,1288,1288,0,名詞,固有名詞,一般,*,*,*,*,ボイスボックス,ボイスボックス,4/7,C1
横から失礼します．
mecabの辞書の2要素目，3要素目は [通常システム 辞書と同一場所にある left-id.def/right-id.def と同一でなければなりません](https://taku910.github.io/mecab/dic.html)が，このID，1288〜1291は[openjtalkのシステム辞書](https://github.com/r9y9/open_jtalk/blob/957229334996d2c9d9fcb73cdb3f4d9c15bcdd57/src/mecab-naist-jdic/_left-id.def)と異なっています．正しくは1348〜1351です．

2021-12-17 06:46 UTC, amamama commented
横から失礼します（githubのissue）．
mecabの辞書の2要素目，3要素目は 通常システム 辞書と同一場所にある left-id.def/right-id.def と同一でなければなりませんが，このID，1288〜1291はopenjtalkのシステム辞書と異なっています．正しくは1348〜1351です．

2021-12-17 16:15 UTC, takana-v commented
ご指摘ありがとうございます。修正しておきました。
（mecabでコストの自動推定をした時に誤った文脈IDになったみたいです）

2022-01-01 10:52 UTC, takana-v reviewed
とりあえず編集中に気になった分をコメントしています。
キャラクターの読みの追加はTALQu等を含めるとキリがないのでどこかで線引きが必要かもしれません。

2022-01-01 10:52 UTC, takana-v commented on user-dic.csv
> +はう,1351,1351,5000,名詞,固有名詞,人名,名,*,*,*,ハウ,ハウ,1/2,C1
十分なテストはできていませんが、おおむね「はう」を含む文でも誤読しない感じです。
（「私はうれしい」「このご飯はうまい」など）

2022-01-01 10:52 UTC, takana-v commented on user-dic.csv
> +ずんだもん,1351,1351,0,名詞,固有名詞,人名,名,*,*,*,ズンダモン,ズンダモン,1/5,C1
発音が正しいか怪しいです。
とりあえず現状に合わせています。

2022-01-01 10:52 UTC, takana-v commented on user-dic.csv
> +雨晴,1350,1350,7000,名詞,固有名詞,人名,姓,*,*,*,アメハレ,アメハレ,2/4,C1
他に「あまはらし」「あまはら」「あまはれ」等の読み方がありますが「あめはれ」を優先しています。

2022-01-01 11:43 UTC, Yosshi999 requested changes

2022-01-01 11:43 UTC, Yosshi999 commented on .github/workflows/build.yml
> +            --include-data-file=../user.dic=./ \
[SHOULD] このオプションによって配布物(Releases)にuser.dicが入ると思いますが、csvの方も入れたほうが良いと思います。利用者がREADMEに従ってユーザー単語を追加しようとした場合、プリセットのユーザー辞書に追記する形で作りたくなるのではないかと思います。

2022-01-01 13:58 UTC, takana-v commented on .github/workflows/build.yml
> +            --include-data-file=../user.dic=./ \
現時点ではバイナリ化した状態では辞書のコンパイルが出来ないので不要かなと思っています。
OpenJTalkのユーザー辞書を使う方針が固まったら、ユーザー側で単語を追加出来るようにcsvも同梱したいと考えています。

2022-01-01 14:31 UTC, Yosshi999 commented on .github/workflows/build.yml
> +            --include-data-file=../user.dic=./ \
なるほど、ではこのchange requestは取り下げます

2022-01-01 14:32 UTC, Yosshi999 approved these changes
LGTM!

2022-01-01 16:20 UTC, Hiroshiba commented
> キャラクターの読みの追加はTALQu等を含めるとキリがないのでどこかで線引きが必要かもしれません。

VOICEVOXキャラやVOICEVOX用語だけが必ず含まれるようにして、その他の用語はimportできるようにするとかが丸いかなと感じました。

2022-01-01 16:26 UTC, Hiroshiba approved these changes
LGTM！！

「ずんだもん」「四国めたん」のイントネーションは聞いてみたいと思います。（違っていたら修正PRかissueを作成する予定です）

１箇所だけ気になったのでコメントしてみました、問題無さそうor修正したらマージでしていただいても大丈夫そうです！

2022-01-01 16:26 UTC, Hiroshiba commented on user-dic.csv
> +はう,1351,1351,5000,名詞,固有名詞,人名,名,*,*,*,ハウ,ハウ,1/2,C1
波音リツの「リツ」が無さそうですが、こちらはデフォルトで入っていそうでしょうか👀

2022-01-02 02:46 UTC, takana-v commented on user-dic.csv
> +はう,1351,1351,5000,名詞,固有名詞,人名,名,*,*,*,ハウ,ハウ,1/2,C1
明示的に指定しなくても問題なく読んでくれますが、念のため追加しておきました。

2022-01-02 02:49 UTC, takana-v commented
修正が完了したのでマージします。

2022-01-02 02:49 UTC, merged

2022-01-09 17:47 UTC, Hiroshiba commented
あとから見てわかるようにするためのメモです。

> 「ずんだもん」「四国めたん」のイントネーションは聞いてみたいと思います。（違っていたら修正PRかissueを作成する予定です）

こちら伺ってみたところ、PRに含まれている設定で問題なさそうでした！