accent_phrases APIのparse_kanaについて疑問文自動調整対応をした
VOICEVOX/voicevox_engine pull request #244
Opened 2021-12-22 16:43 UTC by qwerty2501

## 内容

タイトル通りでparse_kanaで提供されてるaquestalk記法での疑問文対応を行いました。

## 関連 Issue
refs #235

## その他
とりあえずやってみたのですが、実装がどうもいびつになってしまい先にリファクタリングをしてからこれの実装をしたほうが良かったかもしれません
テストデータの共通化などもするべきですが、そもそもmergeされるか不透明なので一旦このままPR出します。
なお疑問文対応ですがaquestalkの仕様に基づき文の終わりのみに？(全角)がつけられてる場合に限り疑問文調整がされるようにしてます
https://www.a-quest.com/archive/manual/siyo_onseikigou.pdf

2021-12-23 01:11 UTC, y-chan reviewed
気になる点を軽くコメントしてみました。
軽く見た感じだと大きな問題はなさそうでした。

2021-12-23 02:05 UTC, qwerty2501 commented on test/test_kana_parser.py
> +        self.assertEqual(len(parse_kana("ギェ'、ギェ'/ギェ'", False)[0]), 3)
確かにそうですね。
ただ関数名についてはpythonでは_をつけると気持ちprivateな関数という風潮らしいので_parse_kanaではなくparse_kana_with_interrogativeみたいな感じの関数名にしようと思います。run.pyから参照したいのはこっちの関数なので

2021-12-23 02:14 UTC, qwerty2501 commented on voicevox_engine/kana_parser.py
> +    text: str, enable_interrogative: bool
機能としては run.pyからのみ使われているようだったのとrun.pyで呼ばれる際にかならずenable_interrogativeを渡される使い方になるのでデフォルト値は不要かなとの判断でした。

2021-12-23 02:24 UTC, qwerty2501 commented on test/test_kana_parser.py
> +        self.assertEqual(len(parse_kana("ギェ'、ギェ'/ギェ'", False)[0]), 3)
ちょっと考えたんですが、importを変えてこのファイルでは以下のような関数を定義すれば差分をかなり小さく抑えられそうなのでこっちでできたらやってみます。
```python
def parse_kana(text:str)->List[AccentPhrase]:
    accent_phrases,_ = kana_parser.parse_kana(text,False)
    return accent_phrases
```

2021-12-23 16:19 UTC, qwerty2501 commented on test/test_kana_parser.py
> +        self.assertEqual(len(parse_kana("ギェ'、ギェ'/ギェ'", False)[0]), 3)
修正してみました

2021-12-23 16:23 UTC, qwerty2501 commented
## Fixed

accent_phrases観点のテストがなかったので追加しました

2021-12-27 16:19 UTC, takana-v requested changes
レビューが遅れてしまい申し訳ありません...
コメントした箇所以外は問題ないかなと思います。

2021-12-27 16:19 UTC, takana-v commented on voicevox_engine/kana_parser.py
> +        text = text[:-1]
普通はないことかと思いますが、空文字列が渡されると例外が発生してInternal Server Errorになります。
(以下のような場合)
`"127.0.0.1:50021/accent_phrases?text=&speaker=2&enable_interrogative=true&is_kana=true"`
500が返るのはあまりよろしくないのでこちらのエラーを返す方がよさそうです。
https://github.com/VOICEVOX/voicevox_engine/blob/eac0e189560dd4963d21c6e9bdfbe7efcc9d68aa/voicevox_engine/model.py#L73

2021-12-27 16:56 UTC, qwerty2501 commented on voicevox_engine/kana_parser.py
> +        text = text[:-1]
ParseKanaErrorでEMPTY_PHRASEが飛ぶようにしてみました

2021-12-27 17:10 UTC, takana-v approved these changes
LGTM！

2021-12-28 00:01 UTC, aoirint approved these changes
よさそうでした！ LGTM！(AquesTalk記法よくわかっていませんが..;）

2021-12-28 00:01 UTC, merged

2021-12-28 07:48 UTC, Hiroshiba commented
あ、READMEにこのことを記載してもいいかなと思いました！
https://github.com/VOICEVOX/voicevox_engine/tree/86e06dc13d634562e92f799c5e75f06da23822cd#%E8%AA%AD%E3%81%BF%E6%96%B9%E3%82%92-aquestalk-%E8%A8%98%E6%B3%95%E3%81%A7%E5%8F%96%E5%BE%97%E4%BF%AE%E6%AD%A3%E3%81%99%E3%82%8B%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%82%B3%E3%83%BC%E3%83%89

> アクセント句は/または、で区切る。、で区切った場合に限り無音区間が挿入される。

↑これを「アクセント句は`/`または`、`で区切る。`、`で区切った場合に限り無音区間が挿入される。`？`で区切った場合は疑問形になる。」とかでしょうか👀

2021-12-28 07:57 UTC, qwerty2501 commented
あ、README PR作っときますね。

> ↑これを「アクセント句は/または、で区切る。、で区切った場合に限り無音区間が挿入される。？で区切った場合は疑問形になる。」とかでしょうか👀

aquestalkの仕様上、？が認められているのは文の終わりのみなので？で区切ることはできないです。実装もあくまで文の最後に？があるかどうかの判定のみしか行ってませんし、とちゅうで？があった場合はエラーになるようにしてます

2021-12-28 08:53 UTC, Hiroshiba commented
PRありがとうございます！！

あ、文末でしたか！把握し違いでした、了解です！