coreのctypes実装を追加＆古いコアを利用できるようにする
VOICEVOX/voicevox_engine pull request #254
Opened 2021-12-29 13:31 UTC by takana-v

## 内容

[ctypes](https://docs.python.org/ja/3/library/ctypes.html)モジュールを利用してコアを読み込むモジュールを追加します。
また、このモジュールを利用して古いコアを利用できる機能を追加します。

## 関連 Issue
- https://github.com/VOICEVOX/voicevox_project/issues/3

## その他
Dockerやビルド周りに調整が必要そうなのでDraftです。

2021-12-30 02:21 UTC, takana-v commented
- #249
- #251
とコンフリクトしそうなのでマージされるまで待機します。

2022-01-05 15:23 UTC, takana-v commented
現時点での動作確認
https://github.com/takana-v/voicevox_engine/releases/tag/ctypes-test

`--old_voicelib_dir`で過去コアのフォルダ、`--old_model_lib_dir`でlibtorchもしくはonnxruntimeのフォルダ、
`--old_model_type`でどちらの種類のコアか `libtorch` or `onnxruntime`(default)
以上の引数を設定することで過去コアを動かすことが可能
/docsとかから動作確認できます（過去コアは`use_old_core=true`で使用できます）

- [x] Windows CPU
- [x] Windows GPU
- [x] Linux CPU
- [ ] Linux GPU
- [ ] Mac CPU
- [x] Docker CPU
- [ ] Docker GPU

2022-01-08 09:04 UTC, takana-v commented
linuxのGPU版で過去コアを指定するとセグフォしたので一旦ドラフトにして原因を調査したいと思います。
```bash
~/tmp/linux-nvidia$ ./run --use_gpu --old_voicelib_dir=/home/takana/tmp/core
Segmentation fault
```

2022-01-08 09:27 UTC, takana-v commented
colabでGPU版の動作を試してみました。
`--old_voicelib_dir`を設定した場合でも問題なく動作したので恐らくセグフォはWSL2に固有の問題かと思います。
（Macは持ってないのでどなたかテストしていただけるとありがたいです）

2022-01-09 09:29 UTC, aoirint commented
macOS Big Sur 11.6.1で https://github.com/VOICEVOX/voicevox_engine/pull/254#issuecomment-1007922271 を試してみました。

ONNX版コア0.10.preview.0は、音声合成まで動作しました。

LibTorch版コア[0.7.4](https://github.com/VOICEVOX/voicevox_core/releases/tag/0.7.4)は、起動時に共有ライブラリの読み込みエラーになりました。依存ツリーと読み込み順が関係していそうなので、順序を変えるのを試したいですね...。

`libtorch.dylib`が`libtorch_cpu.dylib`に依存しているので、`libtorch_cpu.dylib`を`libtorch.dylib`より先に読み込む必要がありそうだと思いました。

```
$ ./run --old_voicelib_dir=../core --old_model_type=libtorch --old_model_lib_dir=/path/to/libtorch/lib
Traceback (most recent call last):
  File "/path/to/macos-x64/./voicevox_engine/synthesis_engine/make_synthesis_engine.py", line 51, in make_synthesis_engine
  File "/path/to/macos-x64/./voicevox_engine/synthesis_engine/core_wrapper.py", line 56, in __init__
  File "/path/to/macos-x64/./voicevox_engine/synthesis_engine/core_wrapper.py", line 45, in load_model_lib
  File "/path/to/macos-x64/./ctypes/__init__.py", line 373, in __init__
OSError: dlopen(/path/to/libtorch/lib/libtorch.dylib, 6): Library not loaded: @rpath/libtorch_cpu.dylib
  Referenced from: /path/to/libtorch/lib/libtorch.dylib
  Reason: image not found
Notice: Failed to make synthesis engine. This error will be ignored.
Traceback (most recent call last):
  File "/path/to/macos-x64/./run.py", line 552, in <module>
  File "/path/to/macos-x64/./voicevox_engine/synthesis_engine/make_synthesis_engine.py", line 83, in make_synthesis_engine
  File "/path/to/macos-x64/./voicevox_engine/dev/core/mock.py", line 72, in metas
  File "/path/to/macos-x64/./pathlib.py", line 1236, in read_text
  File "/path/to/macos-x64/./pathlib.py", line 1222, in open
  File "/path/to/macos-x64/./pathlib.py", line 1078, in _opener
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/macos-x64/voicevox_engine/dev/core/../../../VERSION.txt'
```

（バイナリ版でmock coreが動作しないのは別の問題 https://github.com/VOICEVOX/voicevox_engine/pull/251#issuecomment-1002819063 ですね）

LibTorchの依存関係

<details>

```
$ otool -L libc10.dylib
libc10.dylib:
	@rpath/libc10.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)

$ otool -L libtorch.dylib
libtorch.dylib:
	@rpath/libtorch.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libtorch_cpu.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libc10.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libiomp5.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)

$ otool -L libtorch_cpu.dylib
libtorch_cpu.dylib:
	@rpath/libtorch_cpu.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libiomp5.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	@rpath/libc10.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
```

</details>

2022-01-09 09:48 UTC, PickledChair commented
同じく、Mac でテストしてみました。 @aoirint さんと同様、0.10.preview.0 のコアを用いた場合、成功しました。

ただし、[0.10.preview.1](https://github.com/VOICEVOX/voicevox_core/releases/tag/0.10.preview.1) を使うと失敗します。`libcore_cpu_x64.dylib` がなくなり、代わりに `libcore_cpu.dylib` が同梱されているためのようです。

```
Traceback (most recent call last):
  File "/Users/suitcase/Downloads/macos-x64/voicevox_engine/synthesis_engine/make_synthesis_engine.py", line 51, in make_synthesis_engine
  File "/Users/suitcase/Downloads/macos-x64/voicevox_engine/synthesis_engine/core_wrapper.py", line 126, in __init__
  File "/Users/suitcase/Downloads/macos-x64/pathlib.py", line 1181, in resolve
  File "/Users/suitcase/Downloads/macos-x64/pathlib.py", line 363, in resolve
  File "/Users/suitcase/Downloads/macos-x64/pathlib.py", line 347, in _resolve
  File "/Users/suitcase/Downloads/macos-x64/pathlib.py", line 452, in readlink
FileNotFoundError: [Errno 2] No such file or directory: '/Users/suitcase/Downloads/core/libcore_cpu_x64.dylib'
Notice: Failed to make synthesis engine. This error will be ignored.
...
```

CPU アーキテクチャ名が名前から省かれたのは、 https://github.com/VOICEVOX/voicevox_core/issues/60 を受けて Universal バイナリにしたからなのかと予想したのですが、以下のように確認してみると、Universal バイナリにはなっていないようです（x64 のまま）。何かの手違いかもしれないのでコア側に Issue を立てたいと思います。

```
$ cd core
$ lipo -archs libcore_cpu.dylib
x86_64
$ lipo -info libcore_cpu.dylib
Non-fat file: libcore_cpu.dylib is architecture: x86_64
```

（この PR では基本的に 0.10.preview.0 のコアまでを扱う、という感じでしょうか？ 余計な情報でしたらすみません。一応参考情報として報告しました。）

2022-01-09 10:02 UTC, PickledChair commented
0.10.preview.1 のコアについて、よく見たら、他の OS 向けライブラリも、0.9 系以前と同じように CPU アーキテクチャ名がついていないですね。コアの 0.10 系はライブラリの名前はどうなるのでしょうか……？

2022-01-09 11:24 UTC, PickledChair commented
連続のコメントですみません。Mac で libtorch 版コアの使用に成功したので報告します。

@aoirint さんのコメント https://github.com/VOICEVOX/voicevox_engine/pull/254#issuecomment-1008262065 にあったように libtorch 版コアの使用に失敗したのは、ライブラリの読み込み順に起因するというよりは、rpath の中に core や libtorch のディレクトリが含まれていないからだと推測しました。そこで、以下のように `DYLD_LIBRARY_PATH` にそれらのディレクトリを含めるようにして実行してみました。これで正常にエンジンが動作することを確認しました。

```
DYLD_LIBRARY_PATH=/path/to/libtorch/lib:/path/to/core ./run \
  --old_voicelib_dir=/path/to/core \
  --old_model_type=libtorch \
  --old_model_lib_dir=/path/to/libtorch/lib
```

2022-01-09 15:10 UTC, takana-v commented
> libtorch 版コアの使用に失敗したのは、ライブラリの読み込み順に起因するというよりは、rpath の中に core や libtorch のディレクトリが含まれていないからだと推測しました。そこで、以下のように DYLD_LIBRARY_PATH にそれらのディレクトリを含めるようにして実行してみました。これで正常にエンジンが動作することを確認しました。

pythonでは後から`LD_LIBRARY_PATH`を指定してもうまくいかないので、予め依存ライブラリをロードしておき、コアを読み込むようにしています。
libtorch版を調査したところ、windowsでは`torch_cuda.dll`（CPUでは`torch_cpu.dll`）、linuxでは`libtorch.so`を予め読み込んでおくことでコアの依存関係が解決できるようです。
（`torch_cuda.dll`を読み込むときに`c10.dll`も読み込まれるので`c10.dll`を明示的に読み込む必要はなさそうです）

Macには詳しくないのですが、恐らく依存するファイルが同じディレクトリに入っていても`DYLD_LIBRARY_PATH`に入っていないとエラーになるのかもしれません。（`@rpath`ではなく相対パスにしないと解決できない？）

もしかしたら予めカレントディレクトリをlibtorchのパスにしてから読み込むと解決できるかもしれないのでちょっと試してみたいと思います。
> When the library name is a filename (that is, when it doesn’t include directory names), the dynamic loader searches for the library in several locations until it finds it, in the following order:
> 1. $LD_LIBRARY_PATH
> 2. $DYLD_LIBRARY_PATH
> 3. The process’s working directory
> 4. $DYLD_FALLBACK_LIBRARY_PATH

https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/DynamicLibraryUsageGuidelines.html#//apple_ref/doc/uid/TP40001928-SW21

2022-01-09 16:31 UTC, takana-v commented
https://github.com/takana-v/voicevox_engine/releases/tag/ctypes-test3
https://github.com/VOICEVOX/voicevox_engine/pull/254/commits/afaea8d9eec9c9c78de9c4ebf0b09f8a4bc5c54b 時点のバイナリです。
（expanduserの処理がきちんとできてないです）
お時間あるときにlibtorch版を試していただければ助かります。 
また、0.9台のコアの`otool -L libcore_cpu.dylib` の結果もお願いしたいです。
@aoirint @PickledChair

2022-01-09 17:04 UTC, PickledChair commented
先ほどは話がうまく飲み込めておらず失礼しました。エンジン実行中に任意のバージョンのコアに切り替えられるような実装を目指しているんですね（前もって複数コアの個々の場所がわかっていれば、エンジン起動時に指定できるんですが……理想的には完全に動的に読み込みたいですよね）。

新しいバイナリを試しましたがうまく行きませんでした。libiomp5.dylib は libtorch.dylib と同じディレクトリにありますが、それを認識できていない感じです。

```
$ ./run --old_voicelib_dir=$VOICELIB_DIR --old_model_type=libtorch --old_model_lib_dir=$MODEL_LIB_DIR
Traceback (most recent call last):
  File "/Users/suitcase/Downloads/test/macos-x64/voicevox_engine/synthesis_engine/make_synthesis_engine.py", line 54, in make_synthesis_engine
  File "/Users/suitcase/Downloads/test/macos-x64/voicevox_engine/synthesis_engine/core_wrapper.py", line 59, in __init__
  File "/Users/suitcase/Downloads/test/macos-x64/voicevox_engine/synthesis_engine/core_wrapper.py", line 46, in load_model_lib
  File "/Users/suitcase/Downloads/test/macos-x64/ctypes/__init__.py", line 373, in __init__
OSError: dlopen(/Users/suitcase/Downloads/libtorch/lib/libtorch.dylib, 0x0006): Library not loaded: @rpath/libiomp5.dylib
  Referenced from: /Users/suitcase/Downloads/libtorch/lib/libtorch.dylib
  Reason: tried: '/Users/distiller/project/pytorch/build/lib/libiomp5.dylib' (no such file), '/Users/distiller/project/miniconda/envs/wheel_py37/lib/libiomp5.dylib' (no such file), '/Users/distiller/project/pytorch/build/lib/libiomp5.dylib' (no such file), '/Users/distiller/project/miniconda/envs/wheel_py37/lib/libiomp5.dylib' (no such file), '/Users/suitcase/Downloads/test/macos-x64/./libiomp5.dylib' (no such file), '/usr/local/lib/libiomp5.dylib' (no such file), '/usr/lib/libiomp5.dylib' (no such file)
Notice: Failed to make synthesis engine. This error will be ignored.
Traceback (most recent call last):
  File "/Users/suitcase/Downloads/test/macos-x64/run.py", line 552, in <module>
  File "/Users/suitcase/Downloads/test/macos-x64/voicevox_engine/synthesis_engine/make_synthesis_engine.py", line 86, in make_synthesis_engine
  File "/Users/suitcase/Downloads/test/macos-x64/voicevox_engine/dev/core/mock.py", line 72, in metas
  File "/Users/suitcase/Downloads/test/macos-x64/pathlib.py", line 1236, in read_text
  File "/Users/suitcase/Downloads/test/macos-x64/pathlib.py", line 1222, in open
  File "/Users/suitcase/Downloads/test/macos-x64/pathlib.py", line 1078, in _opener
FileNotFoundError: [Errno 2] No such file or directory: '/Users/suitcase/Downloads/test/macos-x64/voicevox_engine/dev/core/../../../VERSION.txt'
```

こちらでも `DYLD_LIBRARY_PATH` の指定なしに共有ライブラリを読み込む方法を探っているところですが、まだ上手くいく方法は見つかっていません。

また、 https://github.com/VOICEVOX/voicevox_core/releases/tag/0.9.4 の `libcore_cpu.dylib` については以下の結果になりました：

```
$ otool -L libcore_cpu.dylib
libcore_cpu.dylib:
	@rpath/libcore.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libc10.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libtorch.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libtorch_cpu.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
```

2022-01-09 17:36 UTC, takana-v commented
> 前もって複数コアの個々の場所がわかっていれば、エンジン起動時に指定できるんですが……理想的には完全に動的に読み込みたいですよね

ちょっと双方で認識がずれているようなので...
今回のPRでは、起動時に2種類のコアをロードして使えるようにしています。
起動した後でロードしているわけではないので、`DYLD_LIBRARY_PATH`をエディタ側から起動するときに指定すれば問題ないように思いました。
ただし、あまり好ましくないので（onnx版では不要ですし）、なるべく`DYLD_LIBRARY_PATH`を指定せずに起動できるようにしたいです。

思いつく解決策としては二つあります。
- `install_name_tool`コマンドで相対パスで読み込むように修正する（詳細不明）
- 必要なdylibを手動で読み込む

恐らく、必要なdylibを依存順に読み込めば動くような気がします。
`???->libiomp5.dylib->libc10.dylib->libtorch.dylib->libtorch_cpu.dylib`

2022-01-09 18:44 UTC, PickledChair commented
おそらく自分はまだ完全には理解できていない点があるのと、少し見解が違うところがあるようなので、お手数ですがいくつか確認させてください（自分の認識の間違いを修正したいです）。

> 今回のPRでは、起動時に2種類のコアをロードして使えるようにしています。
> 起動した後でロードしているわけではないので、DYLD_LIBRARY_PATHをエディタ側から起動するときに指定すれば問題ないように思いました。

誤解していました。説明ありがとうございます！

> ただし、あまり好ましくないので（onnx版では不要ですし）、なるべくDYLD_LIBRARY_PATHを指定せずに起動できるようにしたいです。

これについては気持ち的には全く同意なのですが、以下のようにまだわかっていないことや、認識の違いがありそうです：

- コアは onnx 版と libtorch 版がそれぞれ任意のディレクトリにある前提でしょうか？
  - onnx 版と libtorch 版の双方とも、エンジンの `run` バイナリ等と同じディレクトリに共有ライブラリ群があれば正しく動くと思います。`run` のディレクトリが rpath に追加されるので、そのディレクトリ直下にある共有ライブラリが読み込み可能になるためです。
  - 逆に、どちらの版も `run` バイナリ等と異なるディレクトリにある場合に共有ライブラリのロードに失敗すると思います。なので、DYLD_LIBRARY_PATH の設定が「onnx版では不要」というのは常に正しいわけではないと思います。

> 思いつく解決策としては二つあります。
> - install_name_toolコマンドで相対パスで読み込むように修正する（詳細不明）

install_name_tool は Xcode に付属するツールだと思うので（間違いでしたらすみません）、ユーザーの環境ではほとんどの場合使えない気がします（前もって配布前のコアに install_name_tool を使うということでしたら、自分の誤解です。こちらであれば問題ないです）。

> - 必要なdylibを手動で読み込む
> 恐らく、必要なdylibを依存順に読み込めば動くような気がします。
> ???->libiomp5.dylib->libc10.dylib->libtorch_cpu.dylib->libtorch.dylib->libcore_cpu.dylib

これについて十分に検証できていないので断言はできないのですが、恐らく動かないと思っています。手元で試している限りでは、先に `libiomp5.dylib` を読み込むようにして、その後に `libtorch.dylib` や `libtorch_cpu.dylib` を読み込むようにソースコードを改変したときに、`libtorch_cpu.dylib` の読み込み時に

```
OSError: dlopen(/Users/suitcase/Downloads/libtorch/lib/libtorch_cpu.dylib, 0x0006): Library not loaded: @rpath/libiomp5.dylib
```

というエラーが出ました。依存順に読み込んで行っても、このケースでは `libtorch_cpu.dylib` の読み込み時に改めて `libiomp5.dylib` を探索しに行って見つからない感じになっているようです（検証不足かもしれません。 @aoirint さんに引き続き確認していただきたいと思っています）。

2022-01-09 18:46 UTC, Hiroshiba commented
> 0.10.preview.1 のコアについて、よく見たら、他の OS 向けライブラリも、0.9 系以前と同じように CPU アーキテクチャ名がついていないですね。コアの 0.10 系はライブラリの名前はどうなるのでしょうか……？

@PickledChair すごく前へのコメントですが、こちらアップロードするバイナリを間違えていたのが原因でした。単純なミスで申し訳ないです。
[0.10.preview.2](https://github.com/VOICEVOX/voicevox_core/releases/tag/0.10.preview.2)だとうまく動くと思います。

2022-01-09 19:04 UTC, takana-v commented
> コアは onnx 版と libtorch 版がそれぞれ任意のディレクトリにある前提でしょうか？

そうですね。別途DLする感じで考えてます。

> onnx 版と libtorch 版の双方とも、エンジンの run バイナリ等と同じディレクトリに共有ライブラリ群があれば正しく動くと思います。run のディレクトリが rpath に追加されるので、そのディレクトリ直下にある共有ライブラリが読み込み可能になるためです。

確かにそうですね、考慮できていませんでした。

> install_name_tool は Xcode に付属するツールだと思うので

これもこちらの調査不足でした、ユーザー側で適用するのは難しそうですね...

> libtorch_cpu.dylib の読み込み時に改めて libiomp5.dylib を探索しに行って見つからない感じになっているようです

検証ありがとうございます。
これまでの結果を含めて考えると、Macでは`DYLD_LIBRARY_PATH`を指定するのが必要になるでしょうか...
（libtorchについてUbuntuで検証した時は、別途DLしたもののフォルダを指定して動作したのでLinuxでは`LD_LIBRARY_PATH`は不要そうです）

後、MacではDLLの読み込みに失敗すると`OSError`が返るんですね...
windowsでは`FileNotFoundError`が返る仕様で、それに基づいて書いたので修正が必要そうです。

2022-01-09 19:45 UTC, PickledChair commented
自分の認識不足が改善されました。先ほどは説明ありがとうございました！

> 後、MacではDLLの読み込みに失敗するとOSErrorが返るんですね...
> windowsではFileNotFoundErrorが返る仕様で、それに基づいて書いたので修正が必要そうです。

https://docs.python.org/ja/3/library/ctypes.html#ctypes.CDLL によると、Windows でも、ロードした dll がさらに依存している dll が見つからない時に `OSError` になるようです。ただ、コアの dll 群をバラバラの場所に配置するユーザーはあまりいないと思うので、Windows ではこのエラーはあまり起こらないと思います。

Mac のケースでも、ロードしようとした dylib が見つからなかったわけではないので `FileNotFoundError` が起こらず、その dylib がさらに依存している dylib が見つからなかったので、この `OSError` が出たのだと思います。

2022-01-09 20:15 UTC, takana-v commented
検証ありがとうございます。
Macでは`DYLD_LIBRARY_PATH`を指定してもらうようにしたいと思います。
動作確認の方はこれで一旦終了して、レビューの方をお願いしたいです。

2022-01-09 20:45 UTC, Hiroshiba commented
> MacではDYLD_LIBRARY_PATHを指定してもらうようにしたいと思います。

`DYLD_LIBRARY_PATH`が必要なのって、過去のlibtorch版を使う場合だけという認識で合っていそうでしょうか。
であれば、そもそもonnx版とMac版が正式リリースされるタイミングはちょうど一緒なので、Macで過去のバージョンを使いたい方は珍しそうな気がしています。
ということで、あまり考えなくても良いのかなと`DYLD_LIBRARY_PATH`が必要なのはそこまで気にしなくても良いのかなと思いました。
（需要が非常に少なさそうなので、サポート自体も一旦しなくて良いかなと感じています）

2022-01-14 10:38 UTC, PickledChair requested changes
全体的に問題なさそうでした！ 一箇所だけ不要そうな部分があったので変更をリクエストしました（コンフリクトが解消したら再度レビューします）。

2022-01-14 10:38 UTC, PickledChair commented on .github/workflows/build.yml
> +          pip install -r requirements-dev.txt
requirements-dev.txt の依存関係のインストールは https://github.com/takana-v/voicevox_engine/blob/ab122643eab57e5cd5d54856dfbb4887569a9392/.github/workflows/build.yml#L59-L63 で行っているので、ここで改めてインストールしなくて良さそうです。

2022-01-14 11:25 UTC, takana-v commented
ちょっとした問題が発生しました。
`cpu_num_threads`引数に対応していない0.10.prewiew2とpreview3の判別が難しい感じです。
プレビュー版への対応を切るという手もありますが、切ってもいいかちょっと悩んでいます。

2022-01-14 11:51 UTC, PickledChair commented
確かにコアの API が 0.10.prewiew.2 と preview.3 の前後で変わりましたね（ `initialize` 関数の引数に `int cpu_num_threads` が加わった）。どちらも onnx 版なので、libtorch 版と onnx 版とでコアの種類を区別している現在の仕組みでは判別できないですね……。

この PR の機能を基本的にユーザー向けの機能（開発者向けでなく）と考えると、ユーザーがプレビュー版（特に 0.10.preview.0 〜 0.10.preview.2 ）のエンジンを使うニーズがあるかどうかで判断が分かれそうです。ほとんどの場合リリース版を使うだろうと考えれば、0.10.preview.2 までの onnx 版のサポートを切る判断で良い気がします。 @Hiroshiba どうでしょうか……？

2022-01-14 12:13 UTC, Hiroshiba commented
プレビュー版は正式版が出たら全部消そうかなと思ってるくらいなので、非対応で全く問題ないと思います！

2022-01-14 15:42 UTC, aoirint requested changes
気になったところにコメントしてみました！

2022-01-14 15:42 UTC, aoirint commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +            if not self.core.initialize(".", use_gpu):
忘れないようにメモ: cpu_num_threadsへの対応をおねがいします・・・！（model_libでの切り替えのほかに、引数の数を見分けるような方法があるともっとよさそうですが...）

2022-01-14 15:42 UTC, aoirint commented on run.py
> +    parser.add_argument("--old_model_type", type=str, default="onnxruntime")
- <https://github.com/VOICEVOX/voicevox_project/issues/3#issuecomment-984860460>

ここの方針が決まっているかちょっとわからないですが、
現行のコアと古いコアを起動オプションで区別しなくてもいいかもと思いました（model_typeのみ必要）。

`old_*`を削除すると、コアを切り替えるたびにエンジンを再起動することになります。

エンジン側でキャラクターごとにバージョンを指定してコアを変えるのを達成するには、キャラクターとバージョンのマッピングを持って、2つだけではなく、任意の数のコアを初期化して保持できるような実装が必要な気がしました。

2022-01-14 15:42 UTC, aoirint commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +        LibraryLoader(CDLL(str((model_lib_dir / lib_name).resolve(strict=True))))
model_lib_dirにNoneを許容して、システムのパスから共有ライブラリを読み込む（`lib_name`のみで読み込む）方法があるとよさそうに思いました。

2022-01-14 15:57 UTC, takana-v commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +                    )
`use_gpu`の通りに読み込むと、GPU版が使えないのか単に使っていないのかが`suppoted_devices`関数で判別できないと思ったのでこのようにしています。

2022-01-14 15:59 UTC, takana-v commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +            os.chdir(cwd)
作業ディレクトリをvoicelib直下にしないとエラーになってしまうのでこのようにしています。
（ちょっと原因がよく分からないです......）

2022-01-14 16:10 UTC, aoirint commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +                    )
あ、たしかにそうですね！　core.initializeでGPUを使うかどうかが切り替わっているので、これでよさそうです！

2022-01-14 16:35 UTC, takana-v commented on run.py
> +    parser.add_argument("--old_model_type", type=str, default="onnxruntime")
>old_*を削除すると、コアを切り替えるたびにエンジンを再起動することになります。

https://github.com/VOICEVOX/voicevox_project/issues/3#issuecomment-984860460 は、「エンジンが過去コアもロードできるようにする」ではなく、「過去コアと最新コアを**同時**に利用できる」ということが目標だと解釈しています。

>現行のコアと古いコアを起動オプションで区別しなくてもいいかも

>任意の数のコアを初期化して保持

確かに任意の数のコアを使える方が便利ですね。
`--voicelib_dir`を複数取れるようにして、`--libtorch_dir`と`--onnxruntime_dir`引数を追加するのもいいかなと思いました。
コアの種類の判別は、事前にカレントディレクトリのライブラリと引数指定のライブラリを読み込んでおけば不要になると思います。

2022-01-15 18:56 UTC, takana-v commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +                )
別の関数に切り出しました。

2022-01-15 18:56 UTC, takana-v commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +        LibraryLoader(CDLL(str((model_lib_dir / lib_name).resolve(strict=True))))
CDLLのみに変更しました。

2022-01-15 18:57 UTC, takana-v commented on voicevox_engine/synthesis_engine/make_synthesis_engine.py
> +    use_mock: Optional[bool] = True,
`enable_mock`という名前に変更しました。
これで多少は誤解が少なくなるかと思います。

2022-01-15 18:58 UTC, takana-v commented on .github/workflows/build.yml
>            path: download/voicevox_core_source
該当部分の削除を行いました。

2022-01-15 18:58 UTC, takana-v commented on .github/workflows/build.yml
> +            --include-data-file=../download/core/libcore_cpu_x64.dylib=./ \
matrixから参照するように変更しました。

2022-01-15 18:58 UTC, takana-v commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +            if not self.core.initialize(".", use_gpu):
対応しておきました。

2022-01-15 18:59 UTC, takana-v commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +        LibraryLoader(CDLL(str((model_lib_dir / lib_name).resolve(strict=True))))
windowsでしか確認できていませんが、PATHからlibtorchやonnxのdllを読み込むように変更しました。

2022-01-15 19:11 UTC, takana-v commented
マスターとの変更点
- `voicelib_dir`引数を複数取れるように変更
- `model_lib_dir`引数を追加（libtorchやonnxのパス）
- `enable_mock`引数を追加（コアの読み込みエラー時にmockを使うようになります）
- API`/core_versions`を追加
- APIの引数に`version`を追加（デフォルトは最新のコア）
- cancellabe関係の処理を一時的に無効化

cancellableをどうするかは考え中です。
- 最新のコアだけ起動（処理が複雑になるかも）
- 全ての過去バージョンを起動
- いっそこの機会に削除

2022-01-16 03:42 UTC, Hiroshiba commented
> cancellableをどうするかは考え中です。
> 最新のコアだけ起動（処理が複雑になるかも）
> 全ての過去バージョンを起動
> いっそこの機会に削除

cancellableって今はenable状態にして起動した場合のみ使えるんでしたっけ。
であれば、計算資源は消費しますが`全ての過去バージョンを起動`が良いのかなと思いました。
実装コストが高ければ、いったん中途半端に対応されている状態（oldは動かない、とか）になってしまっても大丈夫です。（そうアナウンスします）
将来`任意の数のコア`を起動できるようになってから良い感じに実装するのが効率的かも。

2022-01-16 06:39 UTC, takana-v commented
> 将来任意の数のコアを起動できるようになってから良い感じに実装するのが効率的かも。

もうすでに任意の数のコアを起動できるようになっています。
なので、cancellableもすべての過去バージョンを起動すると計算資源が枯渇する恐れがあるので迷ってます。

2022-01-16 07:31 UTC, Hiroshiba requested changes
任意の数良いですね！！
いまのところエンジンの仕様を知らないと実現できないので、まあ計算資源枯渇はとりあえず気にしなくても良いのかなと感じました。
というのと、現状でも全部loadするから枯渇するときは枯渇しそうです。

ちょっとコードを読んでみました。
すでに結構な変更になっているので、cancellableは別でも良いかもと感じました。
結構簡単に実装できそうであれば実装しちゃっても良いのではと思います･･･！！

2022-01-16 07:31 UTC, Hiroshiba commented on voicevox_engine/synthesis_engine/make_synthesis_engines.py
> +            model_lib_dir = [model_lib_dir]
ここに来るのは`model_lib_dir==None`のときで、そうなると`model_lib_dir=[None]`になり、この下の`model_lib_dir = [p.expanduser() for p in model_lib_dir]`がエラーになりそうです。

2022-01-16 07:31 UTC, Hiroshiba commented on voicevox_engine/synthesis_engine/make_synthesis_engines.py
> +        root_dir = Path(__file__).parents[2]
Nuitkaビルドしていると`__compiled__`が含まれるんですね！！
結構馴染みがないので、意図をコメントで残すか、`is_nuitka_compiled= "__compiled__" in globals()`みたいに意味のわかる変数に代入するかすると良いかもと思いました。

2022-01-16 07:31 UTC, Hiroshiba commented on voicevox_engine/synthesis_engine/make_synthesis_engines.py
> +    model_lib_dir: Optional[List[Path]] = None,
変数名からlistだとわからないのでバグ埋め込みの原因になるかもと感じました。
変数名をdirsやdir_listにするのはどうでしょう。

2022-01-17 09:19 UTC, takana-v commented on voicevox_engine/synthesis_engine/make_synthesis_engines.py
> +            model_lib_dir = [model_lib_dir]
変数名のミスでしたのでhttps://github.com/VOICEVOX/voicevox_engine/pull/254/commits/5ed40472f26422c2cabb2a72500db5f5db6e4208 で修正しました。

2022-01-17 09:19 UTC, takana-v commented on voicevox_engine/synthesis_engine/make_synthesis_engines.py
> +        root_dir = Path(__file__).parents[2]
コメントをhttps://github.com/VOICEVOX/voicevox_engine/pull/254/commits/5ea60f43f8621c2e1b9bb9508ddde238cb3769aa で追加しました。

2022-01-17 09:19 UTC, takana-v commented on voicevox_engine/synthesis_engine/make_synthesis_engines.py
> +    model_lib_dir: Optional[List[Path]] = None,
https://github.com/VOICEVOX/voicevox_engine/pull/254/commits/48761d9d3ab8a2d7607b16284191d98bf79979f7 で変更しました。

2022-01-21 16:23 UTC, Hiroshiba approved these changes
LGTM！！

cancelableが一旦なくなる点ですが、このPRをrelease-0.10に一旦含めないようにし、release-0.11までの復活を目指そうかなと考えています。
であればバージョンアップ時にインターフェイスが変わらないので、問題にならないかなと思います！
（忘れちゃいそうなので、戻すタスクのissue化したほうが良いかもです）

2022-01-21 17:19 UTC, Hiroshiba approved these changes

2022-01-21 17:19 UTC, Hiroshiba commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +def load_model_lib(model_lib_dir: List[Path]):
`model_lib_dirs`にすると混乱が少なそうに感じました！

2022-01-21 17:19 UTC, Hiroshiba commented on run.py
> +    parser.add_argument("--model_lib_dir", type=Path, default=None, action="append")
model_libとvoicelibは意味的に似ていそうなのと、modelはFastAPIでも用語が使われているのでちょっと避けたいです。
`runtime_dir`とかどうでしょう？

2022-01-21 17:57 UTC, takana-v commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +def load_model_lib(model_lib_dir: List[Path]):
変更漏れだったので修正しました。

2022-01-21 17:59 UTC, takana-v commented
変更したので最新版の説明です。

マスターとの変更点
- `voicelib_dir`引数を複数取れるように変更
- `runtime_dir`引数を追加（libtorchやonnxのパス）
- `enable_mock`引数を追加（コアの読み込みエラー時にmockを使うようになります）
- API`/core_versions`を追加
- APIの引数に`version`を追加（デフォルトは最新のコア）
- cancellabe関係の処理を一時的に無効化

2022-01-21 18:51 UTC, aoirint reviewed
ちょっと細かいのですが、コメントを追加しました・・・！

2022-01-21 18:51 UTC, aoirint commented on run.py
> +    )
`len(synthesis_engines) == 0`になった場合の処理が`generate_app`か、ここに必要そうです。

2022-01-21 18:51 UTC, aoirint commented on Dockerfile
> +CMD [ "gosu", "user", "/opt/python/bin/python3", "./run.py", "--use_gpu", "--voicelib_dir", "/opt/voicevox_core/", "--runtime_dir", "/opt/onnxruntime/lib", "--host", "0.0.0.0" ]
メモです。

ONNX Runtimeのディレクトリを、システムにパスを通すか、`--runtime_dir`でパスを渡すか、若干悩みますが、`voicelib_dir`も渡しているので、これでいいかなと思いました！

2022-01-21 18:51 UTC, aoirint commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +def load_model_lib(runtime_dirs: List[Path]):
引数名を変えたので、load_runtime_libにするのはどうでしょう？

（ランタイムというのはMSVCランタイムのような形で聞きますが、ランタイムライブラリの略で単体では実行時、の意味だと思うので、runtime_dirだとworking directoryと混同しそうな気はしますが、いい名前がわからない...）

2022-01-21 18:55 UTC, aoirint commented on run.py
> +    parser.add_argument("--old_model_type", type=str, default="onnxruntime")
> 同時に利用できる

たしかにそうですね！
ctypes実装は、複数のコアを同時にロードするためにCythonから切り替えたのでした！

2022-01-21 19:01 UTC, aoirint commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +            os.chdir(cwd)
なるほどです！
マージ後でもいいと思いますが、本来いらなさそうなので、検証しておきたいなと思いました！

古いコアには、initializeに渡すパスの末尾にスラッシュが必要という仕様があったと思いますが、それとは関係なさそうですかね・・・？

2022-01-22 04:20 UTC, PickledChair commented on run.py
> +    def select_engine(core_version: Optional[str]):
この関数の名前については良いものがないかと自分も考えていたのですが、get_engine が良さそうですね。old_engine をグローバル変数で持っていた当初の実装であれば select_engine や use_engine が自然だったと思うのですが、現在は synthesis_engines からバージョン名指定でエンジンのインスタンスを取ってきているので、get_engine という名前が自然に感じる実装に変わった気がします。

また、戻り値の型ヒント（ `-> SynthesisEngineBase` ）もあった方が良さそう？ と思いました。

2022-01-22 05:19 UTC, PickledChair requested changes
関数の戻り値の型ヒント周りで気になった点をコメントしました。ただ、generate_app 関数内で定義されている関数を始めとして、多くの関数で引数の型ヒントを書いているのに戻り値の型ヒントを書いていないことに気がつきました（付け足し始めるとキリがない？）。あってもなくても動作に影響するものではないと思うので、そのままにしておくというのも一つの手だと思うのですが、これについて何か方針があったりするでしょうか……？

2022-01-22 05:37 UTC, PickledChair commented on voicevox_engine/synthesis_engine/make_synthesis_engines.py
> +) -> List[SynthesisEngineBase]:
これに関連して、 https://github.com/takana-v/voicevox_engine/blob/0ff4f56259b0df77b5f61c208fa3e4b2ffad9b11/run.py#L51-L53 も引数 `synthesis_engines` の型は `Dict[str, SynthesisEngineBase]` ですね。

2022-01-23 09:08 UTC, takana-v commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +            os.chdir(cwd)
バージョンによって関数が異なる可能性があり、現状ではinitializeしてmetas()を呼ばないとバージョンが分からないので、__init__()の中でinitializeしてます。

2022-01-23 09:14 UTC, takana-v commented on voicevox_engine/synthesis_engine/make_synthesis_engines.py
> +    load_model_lib(model_lib_dirs)
パスが異なる同名のdllは別物として読み込まれるはずです。
ただ依存関係の解決でどのバージョンが優先されるかどうかはちょっと分からないです。
onnxは下位互換性があるようですが、バージョンが上のものでも動くんでしょうか...？

2022-01-23 09:18 UTC, takana-v commented on run.py
> +    )
コード的にはmockが入るかエラーで落ちるはずですが、念のためチェックを入れておこうと思います。

2022-01-23 09:23 UTC, takana-v commented
型ヒントについては、 #256 で一旦追加されましたが不具合があり、やむなくリバートしました。
別で型ヒントを追加するPRを立ててもいいかもしれませんね。

2022-01-23 09:49 UTC, PickledChair commented
> 型ヒントについては、 #256 で一旦追加されましたが不具合があり、やむなくリバートしました。
> 別で型ヒントを追加するPRを立ててもいいかもしれませんね。

なるほど、これのリバートが関係していたんですね！ 情報ありがとうございます。型ヒントを加えることについて、Issue か PR を立てることを検討しています。

2022-01-23 11:27 UTC, aoirint commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +            os.chdir(cwd)
なるほどです！

コア側にinitializeせずに呼び出せるバージョンAPIがほしいかなと思いました。

- <https://github.com/VOICEVOX/voicevox_core/issues/65>

上のIssueでバージョン情報の埋め込みがされて、その上でinitalize不要なAPIが追加されれば、`__init__`とinitializeを分けることができそうでしょうか。

その対応がされても、結局LibTorch版コアではinitializeを呼び出さないとバージョンを取得できないですが、LibTorch版コアではmetas.jsonをエンジン側からパースするくらいはしてもいいのかもと思いました（コンストラクタにバージョンを渡してinitialize時に一致を検査、とか）。

もしくは、コアをエンジンに読み込ませる時点でバージョンが分かっている仕様（起動引数で渡すとか、バージョン情報がファイルシステムから取得できる状態になっているとか）にする手もあるかもと思いました。

2022-01-24 08:29 UTC, takana-v commented
とりあえず修正終わりました。
cancellableに関してはかなりめんどくさそうなので後回しです。
（本音を言うと機能ごと削除したいです。正直リターンが労力に見合わないので...）

2022-01-24 11:37 UTC, aoirint reviewed
よさそうでした！ 対応ありがとうございます！
1点だけコメントを追加しました。

2022-01-24 11:37 UTC, aoirint commented on voicevox_engine/cancellable_engine.py
> +        runtime_dirs=args.runtime_dir,
make_synthesis_engine関数はもうないので、cancellable_engineをimportすると、make_synthesis_engineがimportできないというエラーが出そうです。

動作はしなくてもいいので、モジュールの先頭かコンストラクタで明示的に例外を投げるか、make_synthesis_enginesをimportするようにだけ変更してもいいかもです・・・！

動作しない旨を伝えるFIXMEコメントもcancellable_engineに残しておきたいです。

2022-01-24 11:48 UTC, takana-v commented on voicevox_engine/cancellable_engine.py
> +        runtime_dirs=args.runtime_dir,
https://github.com/VOICEVOX/voicevox_engine/pull/254/commits/ceb11b873e4153affe17b10863a79203005c884e にて対応しました。

2022-01-24 11:51 UTC, aoirint approved these changes
LGTM！！

2022-01-24 11:53 UTC, Hiroshiba commented
> （本音を言うと機能ごと削除したいです。正直リターンが労力に見合わないので...）

相談感謝です！！
最終的には総合的に判断して機能消去でもOKです。
まぁ、今回は一旦非活性化ということで…！

2022-01-24 13:11 UTC, PickledChair approved these changes
LGTM！！（お疲れ様でした。グッジョブです！👍）

2022-01-24 13:12 UTC, PickledChair commented
https://github.com/VOICEVOX/voicevox_engine/pull/254#pullrequestreview-859767158 で

> cancelableが一旦なくなる点ですが、このPRをrelease-0.10に一旦含めないようにし、release-0.11までの復活を目指そうかなと考えています。

とありましたが、普通にマージしても良い感じですか……？

2022-01-24 15:38 UTC, Hiroshiba commented
> 普通にマージしても良い感じですか……？

適宜releaseブランチにマージしていくだけだったので、大丈夫でした！
（気にしていただいてありがとうございます！）

とりあえずマージしちゃいます！
お疲れさまです、ありがとうございました････！！！！！

2022-01-24 15:38 UTC, merged