refacter: data modelを分離
VOICEVOX/voicevox_engine pull request #256
Opened 2021-12-29 17:56 UTC by qwerty2501

## 内容

APIで返す型と内部で使う型が同じだとフィールドをおいそれと変えることが難しいので、型を分離する

2021-12-29 18:19 UTC, qwerty2501 commented
とりあえず分離したけど、model.pyの方の型はBaseModelとかFieldとかなくして、dataclassにしたほうが良さそう

2021-12-29 18:45 UTC, qwerty2501 commented on voicevox_engine/model.py
> -class ParseKanaBadRequest(BaseModel):
これはhttp文脈の型なので移動させた

2021-12-29 18:45 UTC, qwerty2501 commented on voicevox_engine/webapi/fast_api_model.py
> +from ..model import ParseKanaError, ParseKanaErrorCode
ParseKanaBadRequestつくるのに必要なため参照

2021-12-30 17:44 UTC, qwerty2501 commented
とりあえずデータ型を分離して、変換関数を実装しました
以下判断お願いします

- この変更を取り込むべきか
- model.pyの方の型はBaseModelとかFieldとかなくして、dataclassにするべきか
- full_context_label.pyにある型もmodel.pyに統合するべきか(PR分けたほうが良さそう)

2021-12-30 18:29 UTC, Hiroshiba commented
> この変更を取り込むべきか

たしかに変更量は結構大きめですが、取り込んじゃいましょう！！

ただもうちょっと実装の負担を減らせると嬉しいかなと思いました。
たとえばmora_modelを変換するためにfrom_mora_modelやto_mora_modelのglobal関数を実装すると、使用者が対応するコンバータを探す手間が増えることに気づきました。
なので各fastapi modelクラスにto_engineとfrom_engineのようなメソッドを付けちゃっても良いかもと感じました。
（汎用convert関数を作って中で型を見て変換、ということもできるのですが、こうするとpythonの型推論が壊れそうなので。。）

> model.pyの方の型はBaseModelとかFieldとかなくして、dataclassにするべきか

dataclassにしちゃったほうが良いと思います。
ただ、Modelのプロパティ値とdataclassのプロパティ値は微妙に型が合わなそうなので、一旦ModelのままにしてFIXMEコメントを残すと良いのかなと感じました。

> full_context_label.pyにある型もmodel.pyに統合するべきか(PR分けたほうが良さそう)

full_context_labelはOpenJTalkに引っ張られる仕様なため、エンジン用とはまた変わってきそうな気もします。
なのでそのままの方が良いかもと思いました。

2021-12-30 19:22 UTC, qwerty2501 commented
> なので各fastapi modelクラスにto_engineとfrom_engineのようなメソッドを付けちゃっても良いかもと感じました。

~engineだと何の型にするのか想像しにくいのではないでしょうか？ model.py にあるのだからto_model,from_modelにするか、modelが紛らわしいのならmodel.pyの名前を例えばdomain.pyにし、to_domain,from_domainにしたほうが良さそうに感じました。

> ただ、Modelのプロパティ値とdataclassのプロパティ値は微妙に型が合わなそうなので、一旦ModelのままにしてFIXMEコメントを残すと良いのかなと感じました。

:+1: 

> full_context_labelはOpenJTalkに引っ張られる仕様なため、エンジン用とはまた変わってきそうな気もします。
なのでそのままの方が良いかもと思いました。

このPRではやりませんが、残すのであればそれらの型名にプレフィックスでOpenJTalkをつけたほうが良さそうですね。似たような型があるので混同しそうです

2021-12-30 19:58 UTC, Hiroshiba commented
> ~engineだと何の型にするのか想像しにくいのではないでしょうか？ 

例えば`Mora`に`to_engine()`（`Mora.to_engine()`）を作って、エンジン用のMora型に変えるというのを想像していました！

2021-12-31 06:21 UTC, qwerty2501 commented
from_engine,to_engineメソッドを各クラスに実装しましたcyclic importになったのでもとの実装は消しました

2021-12-31 20:31 UTC, Hiroshiba requested changes
大丈夫そうです！
後世に伝えるにあたってちょっと変えれそうなところをコメントしてみました。

2021-12-31 20:31 UTC, Hiroshiba commented on run.py
> +voicevox_enbine/model.pyで定義されている型は内部で使用する方なので、リクエスト及びレスポンスを行う際に使用してはならない。
タイポ発見です
```suggestion
voicevox_enbine/model.pyで定義されている型は内部で使用する型なので、リクエスト及びレスポンスを行う際に使用してはならない。
```

2021-12-31 20:31 UTC, Hiroshiba commented on test/test_fastapi_model.py
> +    def _asserts(self, expected, given, actual):
何をassertしているかぱっとわからないかもです。
良い名前が思いつかなかったのですが、givenが変換前であることがわかると良いのかなと感じました。
変数名とメソッド名で表すのが難しそうであればコメントでも良いかもです。

2021-12-31 20:31 UTC, Hiroshiba commented on test/test_fastapi_model.py
> +        self.assertEqual(given, actual)
`self.assertEqual(given, actual)`の意図としては、このプルリクエストでは一致していることを確認したいけど、将来的には変わっていても良いという認識で合っていそうでしょうか。
となると、将来値を変更したときにここがエラーになり、一致することを保証したいのかと勘違いしそうです。
なにかしらコメントを残すと良いかもと感じました。

2022-01-01 01:44 UTC, qwerty2501 commented on test/test_fastapi_model.py
> +        self.assertEqual(given, actual)
これあるとまずいですね！消しました

2022-01-01 01:45 UTC, qwerty2501 commented on test/test_fastapi_model.py
> +    def _asserts(self, expected, given, actual):
関数名と変数名変えてみました。これでだめならコメント追加します

2022-01-01 03:44 UTC, Hiroshiba commented on test/test_fastapi_model.py
> +    def _asserts(self, expected, given, actual):
良さそうです！！

2022-01-01 03:45 UTC, Hiroshiba approved these changes
LGTM！！

2022-01-01 22:09 UTC, aoirint approved these changes
LGTM！！

2022-01-02 00:33 UTC, merged