疑問文の仕様変更反映 #272
VOICEVOX/voicevox_engine pull request #273
Opened 2022-01-06 14:48 UTC by qwerty2501

## 内容
- AccentPhraseにis_interrogativeをもたせる
- 疑問符Mora追加を調整前ではなく調整後に行うようにした https://github.com/VOICEVOX/voicevox_engine/issues/272#issuecomment-1006316072
- APIが動かなくなるため #253 の修正をここに統合

## 関連 Issue
refs #272 #253
close #255

## スクリーンショット・動画など
accent_phraseのis_interrogativeがない状態でrequestしてもエラーにならないことの確認
![accent_phrase_add_improve_evidence](https://user-images.githubusercontent.com/939468/148408995-2c11bebc-acd0-4459-9a37-d3c08c9aeebd.gif)

## その他

2022-01-06 14:53 UTC, qwerty2501 commented on test/test_synthesis_engine_base.py
> +        )
pitch 0だと疑問符つけない実装にしたため、pitchがちゃんと生きてる値にしたほうがよさそうなので修正

2022-01-06 14:53 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +    if accent_phrase.is_interrogative and not (len(moras) == 0 or moras[-1].pitch == 0):
https://github.com/VOICEVOX/voicevox_engine/issues/272#issuecomment-1006634039 により最終moraのpitchが0の場合は疑問符moraをつけない実装にしてみたが本当にそうなのか？

2022-01-06 15:11 UTC, qwerty2501 commented
is_kana時の/accent_phraseが上手く動かなくなるので #255 の修正内容もこっちで行う

2022-01-07 19:07 UTC, Hiroshiba commented on test/test_synthesis_engine_base.py
> +        print(actual)
👀

2022-01-07 19:08 UTC, Hiroshiba commented
ディスカッションがあったのですが、 https://github.com/VOICEVOX/voicevox_engine/issues/272#issuecomment-1007659673 のとおり結論が出たので、アサインしてみます！

2022-01-08 03:02 UTC, qwerty2501 commented on test/test_synthesis_engine_base.py
> +        print(actual)
あっ

2022-01-08 03:05 UTC, qwerty2501 commented on test/test_synthesis_engine_base.py
> +        print(actual)
fixed

2022-01-08 07:22 UTC, takana-v requested changes

2022-01-08 07:22 UTC, takana-v commented on voicevox_engine/kana_parser.py
> +                text += mora.text
最後のモーラのpitchが0かつaccent_phraseのis_interrogativeがTrueの場合、kanaが誤ったものになってしまいます。
（例：`きゃっ？`のkanaが`キャ'？`になる）
mockだとpitchが0になるので、恐らく常にkanaが誤ったものになってしまっています。

2022-01-08 12:59 UTC, qwerty2501 commented on voicevox_engine/kana_parser.py
> +                text += mora.text
修正しました〜

2022-01-08 15:28 UTC, takana-v approved these changes
LGTM！

2022-01-08 15:28 UTC, takana-v commented on test/test_synthesis_engine_base.py
> +def yukarin_s_mock(length: int, phoneme_list: numpy.ndarray, speaker_id: numpy.ndarray):
コアのmockを使いまわせると嬉しいですが、どうやらfastapiから呼ばれる前提で書かれているので、これでも問題ないかと思います。

2022-01-08 16:12 UTC, qwerty2501 commented on test/test_synthesis_engine_base.py
> +def yukarin_s_mock(length: int, phoneme_list: numpy.ndarray, speaker_id: numpy.ndarray):
coreにもmockがあったんですね。
pitchが最大値超えないようにしたかったのでそれが満たせるなら使っても良いかもですが、そもそも一番最善なのは `MockSynthesisEngine` がMockとして機能することなのでどちらにしろ将来的にはリファクタリングは必要になってきそうです。
余談ですがこのリポジトリでmockとされてるもののほとんどはStubなので名前変えたほうが良いかもです。

2022-01-09 06:54 UTC, qwerty2501 commented on voicevox_engine/synthesis_engine/synthesis_engine_base.py
> +    if accent_phrase.is_interrogative and not (len(moras) == 0 or moras[-1].pitch == 0):
結論:
> > わりきってpitch=0の場合はmoraを追加しないという実装のみにする
>
> が良いかなと思いました！

https://github.com/VOICEVOX/voicevox_engine/issues/272#issuecomment-1007639332

のため実装はこのままとする

2022-01-10 17:58 UTC, aoirint approved these changes
LGTM！ コードは問題なさそうでした！

2022-01-10 17:59 UTC, merged