Github Actionsのmatrix変数をenvに変更
VOICEVOX/voicevox_engine pull request #276
Opened 2022-01-06 16:04 UTC by Hiroshiba

## 内容

Github Actionsで、コアのバージョンなどを書き換える場所が分散していたので、エディタのようにまとめるようにしてみました。
これでアプデリリースの手間がちょっと減ったかなと思います。

2022-01-07 05:54 UTC, PickledChair requested changes
エラーになった・なりそうだった部分についてコメントしました。確認よろしくお願いいたします……！

2022-01-07 05:54 UTC, PickledChair commented on .github/workflows/build.yml
>              VOICEVOX_CORE_EXAMPLE_VERSION=${{ matrix.voicevox_core_example_version }}
`matrix.voicevox_core_example_version` は https://github.com/VOICEVOX/voicevox_engine/pull/276/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L303 の削除で消えたので、ここでエラーになりそうです。

また、これは今回の PR とは別なのですが、`VOICEVOX_CORE_EXAMPLE_VERSION` はもう使われていない変数ですね。代わりに `VOICEVOX_CORE_SOURCE_VERSION` が使われているはずです（すみません、 #249 のレビュー時に見落としていました……。使われていない変数を指定して warning が出なかったのがちょっと不思議です。警告がなかったので気づけませんでした）。

以上を合わせて考えると、ここは

```
VOICEVOX_CORE_SOURCE_VERSION=${{ env.VOICEVOX_CORE_SOURCE_VERSION }}
```

とするのが適切かと思います。念の為 @aoirint さんにも意見を伺いたいです。

2022-01-07 05:54 UTC, PickledChair commented on .github/workflows/build.yml
> +
`env` が２つになっていたのでエラーでビルドが通っていませんでした：

https://github.com/VOICEVOX/voicevox_engine/actions/runs/1663775998/workflow

2022-01-07 19:09 UTC, Hiroshiba commented on .github/workflows/build.yml
> +
うわほんとですね･･･　修正しました！

2022-01-07 19:11 UTC, Hiroshiba commented on .github/workflows/build.yml
>              VOICEVOX_CORE_EXAMPLE_VERSION=${{ matrix.voicevox_core_example_version }}
気づいてくださってありがとうございます！！

2022-01-07 21:57 UTC, aoirint commented on .github/workflows/build.yml
>              VOICEVOX_CORE_EXAMPLE_VERSION=${{ matrix.voicevox_core_example_version }}
よさそうです！

警告が出なかったのは、Dockerfile側でARGのデフォルト値を指定しているからだと思いました！

2022-01-07 22:05 UTC, aoirint commented on .github/workflows/build-docker.yml
> +            VOICEVOX_CORE_SOURCE_VERSION=${{ env.VOICEVOX_CORE_SOURCE_VERSION }}
DockerfileにもPythonバージョンを指定するARGがあるので、`env`に追加しておくとよさそうです。

```yaml
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
```

`VOICEVOX_RESOURCE_VERSION`も追加したいですが、いまのところ、Dockerイメージの話者リソースにはダミーが使われていた（#180 での変更漏れ？）と思うので、別PRかもです。

2022-01-07 22:43 UTC, aoirint reviewed
気づいたところコメントしてみました。

2022-01-07 22:43 UTC, aoirint commented on .github/workflows/build-docker.yml
> +  VOICEVOX_CORE_VERSION: '0.10.preview.0'
`build-docker`ジョブの下にある`env.IMAGE_NAME`も、`build.yml`と同じようにグローバルなenvに移してもいいかもです。

```yaml
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/voicevox_engine
```

2022-01-07 22:43 UTC, aoirint commented on .github/workflows/build-docker.yml
> +
`VOICEVOX_RESOURCE_VERSION`も追加したいですが、いまのところ、Dockerイメージの話者リソースにはダミーが使われていた（#180 での変更漏れ？）と思うので、別PRかもです（Dockerfile内に製品版リソースを展開する処理を書く）。

2022-01-07 22:43 UTC, aoirint commented on .github/workflows/build-docker.yml
> +            VOICEVOX_CORE_SOURCE_VERSION=${{ env.VOICEVOX_CORE_SOURCE_VERSION }}
DockerfileにもPythonバージョンを指定するARGがあるので、`env`に追加しておくとよさそうです。

```yaml
env:
  PYTHON_VERSION: '3.8'
```

```yaml
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
```

2022-01-07 22:56 UTC, aoirint commented on .github/workflows/build-docker.yml
> +
#278 でIssue化しました。

2022-01-07 23:03 UTC, Hiroshiba commented on .github/workflows/build-docker.yml
> +  VOICEVOX_CORE_VERSION: '0.10.preview.0'
移しました！　１つのjobからしか使われていないから別にlocalでも良かったかもとちょっと思いました

2022-01-07 23:05 UTC, Hiroshiba commented on .github/workflows/build-docker.yml
> +
issue化ありがとうございます！　とりあえずこのPRでは放置しちゃおうと思います。

2022-01-07 23:08 UTC, Hiroshiba commented on .github/workflows/build-docker.yml
> +            VOICEVOX_CORE_SOURCE_VERSION=${{ env.VOICEVOX_CORE_SOURCE_VERSION }}
追加しました！

2022-01-07 23:40 UTC, aoirint approved these changes
LGTM！

2022-01-08 00:47 UTC, PickledChair requested changes
ほぼ良さそうだったのですが、一部議論が必要そうな部分があったのでコメントしました。

2022-01-08 00:47 UTC, PickledChair commented on .github/workflows/build.yml
>              ONNXRUNTIME_URL=${{ matrix.onnxruntime_url }}
build-docker.yml での https://github.com/VOICEVOX/voicevox_engine/pull/276/files#r780557011 の場合と同じように、`build-args` に

```
PYTHON_VERSION=${{ env.PYTHON_VERSION }}
```

を追加した方が良さそうだと思いました。

ただ、build-docker.yml の方は `PYTHON_VERSION: '3.8.12'` とパッチバージョンまで指定しており、Dockerfile 内のデフォルト値も `ARG PYTHON_VERSION=3.8.10` とやはりパッチバージョンまで指定しています。

一方で、build.yml では `PYTHON_VERSION: '3.8'` のようにマイナーバージョンまでの指定です。

Dockerfile 内では Python のビルドに pyenv の python-build を使っていると思うので、パッチバージョンまで指定しないとエラーが出そう？ と思いました。

なので選択肢としては、

- `build.yml` では `build-args` で `PYTHON_VERSION` を指定しない
- `build.yml` でも `build-args` で `PYTHON_VERSION` を指定する。加えて、`env.PYTHON_VERSION` を `3.8.12` のようにパッチバージョンまで指定する

のどちらかになると思います。

2022-01-08 01:04 UTC, Hiroshiba commented on .github/workflows/build.yml
>              ONNXRUNTIME_URL=${{ matrix.onnxruntime_url }}
なるほどです、指定できたほうが良さそうに感じたので後者の方を実装してみます！

2022-01-08 01:10 UTC, Hiroshiba commented
修正し、ついでに3.8.12を用いていることをREADMEでもわかるようにしてみました。

2022-01-08 01:19 UTC, PickledChair commented
ビルドが落ちたので変だなと思い https://github.com/VOICEVOX/voicevox_engine/runs/4745476938?check_suite_focus=true を確認しました。

どうも `actions/setup-python@v2` では Windows 向けの Python 3.8.12 がサポートがないようです（エラーメッセージ中にあった https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json で各バージョンのサポート状況が確認できます）。3.8 系の中で Windows でも利用可能な一番新しいバージョンは 3.8.10 のようです。おそらくこれまではこれが自動で選択されていたのではと推測しています。3.8.10 に変更した方が良さそうですが、どうでしょうか？

2022-01-08 01:22 UTC, Hiroshiba commented
なるほどです。3.8.10で良い気がするので修正してみます！

2022-01-08 01:30 UTC, PickledChair approved these changes
LGTM !

2022-01-08 01:34 UTC, merged