Feature/specfied CPU Threads
VOICEVOX/voicevox_engine pull request #286
Opened 2022-01-13 09:28 UTC by AsPulse

## 内容

実行時引数または環境変数から値を得て、Coreに渡します。

### 不安があるところ
```py
core.initialize(voicelib_dir.as_posix() + "/", use_gpu, cpu_num_threads)
```
この処理は、「Core側がcpu_num_threadsを受け取る前のバージョン」だった場合に大丈夫なのでしょうか...？
CoreとEngineがセットで提供されない場合、引数を受け取れるかどうかのアサーションが必要かもしれませんが、思いつきませんでした。

## 関連 Issue

ref #282

2022-01-13 09:40 UTC, AsPulse commented
現在、requirements-test.txtをインストールしたところ、
```bash
ERROR: Failed building wheel for pyopenjtalk
Failed to build pyopenjtalk
ERROR: Could not build wheels for pyopenjtalk which use PEP 517 and cannot be installed directly
```
というエラーが出てしまいコードの検証が不可能な状態で今はDraftとしております。

この現象の解決法がわかる方 / 代わりにコードの確認をして頂ける方がいらっしゃったら教えて頂けると嬉しいです。

2022-01-13 11:06 UTC, y-chan approved these changes
LGTMです。

> 「Core側がcpu_num_threadsを受け取る前のバージョン」だった場合に大丈夫なのでしょうか...？

今はこれを考慮する必要はないと思います(開発者は、ほとんどの場合において最新版を使用すると思うので)
また、 #254 もあるので、このPR内で気にする必要はないかなと思いました...!

2022-01-13 13:14 UTC, takana-v reviewed
>この処理は、「Core側がcpu_num_threadsを受け取る前のバージョン」だった場合に大丈夫なのでしょうか...？

#254 で対応したいと思います。
（マージされ次第作業したいと思います）

2022-01-13 13:14 UTC, takana-v commented on voicevox_engine/synthesis_engine/make_synthesis_engine.py
> +        )
他の所では標準エラー出力に出力しているので合わせた方がいいかもと思いました。

```suggestion
        print(
            "Warning: cpu_num_threads is set to 0. "
            + "( The library leaves the decision to the synthesis runtime )",
            file=sys.stderr,
        )
```

2022-01-13 13:14 UTC, aoirint requested changes
run.pyで`make_synthesis_engine`に`cpu_num_threads`を渡し忘れている気がします！

CancellableEngineでも`make_synthesis_engine`を呼んでいるので、そちらも対応しておくとよさそうに思いました。

2022-01-13 13:37 UTC, AsPulse commented on voicevox_engine/synthesis_engine/make_synthesis_engine.py
> +        )
ありがとうございます！修正しました

2022-01-13 13:41 UTC, takana-v approved these changes

2022-01-14 06:39 UTC, aoirint approved these changes
LGTM！

2022-01-14 06:40 UTC, merged