対応デバイスが分かるAPIエンドポイントを追加
VOICEVOX/voicevox_engine pull request #299
Opened 2022-01-24 17:18 UTC by takana-v

## 内容

コアがCPU/GPUモードに対応しているかを返すエンドポイント`/supported_devices`を追加します。

## 関連 Issue

close #246 
- #246 

## その他

#254 の変更が含まれていますので、release-0.10へは含めないようにお願いします。

2022-01-25 13:34 UTC, Hiroshiba reviewed
含めない旨了解です！

2022-01-25 13:34 UTC, Hiroshiba commented on run.py
> +    @app.get("/supported_devices", response_model=List[Speaker], tags=["その他"])
`response_model`の値がおかしい・・・かも？

2022-01-25 13:44 UTC, takana-v commented on run.py
> +    @app.get("/supported_devices", response_model=List[Speaker], tags=["その他"])
response_modelの存在を忘れていました...
とりあえず手元では`{"cpu": bool, "cuda": bool}`の形だったので、それに合わせて追記しました。

2022-01-27 10:32 UTC, PickledChair requested changes
気になった点についてコメントしました！

2022-01-27 10:32 UTC, PickledChair commented on run.py
> +        supported_devices = get_engine(core_version).supported_devices
`get_engine(core_version).supported_devices` という書き方から、「 `SynthesisEngineBase` を継承したクラスのインスタンスは `supported_devices` というプロパティを持っている」ことを期待しているように感じました。なので、抽象基底クラス `SynthesisEngineBase` に以下のように抽象プロパティ `supported_devices` を定義し、`SynthesisEngine` や `MockSynthesisEngine` クラスでそれをオーバーライドした方が良い気がしました。

```python
class SynthesisEngineBase(metaclass=ABCMeta):
    ...
    @property
    @abstractmethod
    def supported_devices(self) -> Optional[str]:
        raise NotImplementationError()
    ...
```

2022-01-27 14:36 UTC, takana-v commented on run.py
> +        supported_devices = get_engine(core_version).supported_devices
現在実装されているspeakers情報に合わせて書きましたが、確かに`SynthesisEngineBase`で抽象プロパティを書いた方が良いように思いました。
speakersも合わせて変更しようかと思います。

2022-01-27 14:39 UTC, takana-v commented on test/test_mock_synthesis_engine.py
> +        self.engine = MockSynthesisEngine(speakers="", supported_devices="")
現在のテストでは、speakersが空文字列だったのでそれに合わせて書きました。
（私もcore.metas()やcore.supported_devices()の結果の方が自然だと思います）

2022-01-27 15:09 UTC, takana-v commented on run.py
> +        supported_devices = get_engine(core_version).supported_devices
試してみましたが、以下のように書く必要があるみたいです。
ちょっと冗長になりますね...

```python
class SynthesisEngine(SynthesisEngineBase):
    def __init__(self, ...):
        self._supported_devices = supported_devices

    @property
    def supported_devices(self) -> Optional[str]:
        return self._supported_devices
```

2022-01-28 15:19 UTC, takana-v commented on run.py
> +        supported_devices = get_engine(core_version).supported_devices
https://github.com/VOICEVOX/voicevox_engine/pull/299/commits/07bff95d02236667ef7edef3bbd01045f473b0dd で変更しました。

2022-01-28 16:07 UTC, PickledChair approved these changes
LGTM！

2022-02-01 13:20 UTC, Hiroshiba commented on voicevox_engine/synthesis_engine/synthesis_engine.py
> +        supported_devices: coreから取得した対応デバイスに関するjsonデータの文字列
おそらくNoneのときに意味を持っている設計だと思うので、その説明があると良いのかなと思いました。
（Noneのときはすべてのデバイスでサポートしているか不明です、みたいな）

2022-02-01 13:22 UTC, Hiroshiba requested changes
良さそうです！！
皇族の方にわかりやすいよう、コメントとドキュメント追加をお願いしたいです･･･！

2022-02-03 23:02 UTC, Hiroshiba approved these changes
LGTM！！

2022-02-03 23:02 UTC, merged