readmeに過去のバージョンのコアの使用方法を追記
VOICEVOX/voicevox_engine pull request #300
Opened 2022-01-24 17:50 UTC by takana-v

## 内容
題の通り

## 関連 Issue
close #298 
- #298 
- ref #236

## その他

#254 の変更が含まれていますので、release-0.10へは含めないようにお願いします。

2022-01-27 11:08 UTC, PickledChair requested changes
Mac の場合は記載の方法では起動できないので、それについてコメントしました（Mac では未サポートとするという話もあった気がしたので、Mac についてはあえて何も書かない、というのもありなのかもしれませんが、一応言及しました……）。

また、これはメモなのですが、 https://github.com/VOICEVOX/voicevox_core/pull/70 で Mac 版のコアライブラリのファイル名が `libcore_cpu_x64.dylib` から `libcore_cpu_universal2.dylib` に変わったので、Mac ではプレビュー版のコア（ `0.10.preview.*` ）が使用できなくなりました。これらのコアのサポートを切ると仮定して、README でそれに言及すべきかどうか少し迷うところだと感じました……。

2022-01-28 15:28 UTC, PickledChair approved these changes
LGTM！

2022-02-01 13:47 UTC, Hiroshiba commented on README.md
> +#### ライブラリを直接指定する
pip installで入る方のライブラリと勘違いするかもなので、他の箇所の語句に合わせて「音声ライブラリ」が良いのかなと思いました！

```suggestion
#### 音声ライブラリを直接指定する
```

2022-02-01 13:49 UTC, Hiroshiba approved these changes
LGTM！！！

2022-02-01 13:49 UTC, merged