ユーザ辞書機能の追加
VOICEVOX/voicevox_engine pull request #301
Opened 2022-01-25 18:25 UTC by takana-v

## 内容

ユーザ辞書機能を追加します。
`user_dict.json`に内容が保存されます。（run.exe直下に作られます）
（製品版ボイボでアップデート時に上書きされないようにする必要があります）

## 関連 Issue

- https://github.com/VOICEVOX/voicevox_project/issues/6

2022-01-25 19:03 UTC, Hiroshiba commented
> 製品版ボイボでアップデート時に上書きされないようにする必要があります

こちら、ちょっと問題になりそうですね･･･！
エディタ側のconfigファイルと同様ユーザーディレクトリ？に保存するのが良いのかなと思いました。

解決しちゃうか、エンジン側にissue化するか、 https://github.com/VOICEVOX/voicevox_project/issues/6 にTODOとしてチェックリストを追加するかお願いしたいです！

2022-01-26 13:45 UTC, takana-v commented
製品版ボイボのフォルダに保存しようかと思ったのですが、エンジンだけ起動する可能性があったり、そもそもフォルダが分からない（voicevox、voicevox-cpu、voicevox-devのどれか）ので新しいフォルダに保存することにしました。

windows: `Appdata\Roaming\voicevox-engine`
Linux&Mac: `~/.voicevox-engine`（未テスト）

これらのフォルダ内に`user.dic`および`user_dic.jsonが保存されます。
これに伴い、リポジトリからコンパイル済み辞書を削除しました。

2022-01-26 14:41 UTC, Hiroshiba commented
> 製品版ボイボのフォルダに保存しようかと思ったのですが、エンジンだけ起動する可能性があったり、そもそもフォルダが分からない（voicevox、voicevox-cpu、voicevox-devのどれか）ので新しいフォルダに保存することにしました。

たしかに・・・！！
ディレクトリが一緒だったほうが良いのか、別れてたほうが良いのかはちょっとわかりませんが、エンジン側的にはどっちでも良さそうです。
ディレクトリを一緒にする手として、エンジン起動時の引数でディレクトリを受け取れるようにしておく手を思いつきました。

書き込むべきディレクトリはOSによって変わってくるので、ライブラリに頼るのが良さそうに感じました。
appdirsとかがあるっぽいです。 https://pypi.org/project/appdirs/

2022-01-26 17:12 UTC, takana-v commented
appdirsを用いるように変更しました。

2022-01-26 18:44 UTC, takana-v commented
REST APIに沿った返答に変更しました。
- Response: 204 -> 成功
- Response: 422 -> 失敗

2022-02-01 12:16 UTC, Hiroshiba requested changes
軽く見てみました！！

2022-02-01 12:16 UTC, Hiroshiba commented on voicevox_engine/model.py
> +                    "(?:[アイウエオカ-モヤユヨ-ロワ-ヶ][ァィゥェォャュョヮ]|[アイウエオカ-モヤユヨ-ロワ-ヶー])",
っ　や濁音などが含まれても正しく動くかのテストが欲しいかもです

2022-02-01 12:16 UTC, Hiroshiba commented on voicevox_engine/user_dict.py
> +# nuitkaビルドをした際はグローバルに__compiled__が含まれる
ここ何度か見たのでそろそろ関数化しても良いかもと思いました。
file managerモジュールとか、utilityとか…？

2022-02-01 12:16 UTC, Hiroshiba commented on voicevox_engine/user_dict.py
> +        with default_dict_path.open(encoding="utf-8") as f2:
ちなみに.read_textみたいな便利メソッドがあったはず

2022-02-01 12:16 UTC, Hiroshiba commented on voicevox_engine/user_dict.py
> +        raise RuntimeError("辞書のコンパイル時にエラーが発生しました。古い状態のユーザ辞書が適用されます。")
あれ、古い方の再適用がされてないかも？

2022-02-01 12:16 UTC, Hiroshiba commented on voicevox_engine/user_dict.py
> +    with _user_dict_path.open(encoding="utf-8", mode="w") as f:
ちなみにwrite_textという便利メソッドが。

2022-02-01 12:16 UTC, Hiroshiba commented on run.py
> +    def update_user_dict(surface: str, pronunciation: str, accent_type: int):
この命名だと、単語追加はadd_user_dictとかになるので単位が分かりづらくなる気がしました。
やってることは単語updateでしょうか。
用語はopenjtalkにあわせておくと混乱がなさそうだなと思いました。word？

2022-02-03 13:16 UTC, takana-v commented on voicevox_engine/user_dict.py
> +        raise RuntimeError("辞書のコンパイル時にエラーが発生しました。古い状態のユーザ辞書が適用されます。")
90行目は辞書ファイルが見つからないので再適用できない状態です。
93行目は91行目で再適用されています。
（辞書ファイルのハッシュ値が同じ→エラーが起きて辞書が古いまま）

2022-02-03 13:17 UTC, takana-v commented on voicevox_engine/user_dict.py
> +# nuitkaビルドをした際はグローバルに__compiled__が含まれる
utility辺りに`engine_root()`みたいな形でエンジンのルートディレクトリ（run.exeがある場所）を返す関数を作ろうかと思います。

2022-02-03 14:02 UTC, takana-v commented
モーラ数の計測にミスがあったので（`ぁ`など）修正していたところ気になった事があったので質問です。
`pyopenjtalk.g2p`と`parse_kana`の結果が食い違うことがあります。
（エディタで新しいセルに打ち込んだ場合は前者が、読み修正の時は後者が使われます）
`くゎ`の結果が、g2pでは`k u`、parse_kanaでは`kw a`となります。
[ゎ - Wikipedia](https://ja.wikipedia.org/wiki/%E3%82%8E)
どちらが正しそうでしょうか？
@Hiroshiba

2022-02-03 14:17 UTC, Hiroshiba commented
なるほど、モーラ数が変わるのはバグにつながりそうですね…
OjtPhonemeの中に含まれている音素であれば、基本openjtalkに従っておきたいです。
ということでkw aにしたいところです…！

2022-02-03 23:13 UTC, Hiroshiba commented on voicevox_engine/user_dict.py
> +        raise RuntimeError("辞書のコンパイル時にエラーが発生しました。古い状態のユーザ辞書が適用されます。")
なるほどです！
ちょっとロジックがややこしいかもと感じました。
hashを取らない方法もありそうです。
別のファイルに出力しようとして、出力に成功したらrenameする方法はどうでしょう。

2022-02-05 09:16 UTC, takana-v commented on voicevox_engine/user_dict.py
> +        raise RuntimeError("辞書のコンパイル時にエラーが発生しました。古い状態のユーザ辞書が適用されます。")
そのように変更しました。
ただ、今は他のエンジンも同じフォルダを使用することになるので、上書き時にエラーが発生する可能性があります。
EngineIDなどの策定が済んだらそちらにフォルダ名を変更したいです。

2022-02-05 12:38 UTC, Hiroshiba approved these changes
LGTM！！！

なかなか複雑めですね･･･！
@aoirint さんか @y-chan さんもレビュー頂けると！！

2022-02-20 08:51 UTC, y-chan approved these changes
LGTMです！！
apiのパスも、REST APIを意識した感じで、今後削除等が増えてもいい感じになりそうだと思いました！

このままマージしても大丈夫そうですが、一点だけ、気になったのでコメントしてみました。

2022-02-20 08:51 UTC, y-chan commented on voicevox_engine/user_dict.py
> +                    word.accent_associative_rule,
可読性の観点から、fstringにした方が良いと思いましたが、何か意図があるのでしょうか?

2022-02-20 09:13 UTC, takana-v commented on voicevox_engine/user_dict.py
> +                    word.accent_associative_rule,
fstringだと1行が長すぎになり、3重引用符を使うとコードが冗長になると思ってフォーマットにしました。

2022-02-20 10:25 UTC, Hiroshiba commented on voicevox_engine/user_dict.py
> +                    word.accent_associative_rule,
個人的にはどっちでも全然読めそうに感じました･･･！

2022-02-20 10:26 UTC, Hiroshiba commented
マージします。待望の機能ですね･･･！

2022-02-20 10:26 UTC, merged