疑似疑問文化をsynthesis APIの直前に移動
VOICEVOX/voicevox_engine pull request #310
Opened 2022-01-27 15:43 UTC by Yosshi999

## 内容
Mora追加による疑似疑問文化を音声合成の直前部に移動した。
synthesis系のAPI(`/synthesis, /cancellable_synthesis, /multi_synthesis, /synthesis_morphing`)に影響

## 関連 Issue
ref. #272 
https://github.com/VOICEVOX/voicevox_engine/issues/272#issuecomment-1022610866

## スクリーンショット・動画など

## 懸念点
疑似疑問文化がいい感じにならなかったときユーザーによる語尾音高の調整が出来なくなった

2022-01-27 15:46 UTC, Yosshi999 commented
#309 未検証

2022-01-27 16:08 UTC, takana-v requested changes
- #309 
上のIssueのバグに関してです。

2022-01-27 16:08 UTC, takana-v commented on run.py
> +            return accent_phrases
`parse_kana()`で疑似疑問文化が行われてしまうと思います。
`parse_kana()`ではアクセント句の`is_interrogative`フラグを立てるだけにするようにすると良いかと思います。

2022-01-27 18:13 UTC, Hiroshiba commented on run.py
> +            return accent_phrases
自分も確認しました。↓の行がまるまる要らないはずです･･･！
https://github.com/Yosshi999/voicevox_engine/blob/266c82cd400791be9e21b51affaae3ee6b9a6899/voicevox_engine/kana_parser.py#L118-L127

2022-01-28 10:50 UTC, Yosshi999 commented on run.py
> +            return accent_phrases
む、見落としてました

2022-01-28 13:01 UTC, Hiroshiba commented
おっと、未使用importがある関係でテストが落ちていますね･･･
でもそれ以外は大丈夫そうなのでマージしちゃいます！

こちらはrelease-0.10ブランチにマージさせていただきます！

2022-01-28 13:02 UTC, merged