ユーザー辞書機能：単語の更新/削除機能を追加
VOICEVOX/voicevox_engine pull request #338
Opened 2022-02-21 11:29 UTC by takana-v

## 内容

題の通り

## 関連 Issue

- https://github.com/VOICEVOX/voicevox_project/issues/6

## その他
https://github.com/VOICEVOX/voicevox_engine/pull/334#discussion_r810622369
こちらの変更も一緒に行っています。
また、重複している処理があったので削除しています。（jsonへ2回書き込んでいた）

2022-02-24 10:04 UTC, y-chan reviewed
良さそうだと思いました！
一点だけ、テストに関して気になったので、コメントしておきます。

2022-02-24 10:04 UTC, y-chan commented on test/test_user_dict.py
> +        )
applyするだけでなく、applyしたものがちゃんと動作しているか、結果比較等した方がテストとしては良さそうだと思いました。(`rewrite_word`の方ではちゃんとされているようなので、`apply_word`の方でもやって貰えると...!)

2022-02-25 09:36 UTC, y-chan approved these changes
LGTMです！
これでエディタ側の実装にフェーズに移行できそうですね...!

2022-02-25 15:14 UTC, Hiroshiba requested changes
きれいに感じました！！

RESTっぽくするためにも、`/id`のとこだけ変更して頂けると･･･！

2022-02-25 15:14 UTC, Hiroshiba commented on run.py
> +    ):
idはURLパラメータ？にするのがよくある方法っぽいです
https://restfulapi.net/rest-put-vs-post/

2022-02-25 15:14 UTC, Hiroshiba commented on run.py
> +    def delete_user_dict_word(id: int):
同上です

2022-02-25 15:14 UTC, Hiroshiba commented on test/test_user_dict.py
> +        "0": {
IDはintなんでしたっけ、stringなんでしたっけ

2022-02-25 15:14 UTC, Hiroshiba commented on test/test_user_dict.py
> +    "next_id": 1,
将来辞書エディターみたないなのが出たりしたとき、`next_id`の数値と、word idがずれてしまう未来が見えました。
uuidにしても良いかも？

2022-02-25 15:15 UTC, Hiroshiba approved these changes
LGTM！！！

初学者の方がPUTやDELETEの使い方をわからない可能性があるかもなので、READMEにcurlでの例があるとちょっとやさしいのかなと思いました。
（あっても間違っちゃうかもですが）

2022-02-25 15:16 UTC, merged