ユーザー辞書機能：コストのパーセンタイルを追加
VOICEVOX/voicevox_engine pull request #357
Opened 2022-03-03 09:48 UTC by takana-v

## 内容

ユーザ辞書のコストのパーセンタイルのデータを追加します。
実際にパーセンタイル値を使えるようにAPIを変更するのは別PRで行います。

## 関連 Issue

- https://github.com/VOICEVOX/voicevox_project/issues/6

2022-03-03 09:50 UTC, takana-v commented on voicevox_engine/part_of_speech_data.py
> +        part_of_speech_detail_2="*",
前PRで誤りがあったので修正しています。

2022-03-03 09:50 UTC, takana-v commented on voicevox_engine/part_of_speech_data.py
> +        cost_percentile=[-987, 3488, 3646, 3658, 3659, 3659, 3659, 3659, 3659, 4045, 6921, 6921, 6921, 6921, 6921, 6921, 7260, 7664, 8197, 8440, 8573, 8607, 8609, 8609, 8609, 8609, 8609, 8609, 8609,
フォーマットすると逆に見づらくなると思ったので自動フォーマットを切っています。

2022-03-03 11:12 UTC, y-chan commented
軽く見たのですが、`get_percentile.py`は実際の辞書からコストの一覧を取得し、パーセンタイルを生成するスクリプトという認識であっているでしょうか？
意図がちょっとわかりにくい気がしたので、ファイルの先端にコメントを書き、意図を記述しておくのが良いかと思いました。

また、パーセンタイルをAPIでどのように扱うかがちょっと気になっています。
例えば、エディタ側では1～10の優先度といった扱いになりそうですが、パーセンタイルの各値がかなり重複しているものもみられるので優先度を1(内部処理的には100分の10)上げたとしても違いを感じられない(使われている値的にも違いがない)といったことが起きそうな気がしています。

そんな感じのことがOpenJTalkのことがわからないながらに気になったぐらいで、あとはLGTMでした！

2022-03-03 13:36 UTC, takana-v commented
> 優先度を1(内部処理的には100分の10)上げたとしても違いを感じられない

確かに自分も気になっています。
`最小値 + （最大値 - 最小値）* （優先度 / 100）`（優先度は0～100）
とかで計算すればよさそうでしょうか...？
（外れ値を排除する必要がありそうですが）

2022-03-03 15:38 UTC, Hiroshiba requested changes
たしかにパーセンタイルは相性が悪そうですね･･･
そもそもどういう分布にするのが正解なのかわからない。。

まあ、１００段階あっても使わない人が大半かもと思いました。
全品詞まとめてcostの一覧を作って、１０分率くらいにすれば値はバラけそうでしょうか。
もしそれでバラけるなら、その１０段階だけ用意するというのはどうでしょう👀

外れ値が気になるのもとても同感です。-4444とか強すぎる。
･･･12分率にして最初と最後は省く、とか･･･？

2022-03-03 15:38 UTC, Hiroshiba commented on voicevox_engine/part_of_speech_data.py
> +        cost_percentile=[-987, 3488, 3646, 3658, 3659, 3659, 3659, 3659, 3659, 4045, 6921, 6921, 6921, 6921, 6921, 6921, 7260, 7664, 8197, 8440, 8573, 8607, 8609, 8609, 8609, 8609, 8609, 8609, 8609,
jsonとかでファイルで持っておくのも良いかなと感じました。
（さすがにコード内に１００要素の配列があるのはメンテナンス性が下がってしまうかも）

2022-03-03 15:38 UTC, Hiroshiba commented on get_percentile.py
> +import argparse
y-chanさんと同感で、最初にコメントで何なのかがあるとわかりやすそうに感じました！

2022-03-03 17:53 UTC, takana-v commented
固有名詞の12分割から最初と最後を省くとこのようになりました。
`[4214 8264 8609 8609 8609 8609 8609 8609 8609 8609]`
全品詞の12分割から最初と最後を省くとこのようになりました。
`[4449 5746 6537 6962 6962 7358 7756 8251 8562 8562]`

品詞ごとにコストの分布に差があるのでできればそれを再現したかったのですが難しそうですね...
全品詞のものでも値が被っているのが気になります。

単純に一次関数的に値を設定するのもあまりよくない気がします。
最低値、中央値、最高値が元のパーセンタイルの10％、最頻値、90％の値になるようにいい感じに手動で値を設定するのがよさそうでしょうか...？

2022-03-03 18:09 UTC, Hiroshiba commented
かぶってますね・・・

> 最低値、中央値、最高値が元のパーセンタイルの10％、最頻値、90％の値になるようにいい感じに手動で値を設定するのがよさそうでしょうか...？

おお、なるほどです！！
なんか適当に、こう、1/2倍していきますか。。
パーセンタイルで`50 25 12.5 6.25 3.125 1.56`みたいな･･･

あ、最優先として、文字通り他のすべてよりcostが小さいものを用意するとニーズに合うのかなと感じました。
なので最低コスト-1、最高コスト+1のも一応用意しておくというのはどうでしょう。
（日本語がぶっ壊れそうですが･･･）

2022-03-05 05:10 UTC, takana-v commented
> パーセンタイルで50 25 12.5 6.25 3.125 1.56みたいな･･･

やってみたらこんな感じになりました。（固有名詞）
`return [np.quantile(costs, 1/2**i).astype(np.int64) for i in range(1,11)]`
`[8609, 8609, 6921, 3659, 3658, 3628, 3278, 698, 698, 698]`

これでも値がバラけないですね...

とりあえず1%～最頻値～99%で作ってみたものです。
```python
cost_min = min(costs) - 1
cost_1per = np.quantile(costs, 0.01).astype(np.int64)
cost_mode = statistics.mode(costs)
cost_99per = np.quantile(costs, 0.99).astype(np.int64)
cost_max = max(costs) + 1
return (
    [cost_min]
    + [int(cost_1per + (cost_mode - cost_1per) * i / 5) for i in range(1, 6)]
    + [int(cost_mode + (cost_99per - cost_mode) * i / 5) for i in range(1, 6)][1:]
    + [cost_max]
)
```
`[-988, 4512, 5536, 6560, 7584, 8609, 8809, 8909, 9009, 9110, 14176]`

2022-03-05 14:48 UTC, Hiroshiba commented
> [-988, 3488, 4768, 6048, 7328, 8609, 8734, 8859, 8984, 9110, 14176]

良さそうです！！
実際に使ってみて、感覚がずれてそうだったらまた修正を検討するのが良さそうに感じました！

2022-03-06 10:56 UTC, Hiroshiba commented on get_percentile.py
> +cost_percentileの値の詳細は以下の通りです。
とても細かいのですが、cost_percentileという名前だと語弊があるかもです。
（modelでも使われている名称なので今のうちに変えておきたいなと）

なんだろう･･･　コストの候補（cost_candidates）･･･？

2022-03-06 10:57 UTC, Hiroshiba requested changes
ファイル説明文とてもわかりやすかったです！
１点だけコメントしてみました。

2022-03-06 13:15 UTC, takana-v commented on get_percentile.py
> +cost_percentileの値の詳細は以下の通りです。
他にいい感じの名前が思い浮かばなかったので、`cost_candidates`にリネームしました。

2022-03-06 14:31 UTC, Hiroshiba approved these changes
LGTM！！

2022-03-06 14:31 UTC, merged