WindowsのCPUビルドをDirectMLビルドで置き換える
VOICEVOX/voicevox_engine pull request #367
Opened 2022-03-14 18:23 UTC by y-chan

## 内容

題の通りです。これにより、成果物の名前が`windows-directml`になります。
よって、エディタのビルド側も対応が必要です(私の方で対応する予定です)。

## 関連 Issue

ref #363

2022-03-14 19:37 UTC, Hiroshiba reviewed
おお！！早速のプルリクエスト、感謝です！！

ちょっと運用面でのお願いなのですが、一旦cpu版をdirectml版に置き換えるのではなく、directml版を足す感じでお願いできると助かります！！

理由は単純で、アプデが入って仮にdirectml版に未知の不調が発生した時に、cpu版をすぐ案内できるようにしたいためです。
安定が確かめられればcpu版は削除するか再検討できればと思います！

2022-03-15 00:33 UTC, y-chan commented
確かに、完全に置き換えるのは危険ですね...
修正しておきます

2022-03-15 15:02 UTC, y-chan commented
ビルド出来たので、どなたかお試しいただければと思います。
https://github.com/y-chan/voicevox_engine/releases/tag/directml-test

2022-03-17 15:57 UTC, Hiroshiba commented
試してみたいと思います！
（ビルドは追加になったのでタイトル変更させていただきました）

2022-03-17 16:07 UTC, Hiroshiba commented
Nvidia GPUで動くことを確認しました！ちゃんとCPUより早くなっていそうでした･･･！

2022-03-17 16:42 UTC, Hiroshiba approved these changes
LGTM！！

実際にビルドできているのでマージしちゃって大丈夫そうですが、もしよかったら @aoirint さんか @PickledChair さんも見て頂けると･･･！

2022-03-23 17:14 UTC, Hiroshiba commented
こちらマージしちゃいたいですね･･･！！
もうちょい時間経ったらもうマージしちゃおうと思います :pra

2022-03-23 18:02 UTC, PickledChair requested changes
もしかしてこの箇所は変更忘れでしょうか？（`python_architecture` -> `architecture`。すみません、コメントが付けられない範囲だったのでここに書きました。）

https://github.com/y-chan/voicevox_engine/blob/4c143dd9f6167c0e9a801d423ec0a51f0b97a30a/.github/workflows/build.yml#L369

（すみません、まだ見れていない部分があるのでもう少しお待ちください……）

2022-03-24 04:12 UTC, y-chan commented
確かに、変更し忘れですね...!
直しておきました...!

それと、conflictが発生していたので、rebaseしておきました。

2022-03-24 04:16 UTC, PickledChair approved these changes
LGTM！ マージします。

2022-03-24 04:17 UTC, merged