エンジンのマニフェストを追加
VOICEVOX/voicevox_engine pull request #387
Opened 2022-04-14 16:10 UTC by takana-v

## 内容

SynthesisEngineに情報を持たせることも検討しましたが、run.pyに持たせるようにしました。
base_info.jsonにversion、name、サンプリングレートを書いておき、残りの項目を各ファイルで上書きするようにしました。
（version.txt、name.txtと別々にするとファイル数多くなると思ったのでこのようにしました。）

## 関連 Issue

- https://github.com/VOICEVOX/voicevox_engine/issues/362

## その他
とりあえずマージまで必要な作業を羅列しておきます。
- [ ] マニフェストの様式を正式に決定
- [ ] VVRにマニフェストのリソースを追加
- [ ] ビルド周り修正

2022-05-02 17:47 UTC, Hiroshiba commented
> マニフェストの様式を正式に決定
> VVRにマニフェストのリソースを追加

こちら、とりあえずなくてもマージ可能なので、先にマージしてしまって並行して進めても良いのかなと思いました！

2022-05-02 17:58 UTC, Hiroshiba requested changes
ほぼLGTMです･･･！！

2022-05-02 17:58 UTC, Hiroshiba commented on manifest_assets/base_info.json
> +    "manifest_version": "1.0.0",
結構変わりえそうなので、一旦今のバージョン（`0.12.0`とか）を入れておくというのはどうでしょう 👀

2022-05-02 17:58 UTC, Hiroshiba commented on run.py
> +from voicevox_engine.engine_manifest import EngineManifestLoader
他のクラスはついてないので、短くするために`Engine`なくても良いかも？（あまり強い意見じゃないです）

2022-05-02 17:58 UTC, Hiroshiba commented on voicevox_engine/engine_manifest/EngineManifest.py
> +from typing import List, Optional
これはmodel.pyに置いておいて、Loaderからimportするのが良いのかなと感じました。
（Synthesisとかでもそうなように https://github.com/VOICEVOX/voicevox_engine/blob/243ef5d8ca8460110938f2045f90563a4b016dd6/voicevox_engine/synthesis_engine/synthesis_engine.py#L18 ）

本当はmanifest用のデータクラスとAPI用のmodelクラス２つを用意するのが良さそうなのですが、converter作るのが少し面倒なので、今はmodel側に集約させている感じになっていそうです。

（ただ今のままでも、engine_manifestにとっては整頓する一方、modelにとっては散らかるという一長一短なので、どちらでも良いかなという気もします）

2022-05-05 07:24 UTC, takana-v commented on voicevox_engine/engine_manifest/EngineManifest.py
> +from typing import List, Optional
似たような構造のPresetがこのようになっていたのでそれに倣いました。
（Presetの型はAPIで直接使わないですが...）

2022-05-05 19:36 UTC, Hiroshiba commented on voicevox_engine/engine_manifest/EngineManifest.py
> +from typing import List, Optional
なるほどです。まあどちらでも良いなと感じました･･･！

2022-05-09 15:40 UTC, Hiroshiba commented
マージします！！

2022-05-09 15:40 UTC, merged