ユーザー辞書操作系の優先度の扱いをpriorityで統一
VOICEVOX/voicevox_engine pull request #391
Opened 2022-05-03 01:18 UTC by y-chan

## 内容

題の通り、json/csvにおいては、`cost`を残さざるを得ない(既存のユーザー辞書が壊れるかもしれない)ので、操作系のみを`priority`で統一しました。
これにより、エディタ側・ユーザーは`priority`という単位以外を意識しなくて済むようになります。

## 関連 Issue

close #390

2022-05-03 11:47 UTC, Hiroshiba requested changes
PR感謝です！！！

辞書周りに詳しい @takana-v さんからもレビュー頂けると心強いです！

そもそもこの変更が必要になった経緯

- https://github.com/VOICEVOX/voicevox_engine/issues/390

2022-05-03 11:47 UTC, Hiroshiba commented on voicevox_engine/user_dict.py
> +            result[str(UUID(word_uuid))] = UserDictWord(**word)
ここってどういうことでしょうか👀
（if文のとこがなくても正常に動作しそうに見えたので）

2022-05-03 11:47 UTC, Hiroshiba commented on voicevox_engine/user_dict.py
> +    return MAX_PRIORITY
一番近いものを返す仕様にすると、`MAX_PRIORITY  - np.argmin(np.abs(np.array(cost_candidates) - cost))`と１行で書けるかもです
https://qiita.com/Krypf/items/2eada91c37161d17621d#11-%E6%9C%80%E3%82%82%E3%82%B7%E3%83%B3%E3%83%97%E3%83%AB%E3%81%AA%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3

2022-05-03 11:47 UTC, Hiroshiba commented on voicevox_engine/user_dict.py
> +            result[str(UUID(word_uuid))] = UserDictWord(**word)
あ、理解しました！　今まではword_typeからcost_candidateなどを得ていましたが、context_idで得るような関数を用意したので、context_idが不正な場合にバグるという感じでしょうか！
であれば、以前と同様に`part_of_speech_data[word_type].cost_candidates`を使うようにすると、一貫性を保ちつつここのif文とコメントもなくせる（複雑度を下げれる）かもと感じました！
https://github.com/VOICEVOX/voicevox_engine/blob/243ef5d8ca8460110938f2045f90563a4b016dd6/voicevox_engine/user_dict.py#L127-L131

@takana-v ちょっと確認したいのですが、word_typeとcontext_idって1:1対応なんでしたっけ👀
であれば`UserDictWord`の`context_id`はdefaultを用意しないほうがミス防止になりそうだなーと！

2022-05-03 15:21 UTC, y-chan commented on voicevox_engine/user_dict.py
> +            result[str(UUID(word_uuid))] = UserDictWord(**word)
0.11.4時点で生成される辞書は以下の形式なっており、`read_dict`実行時に`context_id`が取得できません。
![image](https://user-images.githubusercontent.com/34832037/166482577-919331f3-c77c-4084-a317-f32e5f653707.png)
ここに`context_id`が含まれるようになったのは #355 以降で、すなわち0.12以降となります。
それ以前は品詞が固有名詞(1348)固定だったので、それを補完するようなコードにしています。

今読み返してみたら、コメントがかなり荒くて意味が捉えづらいので、修正してみようと思います。

2022-05-03 17:45 UTC, Hiroshiba commented on voicevox_engine/user_dict.py
> +            result[str(UUID(word_uuid))] = UserDictWord(**word)
なるほどです！！マイグレーションなんですね･･･！

2022-05-05 07:17 UTC, takana-v reviewed
保存ファイルのcostを操作しても最も近いpriorityのcostに上書きされる、という仕様をどこかにコメントしておいた方がいいかもしれないと思いました。
既にレビューされている以外の場所は問題ないと思います。

2022-05-25 07:45 UTC, y-chan commented
大変遅くなりました！
レビューいただいた点をカバーできたと思います。
再レビューいただけると助かります...!

2022-05-27 06:35 UTC, Hiroshiba approved these changes
LGTM！！

お待ちしていました！
1ヶ所だけコメントしました🙏

2022-05-27 06:35 UTC, Hiroshiba commented on voicevox_engine/user_dict.py
>  def write_to_json(user_dict: Dict[str, UserDictWord], user_dict_path: Path):
この関数って何のためにあるか覚えていらっしゃったりしますか。。
（costかpriorityどっち保存した方がいいんだろうなーと）

2022-05-27 08:33 UTC, takana-v commented on voicevox_engine/user_dict.py
>  def write_to_json(user_dict: Dict[str, UserDictWord], user_dict_path: Path):
jsonに書き出す処理が複数個所であったため関数に切り出した記憶があります。
その時はcostで管理していたためjsonにもcostで書き出していました。

2022-05-27 19:50 UTC, Hiroshiba commented on voicevox_engine/user_dict.py
>  def write_to_json(user_dict: Dict[str, UserDictWord], user_dict_path: Path):
あそうか、思い出しました！
辞書をjsonファイルで永続化していて、csvはopenjtalkに与えるときに一時的に作っているだけなんでした。
永続化する（互換性が大事）なので以前同様costが良いですね！

2022-05-27 19:51 UTC, Hiroshiba commented
@y-chan テストが通ってないっぽいです。テスト通り次第マージする予定です！

2022-05-29 02:38 UTC, y-chan commented
テストの方修正しました...!
レビュー・マージお願いします...!

2022-05-29 03:40 UTC, takana-v approved these changes
LGTM！

2022-05-29 03:40 UTC, merged

2022-05-29 12:36 UTC, Hiroshiba commented
preview版エンジンがあると便利そうなのでreleaseしてみました。
https://github.com/VOICEVOX/voicevox_engine/releases/tag/0.12.6-preview