モデルの読み込みを起動時から変更
VOICEVOX/voicevox_engine pull request #400
Opened 2022-05-12 12:50 UTC by takana-v

## 内容
題の通り

## 関連 Issue
- #394

close #394 

## スクリーンショット・動画など

## その他
まだ動作未確認です。
確認し次第上の文を削除します。

2022-05-13 19:16 UTC, Hiroshiba commented
こちら実はもうレビュー可能だったりされますか？👀

2022-05-14 00:41 UTC, takana-v commented
https://github.com/VOICEVOX/voicevox_engine/pull/401#discussion_r872197099
こちらの問題があったのでテストできていません。
#401 のマージ後にお願いします。

2022-05-15 04:04 UTC, PickledChair requested changes
実装自体は全く問題なさそうでした！　ただ、コアの API に渡す引数の型に関してちょっと問題意識・提案を持ったのでコメントしました（もし意図があって現在の型が選択されている場合はスルーしていただければと思います）。

2022-05-15 04:19 UTC, Hiroshiba commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +                self.load_model(speaker_id)
core_wrapperはcoreをラップする（型の変換程度）だけの処理にとどめておくと、wrapperとしての役割がはっきりするかもと思いました。
が、`lazy_init`を移動する先の良い候補が浮かびませんでした。。

↓のあたりのyukarin_sa_forwarderを更にラップする形とかが候補ですが･･･うーーーーん。
https://github.com/VOICEVOX/voicevox_engine/blob/cf1c95e0fc1b2dcfdd3801e29a3bbc3b2d8e7da6/voicevox_engine/synthesis_engine/make_synthesis_engines.py#L72-L93

もしくはengineに関数をもたせるとか･･･？

2022-05-15 04:39 UTC, takana-v commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +            self.core.is_model_loaded.restype = c_bool
別の個所を見るのを忘れていました...suggestionを適用しました。
確かにc_int64に変更する方が良いかもしれません。（問題が発生することは少ないかもしれませんが）
個人的に作っていたコアのラッパーではc_int64で指定していましたが、動作に問題はありませんでした。
https://github.com/takana-v/pyvvcore/blob/master/pyvvcore/core.py#L29-L79

2022-05-15 05:03 UTC, PickledChair commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +                self.load_model(speaker_id)
> core_wrapperはcoreをラップする（型の変換程度）だけの処理にとどめておくと、wrapperとしての役割がはっきりするかもと思いました。

なるほど、自分は一旦 OK と判断しましたが、確かに他のコアの API については、コアのエラーに対応して Python の Exception を投げるように実装されていますね（薄い wrapper が意識されている）。

ただ、forwarder 系の API は元々 `SynthesisEngine._synthesis_impl` メソッドで呼び出される時に、エンジン側で特にエラーハンドリングされていないかも？　と感じました。誤ったクエリに対するエラーを処理するのはエディタの責任になっている印象です。もし「まだロードされていないモデルを用いて音声合成しようとする」クエリを誤ったクエリと考えるなら、エディタ側に `lazy_init` 相当の処理をしてもらうことになる気がします。

一方、それでは利便性が低いと考えるなら、モデルの遅延読み込みの処理だけは特別にエンジン側で責任を持つ、ということになると思うので、`CoreWrapper` の実質的な一つ上の階層である `SynthesisEngine` が `lazy_init` 相当の処理を担当する、というのが良さそうな気がしました。

2022-05-15 05:05 UTC, takana-v commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +                self.load_model(speaker_id)
移動先の候補としてはmake_synthesis_engineくらいかと思います。
（SynthesisEngineへの移動は余計な引数などを追加する必要がありそうなので...）

個人的には、そのままでも良いかな...と思っています。
現状ではコアの判別などの処理を行っているので、`型の変換程度`以上のことをやっていると思います。
個人的に作っていたコアのラッパーくらい薄いラッパーであれば外に出してもいいかと思います。
https://github.com/takana-v/pyvvcore/blob/master/pyvvcore/core.py

2022-05-15 05:06 UTC, PickledChair commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +            self.core.is_model_loaded.restype = c_bool
> 個人的に作っていたコアのラッパーではc_int64で指定していましたが、動作に問題はありませんでした。
https://github.com/takana-v/pyvvcore/blob/master/pyvvcore/core.py#L29-L79

なるほど、参考になります！　ちょっと PR を検討しようと思いました。

2022-05-15 05:23 UTC, PickledChair commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +                self.load_model(speaker_id)
> 移動先の候補としてはmake_synthesis_engineくらいかと思います。
> （SynthesisEngineへの移動は余計な引数などを追加する必要がありそうなので...）

確かに、コアの API が増えるごとに引数が追加され続けるのはちょっと問題がありそうですね。関連する質問なのですが、現状 `SynthesisEngine` に `CoreWrapper` のインスタンスごと渡していない理由は何かありましたでしょうか？

> 個人的には、そのままでも良いかな...と思っています。

これも１つの正解な気がします。ただ、コアの API 別にエラーの扱い方が違う、ということになると思うので、統一性がなくなる恐れはある気がします（後で保守しづらくなるかも？）。このデメリットが小さそうであればそのままでもいい、という感想ですが、ちょっとまだ将来的にどういう辛さがありそうか予想できていません……（デメリットが小さいという保証がない）。

2022-05-15 05:27 UTC, PickledChair requested changes
すみません、引数の型に関して指摘漏れがあったので、確認いただければ幸いです。

2022-05-15 05:27 UTC, PickledChair commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +            return self.core.load_model(c_int(speaker_id))
```suggestion
            return self.core.load_model(c_long(speaker_id))
```

2022-05-15 05:27 UTC, PickledChair commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +            return self.core.is_model_loaded(c_int(speaker_id))
```suggestion
            return self.core.is_model_loaded(c_long(speaker_id))
```

2022-05-15 05:33 UTC, takana-v commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +                self.load_model(speaker_id)
> 現状 SynthesisEngine に CoreWrapper のインスタンスごと渡していない理由は何かありましたでしょうか？

coreモジュール（ctypes以前）の時の実装を引き継いだため、関数のみ渡す形になっています。

https://github.com/VOICEVOX/voicevox_engine/blob/release-0.10/voicevox_engine/synthesis_engine/make_synthesis_engine.py

2022-05-15 05:50 UTC, PickledChair commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +                self.load_model(speaker_id)
> coreモジュール（ctypes以前）の時の実装を引き継いだため、関数のみ渡す形になっています。

なるほど、わかりました！

コアの API のほとんどが `SynthesisEngine` で使われるような設計になっている（`CoreWrapper` のインスタンスと `SynthesisEngine` のインスタンスが一対一対応になっている）と思ったので、`SynthesisEngine` の初期化時に `CoreWrapper` のインスタンスごと渡してしまっても良いのではないか？　と感じた次第です。この場合、`SynthesisEngine` の初期化時の引数の増加がなくなると思いました。

2022-05-15 09:44 UTC, takana-v commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +                self.load_model(speaker_id)
確かにインスタンスごと渡せば引数の増加を防げそうですね。
初期から関数で渡す実装になっていたので、念のため @Hiroshiba さんに変更して大丈夫か確認していただきたいです。
また、この変更をこのPRで行うか、いったんこのままマージして別PRとして行うべきかもお聞きしたいです。

2022-05-15 09:58 UTC, Hiroshiba commented on voicevox_engine/synthesis_engine/core_wrapper.py
> +                self.load_model(speaker_id)
良いと思います！！

このまま実装しちゃっても、別PRにしちゃっても、はたまたコメントで残しておくだけでも･･･！

2022-05-15 12:40 UTC, Hiroshiba approved these changes
LGTM！！

2022-05-15 13:46 UTC, PickledChair approved these changes
LGTM！

2022-05-15 13:47 UTC, merged