製品のマニフェストを取ってくる
VOICEVOX/voicevox_engine pull request #429
Opened 2022-07-01 17:00 UTC by Hiroshiba

## 内容

製品版のマニフェストを取ってくるようにします。

update_infos.jsonとmanifest.jsonはマージするようにしてみました。

## 関連 Issue

close #416

## その他

こちらでビルドをお試し中です。
https://github.com/Hiroshiba/voicevox_engine/releases/tag/check-manifest-5

2022-07-01 17:02 UTC, Hiroshiba commented
@takana-v さんと、もしよければ @sevenc-nanashi さんももしよかったらレビュー頂けると嬉しいです･･･！

2022-07-01 20:10 UTC, sevenc-nanashi requested changes

2022-07-01 20:10 UTC, sevenc-nanashi commented on manifest_assets/manifest.json
> +    "icon": "icon.png",
```suggestion
    "icon": "manifest_assets/icon.png",
```
そのエンジンのルートからのパスにした方が良いと思いました

2022-07-02 05:40 UTC, Hiroshiba commented on manifest_assets/manifest.json
> +    "icon": "icon.png",
manifest.jsonがある場所からの相対パスが綺麗かなーと思ったので変えてみました。
が、runコマンドはエンジンのルートからなのにこっちはassetディレクトリからなので、変なことになってますね。。

manifest.jsonを`engine_manifest.json`という名前に変更してルートに配置するとかが丸いかも･･･？
（`engine_manifest`という名前にするのは、エンジンのルートがそのままソフトウェアのディレクトリに展開されるので、何のマニフェストかわからなくなるためです）

2022-07-02 06:15 UTC, sevenc-nanashi commented on manifest_assets/manifest.json
> +    "icon": "icon.png",
なるほど、そっちのほうがよさそうです

2022-07-02 13:17 UTC, Hiroshiba commented on manifest_assets/manifest.json
> +    "icon": "icon.png",
38c807d で対応しました！

2022-07-02 13:32 UTC, Hiroshiba commented on manifest_assets/manifest.json
> +    "icon": "icon.png",
対応しましたー！

2022-07-02 14:02 UTC, takana-v approved these changes
LGTM！
readmeのビルド手順の更新もしておくと良さそうです。

2022-07-02 14:39 UTC, sevenc-nanashi approved these changes

2022-07-03 14:39 UTC, Hiroshiba commented
READMEを更新し、テストが通るようになったのでマージします！

2022-07-03 14:39 UTC, merged