コード署名する
VOICEVOX/voicevox_engine pull request #430
Opened 2022-07-05 14:22 UTC by Hiroshiba

## 内容

run.exeをコード署名します。

証明書.pfxファイルをbase64エンコードしたものをsecret.CERT_BASE64に登録し、
証明書のパスワードをsecret.CERT_PASSWORDに登録して、
workflow_dispatchで「コード署名する」にチェックを入れてbuild.ymlを起動すれば、
core.dllが署名されます。

もしくはcode_signingenvironmentを作成し、同様にCERT_BASE64とCERT_PASSWORDを登録して実行しても署名できます。
（こちらのフローは、OSSリポジトリ上でビルドする場合を想定しています。）

「コード署名する」にチェックを入れずにビルドしたり、releaseを作ってビルドした場合は署名用のコードが実行されないので、メンテナー以外の方は今まで通りにテストビルドができます。

## 関連 Issue

- https://github.com/VOICEVOX/voicevox_core/pull/164

## スクリーンショット・動画など

## その他

2022-07-08 09:28 UTC, y-chan approved these changes
LGTMです

2022-07-09 15:12 UTC, PickledChair requested changes
`environment` の仕様・使い方についてよく知らないこともあり、うまく動くのかどうか自信が持てない部分があったので質問しました（あと typo を発見したのでコメントしました）。ご確認いただければと思います……！

2022-07-09 15:12 UTC, PickledChair commented on .github/workflows/build.yml
> +    environment: ${{ github.event.inputs.code_signing == 'true' && 'code_signing' }} # コード署名用のenvironment
`environment` の使い方に詳しくないのですが、自分が調べた限り、文字列を指定しない場合（ `github.event.inputs.code_signing` が `false` の場合）の挙動がどうなるのかよくわかりませんでした……。

（こちらのドキュメントを読んで見ていました https://docs.github.com/ja/actions/deployment/targeting-different-environments/using-environments-for-deployment ）

コードの意図としては「`github.event.inputs.code_signing` が `true` でないとき、リポジトリの `environment` として `code_signing` が設定されている必要はない」ということだと思うのですが、その意図通りに動くのかちょっと自信が持てていません。もし参考にした例やドキュメント等がありましたら教えていただければ判断材料になると思うので助かります！

それから、実際に `github.event.inputs.code_signing` を `false` にしてビルドしたときどうなるのかを確認できればと思います……！

2022-07-09 15:12 UTC, PickledChair commented on .github/workflows/build.yml
> +          prelease: ${{ github.event.inputs.prerelease }}
typo と思われます……！

```suggestion
          prerelease: ${{ github.event.inputs.prerelease }}
```

2022-07-10 09:15 UTC, Hiroshiba commented on .github/workflows/build.yml
> +    environment: ${{ github.event.inputs.code_signing == 'true' && 'code_signing' }} # コード署名用のenvironment
無指定や存在しないenvironmentを指定した場合の挙動はドキュメントに書いていませんでした。
実際に試してみて、スルーされることを確認した感じです。

別リポジトリですが、実際に無指定にしてみた例がこちらにあります！
https://github.com/Hiroshiba/check_code_signing/runs/7269556780?check_suite_focus=true
コード署名ファイルがないので途中で落ちていますが、指定されたenvironmentが存在しないという理由ではありませんでした。

voicevox engineでのビルドはこちらで試しはじめました。
https://github.com/Hiroshiba/voicevox_engine/actions/runs/2644112262

2022-07-10 09:15 UTC, Hiroshiba commented on .github/workflows/build.yml
> +          prelease: ${{ github.event.inputs.prerelease }}
ほんとだ、ありがとうございます！

2022-07-10 09:50 UTC, PickledChair requested changes
`environment` の指定に関しては了解しました！　追加で変更が必要と思われる箇所を見つけたのでコメントしました。

2022-07-10 09:50 UTC, PickledChair commented on .github/workflows/build.yml
> +    environment: ${{ github.event.inputs.code_signing == 'true' && 'code_signing' }} # コード署名用のenvironment
> 実際に試してみて、スルーされることを確認した感じです。

なるほど、了解しました！　未定義動作の可能性はありますが、目的は達成されそうなので、とりあえずこれで運用してみるということで良さそうです（未定義動作である可能性があることをコメントで書いておくと、後々 GitHub 側の仕様変更に伴って挙動が変わってしまった時に原因調査しやすい気がしたので、コメントがあればなお良いのかも？　とは感じました）。

2022-07-10 09:50 UTC, PickledChair commented on .github/workflows/build.yml
> +        if: github.event.inputs.code_signing
`github.event.inputs.code_signing` は文字列、とのことなので、以下の修正が必要と思いました！ https://github.com/Hiroshiba/check_code_signing/runs/7269556780?check_suite_focus=true で `github.event.inputs.code_signing` が `false` なのになぜ署名しようとしているのだろうと疑問に思ったので気づきました。

（基本的には `!==` 演算子を使うべきと思ったりしたのですが、他の箇所では基本的に `!=` を使っている感じだと思うので、そちらに合わせました……）

```suggestion
        if: github.event.inputs.code_signing != 'true'
```

2022-07-10 10:01 UTC, Hiroshiba commented on .github/workflows/build.yml
> +    environment: ${{ github.event.inputs.code_signing == 'true' && 'code_signing' }} # コード署名用のenvironment
コメントに関してなるほどです！
仕様変更が入った時ここがエラーで止まるので原因調査難度はあまり変わらないかも･･･？
とりあえず `false時の挙動は2022年7月10日時点で未定義動作` みたいなコメントを書いてみようと思います。

2022-07-10 10:02 UTC, Hiroshiba commented on .github/workflows/build.yml
> +    environment: ${{ github.event.inputs.code_signing == 'true' && 'code_signing' }} # コード署名用のenvironment
```suggestion
    environment: ${{ github.event.inputs.code_signing == 'true' && 'code_signing' }} # コード署名用のenvironment（false時の挙動は2022年7月10日時点で未定義動作）
```

2022-07-10 10:08 UTC, Hiroshiba commented on .github/workflows/build.yml
> +        if: github.event.inputs.code_signing
修正が漏れていました！！ありがとうございます！！

2022-07-10 10:17 UTC, PickledChair approved these changes
LGTM！

2022-07-12 10:17 UTC, merged