coreがmodelファイルを切り出したのでビルド周りを追従する
VOICEVOX/voicevox_engine pull request #569
Opened 2023-01-09 10:50 UTC by Hiroshiba

## 内容

コアがmodelディレクトリにあるファイルを読む形になったので追従します。

## 関連 Issue

close #568

## その他

docker版の方は実行まで確認しています。
実行バイナリの方はビルドできそうなところまで確認しましたが、実行は未確認です。

2023-01-09 11:26 UTC, Hiroshiba commented
とりあえず7zコマンドは動いていそうでした･･･！
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/4987327/211297073-c4018e61-eb1e-46bd-891f-58d08930b7ef.png">

2023-01-09 13:12 UTC, Hiroshiba commented
実際音声合成できるかチェックしてるreleaseテストも含めて全部通ってるので大丈夫だと思います！
https://github.com/Hiroshiba/voicevox_engine/actions/runs/3873419712

2023-01-09 13:13 UTC, Hiroshiba commented
@y-chan さん、 @PickledChair さん、見て頂いても良いでしょうか･･･？（変更２２行です🙇）

2023-01-09 14:51 UTC, PickledChair requested changes
リリースビルドの方は問題なさそうでした！（アーティファクトをローカルにダウンロードして実行してみましたが、正常に動作していそうでした。）

Dockerfile が期待通りに使用できるかどうかは試していないのですが、少し問題がありそうだったのでコメントしました。

2023-01-09 14:51 UTC, PickledChair commented on Dockerfile
> +    mv ./core/ /opt/voicevox_core/
- `/opt/voicevox_core/` ディレクトリが事前に作られていないため、エラーになりそうでした。
- `mv ./core/ /opt/voicevox_core/` だと `/opt/voicevox_core/core/...` というディレクトリの構造になると思いますが、変更前の処理を見るに `/opt/voicevox_core/libvoicevox_core.so` のように `core/` ディレクトリをはさまないような構造を想定していると思いました。`mv ./core/* /opt/voicevox_core/` として、`core/` ディレクトリ以下のファイルが直接 `/opt/voicevox_core/` ディレクトリに展開されるようにすると良さそうでした。

```suggestion
    # Move Core to /opt/voicevox_core/
    mkdir /opt/voicevox_core
    mv ./core/* /opt/voicevox_core/
```

2023-01-09 16:01 UTC, Hiroshiba commented on Dockerfile
> +    mv ./core/ /opt/voicevox_core/
ありがとうございます！！
これ（`mv ./core/ /opt/voicevox_core/`）、やってることは`./core/`ディレクトリを`/opt/voicevox_core/`にリネームなので、むしろディレクトリが存在しないことで正しい挙動になってる感じです！

でもこれ`/opt/voicevox_core/`のディレクトリ有無で挙動が変わるのでかなり危ないなと思いました。
なので提案されている形のほうが良さそうです！！

2023-01-09 16:13 UTC, y-chan approved these changes
LGTMです！

2023-01-10 02:56 UTC, PickledChair commented on Dockerfile
> +    mv ./core/ /opt/voicevox_core/
> ありがとうございます！！ これ（`mv ./core/ /opt/voicevox_core/`）、やってることは`./core/`ディレクトリを`/opt/voicevox_core/`にリネームなので、むしろディレクトリが存在しないことで正しい挙動になってる感じです！

すみません、意図を勘違いして、内容的にも間違った指摘をしていました。説明ありがとうございます！　問題ありませんでしたね。

> でもこれ`/opt/voicevox_core/`のディレクトリ有無で挙動が変わるのでかなり危ないなと思いました。 なので提案されている形のほうが良さそう！！

こちら了解です！

2023-01-10 02:57 UTC, PickledChair approved these changes
LGTMです！　マージします。

2023-01-10 03:13 UTC, merged