update_dictのリファクタリング
VOICEVOX/voicevox_engine pull request #630
Opened 2023-02-24 10:47 UTC by Hiroshiba

## 内容

`update_dict`の処理が複雑化していたので、意図をコメントに書きつつ流れを整理しました。

## 関連 Issue

- https://github.com/VOICEVOX/voicevox_engine/issues/419

2023-02-24 12:28 UTC, PickledChair reviewed
一時ファイルの削除操作まわりでちょっと気になった点を見つけたのでコメントしました（自分もちょっとよく分かっていないところがあるので、もし気にしすぎでしたらすみません）。

2023-02-24 12:28 UTC, PickledChair commented on voicevox_engine/user_dict.py
> +        tmp_compiled_path = Path(tmp_compiled_file.name).resolve()
`NamedTemporaryFile` 関数で `delete=True` に設定すれば（デフォルトで `True` なので未指定にすれば）、`with` 構文で

```python
with NamedTemporaryFile(
    prefix="tmp_csv_", dir=save_dir
) as tmp_csv_file, NamedTemporaryFile(
    prefix="tmp_compiled_", dir=save_dir
) as tmp_compiled_file:

    tmp_csv_path = Path(tmp_csv_file.name).resolve()
    tmp_compiled_path = Path(tmp_compiled_file.name).resolve()
    ...
```

と書くと、最後の `finally` 節でのファイルの削除操作がいらなくなる（エラー発生時にも `with` を抜けたときに自動 close および 自動 unlink される）と思いました。

`delete=False` の設定に明確な理由があるかもしれないので、変えて良いかどうかちょっと気になりますが……（おそらくユーザー辞書機能の実装当初からこの設定だったのだと思うので、 @takana-v さんが何かご存知かもしれません）。

2023-02-24 12:28 UTC, PickledChair commented on voicevox_engine/user_dict.py
> +            tmp_compiled_path.unlink()
ファイル削除の前にファイルを close した方が良いと思いました（あるいは、`NamedTemporaryFile` 関数を `delete=True` の設定で `with` 構文で使うとファイルの削除処理が不要になりそうでした）。

一応 macOS で手元で同様のコードを実行したところ、意図通り削除されるようではあったのですが、調べたところ close されていないファイルの削除が成功するかどうかは OS 依存で、Windows では失敗するというような記述を見つけました (cf. https://stackoverflow.com/questions/48315926/should-a-file-be-closed-before-removing ) 。

```suggestion
        if tmp_csv_path is not None and tmp_csv_path.exists():
            tmp_csv_file.close()
            tmp_csv_path.unlink()
        if tmp_compiled_path is not None and tmp_compiled_path.exists():
            tmp_compiled_file.close()
            tmp_compiled_path.unlink()
```

（実際に Windows でも元のコードで問題なさそうでしたら、このままでも良いかもしれません。私は以下のようなコードで `./test` ディレクトリ内に作られた一時ファイルが削除されるかどうかを確認しました。macOS では意図どおり削除されました）

```python
from tempfile import NamedTemporaryFile
from pathlib import Path

test_dir = Path("test")
test_dir.mkdir(exist_ok=True)

f = NamedTemporaryFile(mode="w", delete=False, dir=str(test_dir))
fpath = Path(f.name).resolve()
print("fpath:", fpath)

fpath.write_text("hogehoge", encoding="utf-8")

if fpath is not None and fpath.exists():
    # f.close()
    fpath.unlink()
```

2023-02-24 13:04 UTC, takana-v commented on voicevox_engine/user_dict.py
> +        tmp_compiled_path = Path(tmp_compiled_file.name).resolve()
`pyopenjtalk.create_user_dict`が排他処理で、ファイルを開いたままだとエラーが発生してしまうためだった記憶があります。
なので、`delete=False`にして、ファイルを閉じても削除されないようにし、ファイルを閉じた後に`pyopenjtalk.create_user_dict`を実行、その後に削除、という流れにしたはずです。

2023-02-24 13:36 UTC, PickledChair requested changes
コメントを追加しました

2023-02-24 13:36 UTC, PickledChair commented on voicevox_engine/user_dict.py
> +        tmp_compiled_path = Path(tmp_compiled_file.name).resolve()
> `pyopenjtalk.create_user_dict`が排他処理で、ファイルを開いたままだとエラーが発生してしまうためだった記憶があります。 なので、`delete=False`にして、ファイルを閉じても削除されないようにし、ファイルを閉じた後に`pyopenjtalk.create_user_dict`を実行、その後に削除、という流れにしたはずです。

なるほどです、ありがとうございます！　それであれば `delete=False` のままが良いですね。
`with` を使うとファイルの close は自動でしてくれるはずなので、`try` の中で `with` を使うと良いのかなと思いました。

2023-02-24 13:36 UTC, PickledChair commented on voicevox_engine/user_dict.py
> +        pyopenjtalk.create_user_dict(str(tmp_csv_path), str(tmp_compiled_path))
https://github.com/VOICEVOX/voicevox_engine/pull/630/files#r1116972401 という説明があったので、この関数の実行前に `tmp_csv_file` および `tmp_compiled_file` が close されるべきかも……？

2023-02-24 14:33 UTC, Hiroshiba commented on voicevox_engine/user_dict.py
> +        tmp_compiled_path = Path(tmp_compiled_file.name).resolve()
ここでwithする（openする）と、pyopenjtalk君が書き込めないんですよね･･･。
なので`NamedTemporaryFile`は単純に一時ファイルのパスを作るためだけに使っています。

ちょっとだいぶ意図がわかりにくいので、コメントを書くか`NamedTemporaryFile`を使わないようにするかしようと思います！

2023-02-24 14:56 UTC, PickledChair commented on voicevox_engine/user_dict.py
> +        tmp_compiled_path = Path(tmp_compiled_file.name).resolve()
以前のコードでは以下のようになっていたと思うので、この書き方をすると今回の場合でも `with` で大丈夫そうな気がします。

```python
    with NamedTemporaryFile(
        encoding="utf-8", mode="w", delete=False, dir=save_dir
    ) as f:
        ...
        f.write(default_dict)
        ...
    ...
    # with を抜けたのでファイルは閉じられているが、 f 自体はまだ死んでいないので f.name にアクセスできる
    pyopenjtalk.create_user_dict(
        str(Path(f.name).resolve(strict=True)),
        str(tmp_dict_path),
    )
    delete_file(f.name)
    ...
```

ただ、f が生きている範囲がわかりづらいという欠点もある気がするので、

> コメントを書くかNamedTemporaryFileを使わないようにするかしようと思います！

でも問題ないと思います……！

2023-02-24 15:32 UTC, PickledChair commented on voicevox_engine/user_dict.py
> +        tmp_compiled_path = Path(tmp_compiled_file.name).resolve()
あ、

```python
    tmp_csv_file = NamedTemporaryFile(prefix="tmp_csv_", delete=False, dir=save_dir)
```

という書き方でも一時ファイルが open されているという認識で合っていますか……？（そう考えて、`with` を使う・使わないに関わらず、pyopenjtalk の関数を使う前にファイルの close が必要、という認識でした）

2023-02-24 16:00 UTC, Hiroshiba commented on voicevox_engine/user_dict.py
> +        tmp_compiled_path = Path(tmp_compiled_file.name).resolve()
あ、withを使わない場合はopenされないですね！
withするとopenされる、withから外れるとcloseされてdeleteされる、みたいな感じなはずです。

そもそもpyopenjtalk側がFile Objectを入力できる形になってないので、`NamedTemporaryFile`は相性が悪い気がしました！

2023-02-24 16:13 UTC, Hiroshiba commented on voicevox_engine/user_dict.py
> +            tmp_compiled_path.unlink()
たしかにwindowsだとcloseしていないのでエラーになりました！
`NamedTemporaryFile`の仕様に付き合わず、自分でtmpファイルを作るのが丸いかなと思ったのでそうしてみます！！

2023-02-24 16:16 UTC, Hiroshiba commented on voicevox_engine/user_dict.py
> +        pyopenjtalk.create_user_dict(str(tmp_csv_path), str(tmp_compiled_path))
NamedTemporaryFileの仕様に付き合わず、自分でtmpファイルを作るのが丸いかなと思ったのでそうしてみます！！

2023-02-24 16:58 UTC, PickledChair commented on voicevox_engine/user_dict.py
> +        tmp_compiled_path.replace(compiled_dict_path)
この行は、`tmp_compiled_path` が別ドライブの tmp フォルダに作られなくなったので `Path.replace` の使用に戻したという理解であっているでしょうか？（ #462 の問題を念頭に置いています）

2023-02-24 16:59 UTC, PickledChair approved these changes
LGTM！（１箇所だけ質問しましたが、多分大丈夫そうですかね……？）

2023-02-24 17:46 UTC, Hiroshiba commented on voicevox_engine/user_dict.py
> +        tmp_compiled_path.replace(compiled_dict_path)
あ、ですです！

もう少し意図があって、`shutil.move`はmvできなければcpする感じの処理っぽいんですよね。
Path.replaceはmvできなければエラーになる感じかなと。
ここはMutexを想定している場所なので、cpになってしまうと処理が完了しないままMutexを抜けちゃう可能性がありえるなと思いました。
なのでreplaceに戻そうかなと思った次第でした！

2023-03-12 17:28 UTC, takana-v approved these changes
LGTM！

2023-03-12 17:28 UTC, merged

2023-03-12 20:47 UTC, Hiroshiba commented
（レビューありがとうございます！！）