Docker をリリース時にテストするように追加
VOICEVOX/voicevox_engine pull request #650
Opened 2023-04-02 09:55 UTC by K-shir0

## 内容

- Docker ビルドしたあとに動くかテストを追加
- `check_release_build.py` にて `--skip_run_process` を指定している場合に `process` の起動をスキップできるようにしまた、この変更は Docker 内でプロセスを立ち上げているのにプロセスを立ち上げないようにするためです。

## 関連 Issue

close #564 

## スクリーンショット・動画など

**テストの様子**
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/50326556/229344933-74586578-9c40-4662-861a-e3e0155160d5.png">

## その他

- 一応実行確認済み（模擬的）
- テストの実行時間は大体2分ほど。
- build-docker のビルド部分のコードを変更したのは、`run-release-test-workflow` の `if` 節で `env.〇〇` が使用できなかったため、config の部分で宣言するようにし利用できるようにした。

2023-04-03 01:48 UTC, y-chan commented on .github/workflows/release-test-docker.yml
> +          url="http://localhost:50021/version"
```suggestion
          url="http://127.0.0.1:50021/version"
```

ほぼ誤差みたいなものですが、一旦`127.0.0.1`で統一した方がいいかもです！

ref: #647 #649

2023-04-03 01:50 UTC, y-chan approved these changes
LGTM！

1点だけコメントしましたが、将来的に解決するであろう問題に対するコメントなので、ちょっとどうするか検討したいかもです...!

cc: @Hiroshiba

2023-04-03 10:31 UTC, Hiroshiba commented
まだPR見れてないのですが、127.0.0.1に統一していくのが良いかなと思いました🙏

2023-04-03 15:35 UTC, Hiroshiba requested changes
いくつかコメントしてみました！

実際にrelease-test-dockerを動かすにはreleasesを作る必要があるかもです。
フォーク先のActionsでブランチ指定してbuild-dockerを回せば実行される･･･かも？

2023-04-06 13:05 UTC, K-shir0 commented
コード修正し、 release-test-docker を網羅的にテストしてみました。

この PR とは若干別案件なのですがどうやら、 `ubuntu18.04` がベースとなっている cpu の image が動かないっぽいです。（他の `ubuntu 18.04` ベースのイメージも要確認）自身の環境でも試しましたが、起動後即落ちてるようでログが流れずデバッグが時間かかりそうな感じであまりこちらは見られてないです。

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/50326556/230386229-45c7edae-f6fb-45f4-9e93-dd5cd170fa3c.png">

ただ、反面テスト書かないと `ubuntu 18.04` ベースのイメージを使う人が少なそうで発見できなかったなと感じています。

2023-04-08 00:01 UTC, Hiroshiba commented
> ubuntu18.04 がベースとなっている cpu の image が動かないっぽい

おっと！！　テストの効果が出ててすごくいいですね･･･！！！
個人的にはもうubuntu18のサポートは終了で良いかなと思いました！（@y-chan ping）

ついでにubuntu22追加しちゃっても良いかもですね！
意外とパッとubuntu22では動かなかったりするので別PRのが良いかもですが。

2023-04-08 00:05 UTC, Hiroshiba reviewed
ubuntu18のとこ以外はLGTMです！！

2023-04-10 15:22 UTC, K-shir0 commented
ubuntu22 の検証&対応は別の PR で対応したいと考えてます -> #660

2023-04-10 16:18 UTC, Hiroshiba approved these changes
LGTM！！

修正ありがとうございます！！
ubuntu22対応も嬉しいです！！

2023-04-10 16:18 UTC, merged

2023-04-10 16:20 UTC, Hiroshiba commented
こちらで実際にテストreleaseを作ってみました！
https://github.com/VOICEVOX/voicevox_engine/releases/tag/0.15.0-preview.2

actionsはたぶんこちらです。
https://github.com/VOICEVOX/voicevox_engine/actions/runs/4659151360