CONTRIBUTING.mdの整備
VOICEVOX/voicevox_engine pull request #687
Opened 2023-05-23 16:41 UTC by misogihagi

## 関連 Issue

#686

2023-05-23 21:35 UTC, sevenc-nanashi commented on docs/CONTRIBUTING.md
> +不具合の報告、機能要望、改善提案、質問は<a href="https://github.com/VOICEVOX/voicevox_engine/issues/new">Issue</a>の方に報告してください。
ここはContributingに乗っけるのは少し変な気がしました。

2023-05-23 21:35 UTC, sevenc-nanashi commented on docs/CONTRIBUTING.md
ルートにCONTRIBUTING.mdをおくと特別扱いされる（はず）のでそっちに移動してもいいかもしれません

2023-05-23 21:39 UTC, sevenc-nanashi commented
また、READMEと被る内容がかなりあるので、
- READMEには実行向けのもの（実行セクションとか？）
- CONTRIBUTINGには開発向けのもの（ビルドや環境構築）
みたいに分けるべきだと思いました。

2024-02-26 09:58 UTC, tarepan approved these changes
LGTM!  

👍 インストールから commit まで一連の流れをガイドしており、貢献者がコケづらい良い`CONTRIBUTING.md` です。  
`README.md` との重複や deprecated な記述があるため、これを基礎として一旦 merge し、後続の PR で更に改善するのが適切そうです。  
good work!  

issue #686 に関しては close せず、引き続き track するのが適切に感じます。  

@Hiroshiba  
こちら review 可能です。

2024-02-26 16:26 UTC, Hiroshiba commented
> これを基礎として一旦 merge し、後続の PR で更に改善するのが適切そうです。

なるほどです！
一瞬未完成なコントリビューションガイドラインが現れることになると思うので、ガイドラインの一番上に何かしらのアナウンスがあるといいのかもと思いました！
ちょっと提案してみます！

2024-02-26 16:27 UTC, Hiroshiba commented on CONTRIBUTING.md
> +* [インストール](#インストール)
こんな感じのアナウンスはどうでしょう？ @tarepan 

```suggestion
**このガイドラインは現在工事中です。**

TODO: 重複部分を省く
TODO: deprecated 部分を省く

## 目次

* [インストール](#インストール)
```

2024-02-27 03:49 UTC, tarepan commented on CONTRIBUTING.md
> +* [インストール](#インストール)
👍 ユーザー目線の適切な提案です。進行として非常に参考になります。commit しました。

2024-02-27 03:54 UTC, tarepan requested changes
- [ ] タイポ（`typos` でチェック可能）

2024-02-27 03:54 UTC, tarepan commented on CONTRIBUTING.md
> +* PROCESSER
fix: typo  

```suggestion
* PROCESSOR
```

2024-02-27 03:54 UTC, tarepan commented on CONTRIBUTING.md
> +curl -L https://github.com/VOICEVOX/voicevox_core/releases/download/0.14.3/voicevox_core-${OS}-${arch}-${processer}-${}.zip -o voicevox_core
fix: typo

```suggestion
curl -L https://github.com/VOICEVOX/voicevox_core/releases/download/0.14.3/voicevox_core-${OS}-${arch}-${processor}-${}.zip -o voicevox_core
```

2024-02-27 18:38 UTC, Hiroshiba approved these changes
LGTM！！

@tarepan さんがapproveしたらマージ可能になると思います。
なのでマージしていただければ！

2024-02-28 05:02 UTC, tarepan approved these changes
LGTM!

2024-02-28 05:03 UTC, merged